import { NextRequest, NextResponse } from 'next/server';
import ZAI from 'z-ai-web-dev-sdk';

// Document templates
const documentTemplates: Record<string, (params: {
  candidateName: string;
  position: string;
  startDate: string;
  companyName: string;
}) => string> = {
  'offer-letter': (params) => {
    const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    return `# OFFER LETTER

**Date:** ${date}

**To:** ${params.candidateName}

**Position:** ${params.position}

**Start Date:** ${params.startDate}

---

Dear ${params.candidateName},

We are pleased to offer you the position of ${params.position} at ${params.companyName}. After careful consideration of your qualifications and experience, we believe you will be an excellent addition to our team.

## Terms of Employment

**Position:** ${params.position}  
**Start Date:** ${params.startDate}  
**Location:** Yangon, Myanmar  
**Employment Type:** Full-time

## Compensation

Your starting salary will be discussed and agreed upon in the follow-up meeting. You will also be eligible for our standard benefits package, which includes:

- Health insurance coverage
- Annual leave: 10 days
- Public holidays as per Myanmar calendar
- Professional development allowance

## Next Steps

Please sign and return this letter by [Date] to confirm your acceptance of this offer. If you have any questions, please do not hesitate to contact our HR department.

We look forward to welcoming you to our team!

Best regards,

**HR Department**  
${params.companyName}

---

*Generated by ReferTRM AI Document Processor*`;
  },

  'employment-contract': (params) => {
    const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    return `# EMPLOYMENT CONTRACT

**Contract Date:** ${date}

---

This Employment Contract ("Contract") is entered into between:

**Employer:** ${params.companyName}  
**Employee:** ${params.candidateName}

## 1. Position and Duties

The Employee is employed as **${params.position}** and shall perform all duties as assigned by the Employer, consistent with the position's responsibilities.

## 2. Commencement and Duration

- **Start Date:** ${params.startDate}
- **Employment Type:** Permanent, Full-time
- **Probation Period:** 3 months

## 3. Compensation

- Monthly salary will be communicated separately
- Payment will be made monthly, on the last working day of each month
- Salary reviews will be conducted annually

## 4. Working Hours

- Standard working hours: 9:00 AM to 5:00 PM, Monday to Friday
- Overtime may be required based on business needs

## 5. Leave Entitlement

- Annual Leave: 10 days per year
- Sick Leave: As per Myanmar Labor Law
- Public Holidays: As per Myanmar government calendar

## 6. Termination

Either party may terminate this contract by providing:
- During probation: 1 week notice
- After confirmation: 1 month notice

## 7. Confidentiality

The Employee agrees to maintain confidentiality of all company information, trade secrets, and proprietary data.

## 8. Signatures

**Employer:** _________________ Date: _______

**Employee:** _________________ Date: _______

---

*Generated by ReferTRM AI Document Processor*`;
  },

  'nda': (params) => {
    const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    return `# NON-DISCLOSURE AGREEMENT (NDA)

**Effective Date:** ${date}

---

This Non-Disclosure Agreement ("Agreement") is entered into by and between:

**Disclosing Party:** ${params.companyName}  
**Receiving Party:** ${params.candidateName}

## 1. Purpose

The Disclosing Party wishes to protect its confidential information that may be disclosed to the Receiving Party in the course of employment as ${params.position}.

## 2. Definition of Confidential Information

"Confidential Information" includes, but is not limited to:
- Business strategies and plans
- Financial information and data
- Customer and client information
- Technical and operational procedures
- Trade secrets and intellectual property
- Any other proprietary information

## 3. Obligations

The Receiving Party agrees to:
- Keep all Confidential Information strictly confidential
- Use Confidential Information only for employment purposes
- Not disclose Confidential Information to third parties
- Return all materials containing Confidential Information upon termination

## 4. Duration

This Agreement shall remain in effect during employment and for 2 years after termination of employment.

## 5. Consequences of Breach

Any breach of this Agreement may result in:
- Termination of employment
- Legal action for damages
- Injunctive relief

## 6. Signatures

**Disclosing Party:** _________________ Date: _______

**Receiving Party:** _________________ Date: _______

---

*Generated by ReferTRM AI Document Processor*`;
  },

  'experience-letter': (params) => {
    const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    return `# EXPERIENCE LETTER

**Date:** ${date}

---

**To Whom It May Concern,**

This is to certify that **${params.candidateName}** was employed with ${params.companyName} as **${params.position}**.

During their tenure, they demonstrated excellent professional skills and contributed significantly to our organization. Their responsibilities included:

- Executing duties associated with the ${params.position} role
- Collaborating with team members effectively
- Maintaining high standards of work quality

We found ${params.candidateName} to be a dedicated, hardworking, and reliable team member. They displayed strong work ethics and professional conduct throughout their employment.

We wish ${params.candidateName} all the best in their future endeavors.

**HR Department**  
${params.companyName}

---

*Generated by ReferTRM AI Document Processor*`;
  },

  'promotion-letter': (params) => {
    const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    return `# PROMOTION LETTER

**Date:** ${date}

---

**To:** ${params.candidateName}

Dear ${params.candidateName},

We are delighted to inform you that you have been promoted to the position of **${params.position}**, effective from **${params.startDate}**.

This promotion is in recognition of your outstanding performance, dedication, and valuable contributions to ${params.companyName}. Your hard work and commitment have not gone unnoticed.

## New Position Details

- **Position:** ${params.position}
- **Effective Date:** ${params.startDate}
- **New responsibilities** will be discussed in detail during your transition meeting

We are confident that you will continue to excel in your new role and contribute to the success of our organization.

Please sign below to acknowledge your acceptance of this promotion.

Congratulations on your well-deserved promotion!

Best regards,

**HR Department**  
${params.companyName}

---

**Employee Acknowledgment:**

Name: _________________ Date: _______
Signature: _________________

---

*Generated by ReferTRM AI Document Processor*`;
  },
};

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const {
      docType,
      candidateName,
      position,
      startDate,
    } = body;

    // Validate required fields
    if (!candidateName || !position) {
      return NextResponse.json(
        { success: false, error: 'Candidate name and position are required' },
        { status: 400 }
      );
    }

    // Try AI generation first
    try {
      const zai = await ZAI.create();
      
      const completion = await zai.chat.completions.create({
        messages: [
          {
            role: 'system',
            content: `You are a professional HR document specialist for Myanmar companies. Generate formal, legally-compliant HR documents. Use clear, professional language appropriate for Myanmar business context. Include all necessary sections and legal language where applicable.`,
          },
          {
            role: 'user',
            content: `Generate a ${docType.replace('-', ' ')} for:
- Employee Name: ${candidateName}
- Position: ${position}
- Start Date: ${startDate || 'TBD'}
- Company: ReferTRM Partner Company

Make it professional, complete, and ready to use. Format in markdown.`,
          },
        ],
        temperature: 0.3,
        max_tokens: 2000,
      });

      const document = completion.choices?.[0]?.message?.content || '';

      return NextResponse.json({
        success: true,
        document,
        docType,
        generatedAt: new Date().toISOString(),
      });
    } catch (aiError) {
      console.log('AI document generation failed, using template:', aiError);
      
      // Fallback to template
      const template = documentTemplates[docType];
      
      if (!template) {
        return NextResponse.json(
          { success: false, error: 'Invalid document type' },
          { status: 400 }
        );
      }

      const document = template({
        candidateName,
        position,
        startDate: startDate || 'To Be Determined',
        companyName: 'Our Company',
      });

      return NextResponse.json({
        success: true,
        document,
        docType,
        generatedAt: new Date().toISOString(),
        template: true,
      });
    }
  } catch (error) {
    console.error('Document generation error:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to generate document' },
      { status: 500 }
    );
  }
}
