-- ============================================
-- CV Lead Tracker - Batch 4 of 5
-- Leads 1501 to 2000
-- ============================================

INSERT INTO leads (name, email, phone, current_position, skills, status, source, notes) VALUES
('Ye Yint Htet', 'yairyinthtet98@gmail.com', '09781997119', 'Sales & Marketing', 'git, communication, project management', 'active', 'CV Lead Tracker', 'CV: YeYintHtet - Account Executive (MT).pdf'),
('Ei That Paing', 'eithetpaing264@gmail.com', '959783213123', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Ei That Paing - Account Executive.pdf'),
('Si Thu Lwin', 'sithulwin.mechanicalpower@gmail.com', '959770370618', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Si Thu Lwin- Service Technician (MT).pdf'),
('Moh Moh Swe Oo', 'mohmohsweoo@gmail.com', '09774760313', 'Management', 'git, leadership', 'active', 'CV Lead Tracker', 'CV: MOH MOH SWE OO- Banca Head (MT).pdf'),
('Eainsic Phone Myint', 'einsicphonemyint.1993@gmail.com', '9425022526', 'Management', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Eainsic Phone Myint - Account Manager (MT).pdf'),
('Race - Myanma R', NULL, '09755112402', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Zun Phoo Wai - Bank Adviosr (Pathein)MT.pdf'),
('About Me', 'Townshipeishwesintun63@gmail.com', NULL, 'Sales & Marketing', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Ei Shwe Sin Tun - Bank Advisor (Pathein)MT.pdf'),
('Curriculum Vate', 'khinminwai41@gmail.com', '09251196301', 'Customer Service', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Khin Min Wai- Bank Advisor (Pathein)MT.pdf'),
('Race - Myanmar', NULL, '09650300679', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Shwe Yee Thin - Bank Advisor (Pathein)MT.pdf'),
('Kyi Lai Phyu Bank', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Kyi Lai Phyu -Bank Advisor (MDY) MT.pdf'),
('Race - Myanma R', NULL, '09680090010', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Kyaw San Htoo - Bank Advisor (Pathein)MT.pdf'),
('Thu Ra Zin Bank', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Thu Ra Zin - Bank Advisor (Pathein)MT.pdf'),
('Noe Wai', 'noe254254@gmail.com', '09459388690', 'Management', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Khine Myat Noe Wai - Bank A (Pathein)MT.pdf'),
('Yoon Shweyee Thant', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Yoon Shweyee Thant - Sales (Pathein)MT.pdf'),
('Pathein University', 'hnineiwailwin1122@gmail.com', '09253855397', 'Legal', NULL, 'active', 'CV Lead Tracker', 'CV: Hnin Ei Wai Lwin - Bank Advisor (Pathein)MT.pdf'),
('Seine Lai May', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Seine Lai May - Sales (MT).pdf'),
('Race - Myanma R', 'thiri235656@gmail.com', '0968456123', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Thiri Aye Aye Naing - Bank Advisor (Pathein)MT.pdf'),
('Yoon Shweyee Thant Ba', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Yoon Shweyee Thant - BA (Pathein)MT.pdf'),
('Ndar Pyae Phyo Banca', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Sandar Pyae Phyo - Banca pathein (MT).pdf'),
('Phyu Thet Hnin', 'phyuthethnin912@gmail.com', '09968512711', 'Customer Service', 'excel', 'active', 'CV Lead Tracker', 'CV: Phyu Thet Hnin - Sales (MT).pdf'),
('Yoon Shweyee Thant Bank', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Yoon Shweyee Thant - Bank Advisor (Pathein)MT.pdf'),
('N.r.c No. - 6/thayakha(n)101185', NULL, '09769283479', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Soe Sandi Zaw - Bank Advisor (Dawai)MT.pdf'),
('Ei Ei Phyo', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Ei Ei Phyo CV - Assistant Accountant (MT).pdf'),
('Aye Aye Nyein M', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Aye Aye Nyein - MCV.pdf'),
('Curriculum Vitae', 'oe1997@gmail.co', '09455511171', 'Finance & Accounting', 'express, excel', 'active', 'CV Lead Tracker', 'CV: CURRICULUM VITAE.pdf'),
('May Zin Kyaw', 'mzin96709@gmail.com', '09751842821', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: May Zin Kyaw - Jr. Accountant (MT).pdf'),
('Career History', 'Pyaynyunt220@gmail.com', '09264670154', 'Customer Service', 'excel, leadership, communication, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: Ms. Thazin.pdf'),
('Ms. Seint Honey Aung', 'seinthoneyaung01@gmail.com', '959774933488', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: seinthoneyaung - Accountant (MT).pdf'),
('Khin Bel Win', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Khin Sabel Win - Accountant.pdf'),
('Aye Thiri Mon', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Aye Thiri Mon (senior Acc).pdf'),
('Detailhnin Theint Phyu Aung', 'hnintheintphyuaung266@gmail.com', '09976816427', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: HninTheint - Accountant (MT).pdf'),
('Chit Chit Soe', NULL, '09455511171', 'Management', 'express, excel, communication', 'active', 'CV Lead Tracker', 'CV: Chit Chit Soe - Jr. Accountant (MT).pdf'),
('Hnin Lae Yi', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Hnin Lae Yi - Junior Accountant (MT).pdf'),
('Career History', 'Pyaynyunt220@gmail.com', '09264670154', 'Customer Service', 'excel, leadership, communication, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: Account Position(3).pdf'),
('Myanmar English', 'thethtarlaymg@gmail.com', NULL, 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: THS CV.pdf (Oct_22).pdf'),
('Htay Win', NULL, NULL, 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Htay Win - Accountant (MT).pdf'),
('Thet Wai', NULL, '09252524568', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Thet Wai - Accountant (MT) (2).pdf'),
('Aye Thiri Mon', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Aye Thiri Mon - accountnat.pdf'),
('Tawe Tar Lin', 'tawetar6800@gmail.com', '09673766800', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Tawe Tar Lin - Accountant (MT).pdf'),
('Kyaw Naing Tun', 'maxsuly471@gmail.com', '09763228152', 'Management', 'analytical', 'active', 'CV Lead Tracker', 'CV: Kyaw Naing Tun - Sale & Accountant.pdf'),
('Yu Yu', 'yuyuaung0000@gmail.com', '09788200997', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Yu Yu Aung(Accountant).pdf'),
('Thin Yu Maw', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Thin Yu Maw- Accoutant (MT).pdf'),
('Khin N Moe', 'khinsanmoe1990@gmail.com', NULL, 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Khin San Moe (Accountant)MT.pdf'),
('Thiha Soe', NULL, '09783365012', 'Finance & Accounting', 'git, excel, communication', 'active', 'CV Lead Tracker', 'CV: Thiha Soe.pdf'),
('Daewi Chit', NULL, NULL, 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Daewi Chit- Finance and account(MT).pdf'),
('Education Background', 'td1993@gmail.com', '9678377478', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: CV.pdf'),
('Khant Khant Moe Htet', NULL, '09962751744', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Khant Khant Moe Htet - Assistant Accountant.pdf'),
('Hnin Wai', 'hninchithtu@gmail.com', '09421048700', 'HR & Admin', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Hnin Wai - Store Accountant (MT).pdf'),
('Aye Mon N', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Aye Mon San - Store Acc (MT).pdf'),
('Zin Hlaing Thin', 'zhlaing032@gmail.com', '09255766013', 'General/Other', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Zin Hlaing Thin - Store Accountant (MT).pdf'),
('May Kay Khine', 'starangel.mkk@gmail.com', '09762391012', 'Finance & Accounting', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: May Kay Khine - Account Receivabel Manager (MT).pdf'),
('Myat Kay Khine', NULL, '09967215840', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Myat Kay Khine - Senior A (MT).pdf'),
('Form Esz', NULL, '09256154462', 'Engineering', 'aws', 'active', 'CV Lead Tracker', 'CV: CV Form esz.pdf'),
('Myat Su Khine', 'mirableke1986@gmail.com', '09981912825', 'Management', 'aws, excel', 'active', 'CV Lead Tracker', 'CV: Myat Su Khine - Senior Accountant (MT).pdf'),
('Phoo Paing', NULL, '09250091995', 'HR & Admin', 'git, excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Phoo Paing - Senior Accountant (MT).pdf'),
('Shwe Ye Win Lae', 'shweyee2025@gmail.com', NULL, 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Shwe Ye Win Lae - Senior Accountant (MT).pdf'),
('W Yu Nandar', 'nsawyu00@gmail.com', '09981999141', 'Finance & Accounting', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Saw Yu Nandar - SA (MT).pdf'),
('Yimon Myint', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Yimon Myint - SA (MT).pdf'),
('Htet Htet Oo', 'thetthetoo8110@gmail.com', '09799632321', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Htet Htet Oo - Senior Accountant (MT).pdf'),
('Personal Information', NULL, '09791670577', 'Finance & Accounting', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Kaung Myat Lin - Financial Analyst (MT).pdf'),
('Lai Aung Zaw Myo', 'salaiaungzawmyo175@gmail.com', '09405489680', 'Management', 'sql, excel, powerpoint, photoshop, leadership, communication', 'active', 'CV Lead Tracker', 'CV: SALAI AUNG ZAW MYO - Senior Accountant (MT).pdf'),
('Ei Ei Theint', 'eieitheint.myg07@gmail.com', NULL, 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Ei Ei Theint - Senior Accountant (MT).pdf'),
('Aye Aye Khaing', 'ayeayekhaing.1297@gmail.com', '09788100731', 'Management', 'excel, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Aye Aye Khaing - SA (MT).pdf'),
('Theint Theint Htwe', 'theinttheinthtwe27@gmail.com', '09953473070', 'Customer Service', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Theint Theint Htwe - Senior Accountant.pdf'),
('Thiri Mon', 'thirimon78@gmail.com', '09965731265', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Thiri_Mon - Senior Accountant (MT).pdf'),
('Ei Myat Pwint Phyu', 'eimyatpwintphyu07@gmial.com', '09258415513', 'Management', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Ei Myat Pwint Phyu - Senior Accountant.pdf'),
('Ei Phyo', 'eiphyozin1997@gmail.com', NULL, 'Engineering', 'sql, excel, problem solving', 'active', 'CV Lead Tracker', 'CV: Ei Phyo - SA (MT).pdf'),
('Khin Ndar Lin', 'Sandar.ksl@gmail.com', '09799638310', 'Management', 'sql', 'active', 'CV Lead Tracker', 'CV: Khin Sandar Lin - Senior Account (MT).pdf'),
('Khin Moe Moe Hlaing', 'khinmoemoehlaing629@gmail.com', '09955463092', 'Finance & Accounting', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Khin Moe Moe Hlaing - Senior Accountant.pdf'),
('Aye Thida Tun Sr', 'exemptionayethida916@gmail.com', '959254971876', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Aye Thida Tun - Sr Accountatn (MT).pdf'),
('Theint Theint', 'thaintthaintaung@gmail.com', '09420046078', 'Management', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Theint Theint Resume - Senior Accountant (MT).pdf'),
('Ma Nan Mon Nyein', 'nanmonnyein@gmail.com', '09425295580', 'Finance & Accounting', 'sql, excel', 'active', 'CV Lead Tracker', 'CV: Nan - Senior Accountant (MT).pdf'),
('Su Hlaing Win', 'susushtw11197@gmail.com', NULL, 'Finance & Accounting', 'sql, excel', 'active', 'CV Lead Tracker', 'CV: Su Hlaing Win - Senior Accountant (MT).pdf'),
('Thidar', 'hanifar786@gmail.com', '09958771782', 'Management', 'excel, powerpoint, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Thidar Aye(SA).pdf'),
('Ei Shwe Zin Moe', 'eishwesinmoe853@gmail.comEducation', NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Ei Shwe Zin Moe - SA (MT).pdf'),
('Thet Thet Oo', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Thet Thet Oo - SA (MT).pdf'),
('Thawdar Lamin Supervisor', 'thawtarlamin1298@gmail.com', '09758545618', 'Management', 'excel, leadership, problem solving', 'active', 'CV Lead Tracker', 'CV: Thawdar Lamin - Supervisor Accountant (MT).pdf'),
('Hnin Hnin Aye', 'hninhnina7@gmail.com', NULL, 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Hnin Hnin Aye - Senior Accountant (MT).pdf'),
('Wai Wai Thin', 'flamingousgirl@gmail.com', '959252718596', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Wai Wai Thin - SA (MT).pdf'),
('Yu Yu Maw Ount', 'yuyumaw27488@gmail.com', '09780348776', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: YU YU MAW senior account (MT).pdf'),
('Nay Va La', 'nayvala.naynay1994@gmail.com', '09444735550', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Nay Va La - Senior Accountant (MT).pdf'),
('Ei Shwe Sin Moe', 'eishwesinmoe853@gmail.comEducation', NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Ei Shwe Sin Moe - SA (MT).pdf'),
('Cho Mar Tun', 'chomartun3.2@gmail.com', '09422493788', 'Finance & Accounting', 'problem solving', 'active', 'CV Lead Tracker', 'CV: Cho Mar Tun - Senior A (MT).pdf'),
('Thin Nu Swe', 'thinnuswe01@gmail.com', '09450132974', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Senior Accountant_TNS.pdf'),
('Phuu Phuu Mon Thet', 'phoophoomonthet@gmail.com', '09964273061', 'Engineering', 'sql, excel', 'active', 'CV Lead Tracker', 'CV: Phuu Phuu Mon Thet (Senior Account) _ MT.pdf'),
('Aaindray Phyo Naing', 'aeindrayphyomaung@gmail.com', '09977432980', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Aaindray Phyo Naing - Senior Accountant (MT).pdf'),
('Myint Myint Khaing', 'myintmyint1554@gmail.com', NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Myint Myint Khaing - SA (MT).pdf'),
('Zar Chi Oo', 'zarchioo972@gmail.com', '09260347059', 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Zar Chi Oo - Senior Accountant (MT).pdf'),
('May Zin Oo', 'mayzinoostella352001@gmail.com', NULL, 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: May Zin Oo - SA (MT).pdf'),
('Khaing Nyein Latt', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Khaing Nyein Latt - Senior A (MT).pdf'),
('Mu Mu Win', 'mumu.win.1992@gmail.com', '09420071770', 'Finance & Accounting', 'sql, excel, problem solving', 'active', 'CV Lead Tracker', 'CV: Mu Mu Win - Senior Accoutnant (MT).pdf'),
('Hsu Myat Phyu Sin', 'hsumyatphyusin1.sin1@gmail.com', '9799441448', 'Management', 'git, communication', 'active', 'CV Lead Tracker', 'CV: Hsu Myat Phyu Sin - Senior Accountant (MT).pdf'),
('Tin Aye Hlaing', NULL, NULL, 'Finance & Accounting', 'communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Tin Aye Hlaing - SA (MT).pdf'),
('Me Me Kyaw', 'memkyaw2412@gmail.com', '09955327725', 'Management', 'excel, analytical', 'active', 'CV Lead Tracker', 'CV: Me Me Kyaw - Senior Accountant (MT).pdf'),
('Khaing Zin Nwe', 'kzinnwe14@gmail.com', '09777859599', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Khaing Zin Nwe - Senior Accountant (HTY)MT.pdf'),
('Mo Mo Nge', NULL, NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Mo Mo Nge - Senior Accountant (MT).pdf'),
('Ei Theingi Pyae Sone', 'eempty397@gmail.com', '09750095017', 'Finance & Accounting', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Ei Theingi Pyae Sone  - Senior Accountant (MT).pdf'),
('Thae Thinzar Win', NULL, '09951823232', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Thae Thinzar Win - Senior A (MT).pdf'),
('Than Htike Aung', 'htike.mue.stu@gmail.com', '959794466749', 'Management', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Than Htike Aung - Senior Accountant (MT).pdf'),
('May Thazin Kyu', 'maythazinkyuu@gmail.com', NULL, 'HR & Admin', 'excel, communication, analytical', 'active', 'CV Lead Tracker', 'CV: May Thazin Kyu - Senior Accoutant (MT).pdf'),
('Zin Mar Htet', 'zinmarhtet.mm.33@gmail.com', '09989095517', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Zin Mar Htet - SA (Con)MT.pdf'),
('Ma Aye Thidar', 'athidar465@gmail.com', '09793973580', 'Finance & Accounting', 'excel, photoshop, communication', 'active', 'CV Lead Tracker', 'CV: Ma Aye Thidar -Senior Accountant (MT).pdf'),
('Thandar Lwin', 'thandarlwin572002@gmail.com', NULL, 'Management', 'git, excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Thandar Lwin - Senior Accountant (MT).pdf'),
('Ei Ei Khine', 'eikhinghtoo82@gmail.com', NULL, 'Management', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Ei Ei Khine -SA (MT).pdf'),
('Myo Thandar', 'myothandar42585@gmail.com', '09425854288', 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Myo Thandar - Senior A Hotel (MT).pdf'),
('Ei Ei Phyo', 'eieiphyo13@gmail.com', '09796453700', 'Management', 'aws, excel', 'active', 'CV Lead Tracker', 'CV: EI EI PHYO -SA (Hotel))MT.pdf'),
('Shwe Yamin Oo', 'symo2722002@gmail.com', '09953713138', 'Engineering', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Shwe Yamin Oo - SA (MT).pdf'),
('Khin Zarni Shein', '43042545januarynoelay123@gmail.com', NULL, 'Management', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Khin Zarni Shein - SA (MT).pdf'),
('Nyo Mi Mi Yin', 'nyomimiyin@gmail.com', '09257768821', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Nyo Mi Mi Yin - Senior Accountant (MT).pdf'),
('Nyo Mi Mi Lwin', 'nyomimiyin@gmail.com', '09257768821', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Nyo Mi Mi Lwin - Senior Accountant (MT).pdf'),
('Arkar Soe', NULL, NULL, 'Engineering', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Arkar Soe -Senior A (MT).pdf'),
('Kyi Seint Seint Thu', 'kyiseintthu1994@gmail.com', '959428018438', 'Management', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Kyi Seint Seint Thu - SA (MT).pdf'),
('Winn Lakk Mon', 'Tsp.dimplewlm95@gmail.com', '9258957482', 'Sales & Marketing', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Winn Lakk Mon - SA (MT).pdf'),
('Thandar Nyunt N', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Thandar Nyunt San - Senior Accountant (Kamaryut).pdf'),
('Yuzana Aung', 'yuzana9092@gmail.com', '09455294077', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Yuzana_Aung - SA (MT).pdf'),
('Aye Mya Hmwe', 'ayemyahmwe7777@gma.co', '09262768083', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Aye Mya Hmwe - Senior Accountant (MT).pdf'),
('Kyu Kyu Lay', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: KYU KYU LAY  - Senior A (MT).pdf'),
('Aye Aye', '4@gmail.com', '09409227711', 'Finance & Accounting', 'excel, powerpoint, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: Aye Aye - SA (MT).pdf'),
('Personal Information', 'eieikhaing1031991@gamil.com', NULL, 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: EEK - Senior A (MT).pdf'),
('Myo Thiri Aung', 'myothiriaung1126@gmail.com', NULL, 'Finance & Accounting', 'sql, excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Ms. Myo Thiri Aung- SA (MT).pdf'),
('Thin Zar Li Kyaw', 'thinzarlikyaw1994@gmail.com', '09762713083', 'Management', 'sql, excel, communication', 'active', 'CV Lead Tracker', 'CV: Thin Zar Li Kyaw - Senior A (MT).pdf'),
('Aye Chan Mi Mi', 'ayechanmimi9@gmail.com', NULL, 'HR & Admin', 'communication', 'active', 'CV Lead Tracker', 'CV: Aye Chan Mi Mi - SA (MT).pdf'),
('Su Su Thin', 'susuthin.mk.mdy@gmail.com', '09976191620', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Su Su Thin - Senior Accountant (MT).pdf'),
('Wutt Yi Kyaw', 'wutyi23007@gmail.com', '09421123007', 'Management', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Wutt Yi Kyaw - SA (Tharkata) MT.pdf'),
('Htay Myint Kyi', 'htaymyintkyi534@gmail.com', '09445304951', 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Htay Myint Kyi - SA (MT).pdf'),
('Ndar Myint S A', 'sandarmyint159@gmail.com', NULL, 'Engineering', 'excel, leadership, project management', 'active', 'CV Lead Tracker', 'CV: Sandar Myint - S A (MT).pdf'),
('Phyo Nandar Aung', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Phyo Nandar Aung - SA (Const)MT.pdf'),
('Lai Aung Zaw Myo', 'salaiaungzawmyo175@gmail.com', NULL, 'Management', 'sql, excel, powerpoint, photoshop, leadership, communication', 'active', 'CV Lead Tracker', 'CV: SALAI AUNG ZAW MYO - SA (Const)MT.pdf'),
('Khin Myo Htet Tun', 'Yangon.kmhhtun22@gmail.comKHIN', NULL, 'Engineering', 'sql, aws, excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Khin Myo Htet Tun - Senior Accountant (MT).pdf'),
('Ohnmar', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Ohnmar - Senior Accountant (MT).pdf'),
('Thet Mon Soe', 'thetmonsoe900@gmail.com', '09740837665', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Thet Mon Soe - JA (MT).pdf'),
('Form Phyu Phyu Aung', NULL, '09403536436', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: CV Form- Phyu Phyu Aung.pdf'),
('Ei Ei Phont', 'eieiponteipont@gmail.com', '09696771427', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Ei Ei Phont - JA (No exp)HTY (MT).pdf'),
('Lae Lae Wai', 'lae173476@gmail.com', '959949071059', 'General/Other', 'communication', 'active', 'CV Lead Tracker', 'CV: Lae Lae Wai - Junior A (No exp) MT.pdf'),
('Cho Win Lae', NULL, '09798219002', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Cho Win Lae - JA (No exp)MT.pdf'),
('Win Pyae Pyae Aung', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Win Pyae Pyae Aung - JA (Frsher)MT.pdf'),
('Htet Ei Kyaw', 'hteteikyaw48@gmail.com', '09770769839', 'Management', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Htet Ei Kyaw - Junior A (no exp) MT.pdf'),
('Nan Ei Wai Lwin', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Nan Ei Wai Lwin - JA (No exp)MT.pdf'),
('Thin Me Me Ko', 'thinmemeko6@gmail.com', '09799940563', 'HR & Admin', 'git, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Thin Me Me Ko - JA (no exp)MT.pdf'),
('Kee Char Nyein', 'keecharjosi@gmail.com', NULL, 'HR & Admin', 'communication', 'active', 'CV Lead Tracker', 'CV: Kee Char Nyein - JA (no exp)MT.pdf'),
('Skillswork Experience', 'maythuthukyaw11@gmail.com', '09783298923', 'Customer Service', 'excel', 'active', 'CV Lead Tracker', 'CV: MTTk - JA (MT).pdf'),
('Myo Thiri Hlaing', 'myothirihlaing0123@gmail.com', '09255490413', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Myo Thiri Hlaing - No exp (MT).pdf'),
('Aye Aye Thin', 'ayeayethin010253@gmail.com', '959696837825', 'Finance & Accounting', 'excel, powerpoint, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Aye Aye Thin - JA (Fresher)MT.pdf'),
('Sein Moh Moh Zin', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Sein Moh Moh Zin - JA (no exp)MT.pdf'),
('Ei Mon Htun', 'Managementeimontun.mm@gmail.com', '+959898100995', 'Engineering', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Ei Mon Htun - JA (no exp)MT.pdf'),
('Aye Pa Pa Kyaw', 'tt4038539@gmail.com', '09884175566', 'Management', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Aye Pa Pa Kyaw - No exp (MT).pdf'),
('Hnin Ei Ei Wai', 'eiwaih62@gmail.com', NULL, 'General/Other', 'communication', 'active', 'CV Lead Tracker', 'CV: Hnin Ei Ei Wai- Junior A (No exp) MT.pdf'),
('Noe Noe May Aung', 'noenoe50927@gmail.com', '09967169507', 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Noe Noe May Aung - JA (no exp)MT.pdf'),
('May Thet Hnin', 'maythethnin6999@gmail.com', NULL, 'Management', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: May Thet Hnin - JA (np exp) MT.pdf'),
('Mg Khant Ko Ko', 'khantkokolwin977@gmail.com', '09773237725', 'Management', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Mg Khant Ko Ko Lwin - JA (MT).pdf'),
('Shwe Yin Aung', 'shweyinaung040@gmail.com', '959428320792', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Shwe Yin Aung - JA (Thanlyin)MT.pdf'),
('Thi Ri Mon', NULL, '09456271556', 'Sales & Marketing', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Thi Ri Mon - Accountant No exp (MT).pdf'),
('Hsu Myat', NULL, '09882605578', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Hsu Myat - JA no exp (MT).pdf'),
('Wah Wah Win', 'wahwinn85@gmail.com', '09785646987', 'General/Other', 'excel, problem solving', 'active', 'CV Lead Tracker', 'CV: Wah Wah Win - JA Fresher (MT).pdf'),
('Ae Mon Kyaw', 'gguu1958@gmail.com', '09668873904', 'Customer Service', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Ae Mon Kyaw - Fresher (MT).pdf'),
('Thin Lae Lae Soe', 'mthin4035@gmail.com', '09663089525', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Thin Lae Lae Soe - JA (Fresher)MT.pdf'),
('Khaing Khaing Thwe', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Khaing Khaing Thwe - Junior A No exp (MT).pdf'),
('Khine Zin Tun', 'khinezintun25@gmail.com', '09454226442', 'Finance & Accounting', 'communication, analytical', 'active', 'CV Lead Tracker', 'CV: Khine Zin Tun - JA (no exp) MT.pdf'),
('Yuzana Htun', NULL, NULL, 'Finance & Accounting', 'excel, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Yuzana Htun - JA (No exp)MT.pdf'),
('Phoo Pyae Sone', 'maphue60@gmail.co', '09426909337', 'General/Other', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Phoo Pyae Sone - JA (fresher)MT.pdf'),
('Ma Khin Khin Kyaw', 'Khinkhinkyaw29122003@gmail.com', '09255817516', 'Engineering', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Ma Khin Khin Kyaw - Junior A (no exp) MT.pdf'),
('Aye Ndar Tun', NULL, NULL, 'Management', 'excel, powerpoint, problem solving', 'active', 'CV Lead Tracker', 'CV: Aye Sandar Tun - JA (no exp)MT.pdf'),
('May Thiri Khine', 'maythiri2712@gmail.com', '09443945496', 'Finance & Accounting', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: May Thiri Khine - JA (no exp_ MT.pdf'),
('Koh Aung', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Koh Aung - Junior Acc no exp.pdf'),
('Mg Khant Min Maw', NULL, NULL, 'Management', 'excel, powerpoint, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Mg Khant Min Maw - JA (Fresher)MT.pdf'),
('Thiri Kyaw', 'thirikyaw73333@gmail.com', '09943854304', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Thiri Kyaw - JA (no exp)MT.pdf'),
('Hsu Yi Win', 'hsuyiwin2003@gmail.com', NULL, 'General/Other', 'excel, powerpoint, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Hsu Yi Win - JA (no exp)MT.pdf'),
('Thin Nandar Zaw Exp', 'thinnandarzaw55@gmail.com', '+959420265304', 'Finance & Accounting', 'excel, analytical', 'active', 'CV Lead Tracker', 'CV: Thin Nandar Zaw (JA)no exp MT.pdf'),
('Theingi Nwe', 'nwet2112@gmail.com', '09259920317', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Theingi Nwe - Accountant No exp (MT).pdf'),
('Hla Myo Htet', 'Hlamyohtet133@gmail.com', '09785833474', 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Hla Myo Htet - Junior Accountant (MT).pdf'),
('Ei Ei Khant', 'eieikhant2000@gmail.com', '959774413235', 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Ei Ei Khant - JA (MT).pdf'),
('Eaint Nge Hmue', NULL, NULL, 'Finance & Accounting', 'communication', 'active', 'CV Lead Tracker', 'CV: Eaint Nge Hmue - Junior Accountant (MT).pdf'),
('Ei Phyu Soe', 'eiphyusoe462@gmail.com', '09740933769', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Ei Phyu Soe - JA (MT).pdf'),
('Pwint Phyu Aye', 'pwintphyuaye999@gmail.com', '09976778887', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Pwint Phyu Aye - JA (MT).pdf'),
('Ohnmar Aye', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Ohnmar Aye - Junior Accountant (MT0.pdf'),
('Zin Zin Htike', NULL, NULL, 'HR & Admin', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Zin Zin Htike - JA (No exp) MT.pdf'),
('Zu Zu Moe', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Zu Zu Moe - JA (MT).pdf'),
('Thet Kay Zin', 'thetkayzin16@gmail.com', '+959424217599', 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Thet Kay Zin - JA (MT).pdf'),
('Hay Man Zaw', 'zawhayman123@gmail.comPersonal', NULL, 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Hay Man Zaw - JA (no exp) MT.pdf'),
('Lin Lin Tun', 'linlintun.1432@gmail.com', '959955131359', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Lin Lin Tun - JA (MT).pdf'),
('Aye Myat Soe', 'ayemyatsoe3897@gmail.com', NULL, 'Management', 'excel, communication, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: Aye Myat Soe - Junior A (MT).pdf'),
('Myat Hsu Hlaing', 'Myathsuhlaing2121@gmail.com', NULL, 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Myat Hsu Hlaing - Junior A (MT).pdf'),
('Nawthwalthwaloo', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: nawthwalthwaloo.pdf'),
('Than Myat Cho Thar', 'thanmyatchothar@gmil.com', '959421857105', 'HR & Admin', 'excel, analytical', 'active', 'CV Lead Tracker', 'CV: Than Myat Cho Thar - JA (MT).pdf'),
('Khaing Khin Oo', NULL, NULL, 'Finance & Accounting', 'analytical', 'active', 'CV Lead Tracker', 'CV: Khaing Khin Oo - Junior A (MT).pdf'),
('Nanda Aung Form', 'nandaa9789@gmail.com', '09775130437', 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Nanda Aung cv form (pdf file)(1).pdf'),
('Aye Myat Myat Nyein', 'ayemyatmyatnyein77@gmail.com', '09970314945', 'Finance & Accounting', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Aye Myat Myat Nyein - JA (MT).pdf'),
('Khaing Win Win Zin', NULL, '959750269511', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Khaing Win Win Zin - Junior Accountant (MT).pdf'),
('Yin Mon Aung', 'ma123@gmail.com', '09953875295', 'Management', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Yin Mon Aung - Junior Accountant (MT).pdf'),
('Shwe Phyu Win', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Shwe Phyu Win -Junior A (MT).pdf'),
('Zarli Nwe Oo', 'nawzarlinweoo@gmail.com', '09256675823', 'Finance & Accounting', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Zarli Nwe Oo - JA (MT).pdf'),
('Khine Thinzar Aung', 'khaingthinzaraung2391@gmail.com', '09797977711', 'Engineering', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Khine Thinzar Aung - Junior A (MT).pdf'),
('Amy Tun', NULL, '09785291995', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: AMY_TUN - JA (MT).pdf'),
('Nan Htike Wai', 'nannanhtike1234@gmail.com', NULL, 'Engineering', 'sql, excel', 'active', 'CV Lead Tracker', 'CV: Nan Htike Wai - Junior Accountant (MT).pdf'),
('Curriclum Vitae', 'hninmohmohnwe777@gmail.com', '09958707476', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Hnin - JA (MT).pdf'),
('Kyawt Kyawt Myint', 'kyawtkyawtmyint0@gmail.com', '09780927271', 'Finance & Accounting', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Kyawt Kyawt Myint - Junior A(MT).pdf'),
('Khine Zar Thwe', 'khine2002613@gmail.com', NULL, 'HR & Admin', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: khine zar Thwe - JA (MT).pdf'),
('Thuzar Aung', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Thuzar Aung - Assistant A (MT).pdf'),
('Pann Phyu', 'pannphyu969825@gmail.com', '09968468912', 'Finance & Accounting', 'excel, powerpoint, photoshop', 'active', 'CV Lead Tracker', 'CV: Pann Phyu-Junior A (MT).pdf'),
('Pyae Hein Kyaw', 'pyaeheinkyaw82@gmail.com', '9428260224', 'Sales & Marketing', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Pyae Hein Kyaw - JA (MT).pdf'),
('Thin Yu Swe', 'thinyuswe891@gmail.com', '09651699900', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Thin Yu Swe - JA (MT).pdf'),
('Zue Zue Zan', 'zuezuezan191198zzz@gmail.com', '959786151277', 'Engineering', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Zue Zue Zan - Junior Accountant (MT).pdf'),
('Ei Thin Zar Lin', 'minthinzar2819@gmail.com', '09740804447', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Ei Thin Zar Lin - Junior Accountant (MT).pdf'),
('Ei Phyu Zin', 'eiphyzin123mkn@gmail.com', NULL, 'Management', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Ei Phyu Zin - Junior Accountant (MT).pdf'),
('Thetmyintmosoe J A', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: ThetMyintMoSoe - J A (MT).pdf'),
('Phyo Thazin', 'mimi.mmtz19@gmail.com', '09680339676', 'HR & Admin', 'communication', 'active', 'CV Lead Tracker', 'CV: Phyo Thazin - Junior A (MT).pdf'),
('Thinzar Nyein', 'thinzarnyein123@gmail.com', '09260978533', 'General/Other', 'excel', 'active', 'CV Lead Tracker', 'CV: Thinzar Nyein - Junior Account (MT).pdf'),
('Ei Ei', 'deedee.secondery@gmail.com', '09250003419', 'Engineering', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Ei Ei - Internal Auditor (MT).pdf'),
('Hnin Hnin', 'hninhninpku@gmail.com', NULL, 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Hnin Hnin - JA (MT).pdf'),
('Phyo Pa Pa Aung', 'phyopapaaung363@gmail.com', NULL, 'Education', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Phyo Pa Pa Aung - Junior Accountant (MT).pdf'),
('Thinn Nandar Soe', 'heefei7@gmail.com', '09444655262', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Thinn Nandar Soe - Junior A (MT).pdf'),
('Yuwar Khine', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Yuwar Khine - Junior A (MT).pdf'),
('Aye Nyein Kyar Phyu', NULL, NULL, 'Finance & Accounting', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Resume-Aye-Nyein-Kyar-Phyu.pdf'),
('Mar Mar Soe', 'marmarsoe2k17@gmail.com', NULL, 'Sales & Marketing', 'problem solving', 'active', 'CV Lead Tracker', 'CV: Mar Mar Soe - Junior A (MT).pdf'),
('Ingyin Thant', 'ingyinthant886@gmail.com', '09755228554', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Ingyin Thant - Junior A (MT).pdf'),
('Hnin Yoon Pann Eain', 'hninyoonpanneain1217@gmail.com', '09422996594', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Hnin Yoon Pann Eain - Assistant Accountant (MT).pdf'),
('Nway Yu Mon Aung', 'nwayyumonaung21@gmail.com', '09422538585', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Nway Yu Mon Aung - JA (MT).pdf'),
('Thin Nandar Soe', 'heefei7@gmail.com', '09444655262', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Thin Nandar Soe - Junior A (MT).pdf'),
('Thandar Swe', 'thandarswe.ts1794@gmail.com', '09771754190', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Thandar Swe - JA (MT).pdf'),
('Thazin Htet', NULL, '09759011496', 'Engineering', 'sql, excel', 'active', 'CV Lead Tracker', 'CV: Thazin Htet - Junior Accountant (MT).pdf'),
('Naw May Thin Khine', 'nawmaythinkhing@gmail.com', '09442580194', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Naw May Thin Khine - JA (no exp) MT.pdf'),
('Pan Ei Phyu', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Pan Ei Phyu - JA (MT).pdf'),
('Hsu Mon Aung', 'sumon.me2019@gmail.com', '09775636502', 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Hsu Mon Aung - Junior Accountant (MT).pdf'),
('Su Wai Yan', 'hsuwaiyan22@gmail.com', '09798198414', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Su Wai Yan - JA (MT).pdf'),
('Aye Nyein Han', 'einhan97@gmai.com', '9424450482', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Aye Nyein Han - JA (MT).pdf'),
('May Thandar Moe', 'maythandarmoe.04@gmail.com', '09756423675', 'Finance & Accounting', 'excel, powerpoint, communication, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: May Thandar Moe - JA (MT).pdf'),
('May Thandar Moe', 'maythandarmoe.04@gmail.com', '09756423675', 'Finance & Accounting', 'excel, powerpoint, communication, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: May Thandar Moe - JA (NOK)MT.pdf'),
('Khine Thinzar Lwin', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Khine Thinzar Lwin - JA (MT).pdf'),
('Thin Yanat', 'thinyanant152024@gmail.com', '09982981135', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Thin Yanat - Assistant Accountant (MT).pdf'),
('Nan Ei Wai Lwin', 'nanneiwailwin656@gmail.com', '+959988805666', 'Management', 'excel, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Nan Ei Wai Lwin-JA (MT).pdf'),
('Ei Thu Kyaw', 'poemloverkim200021@gmail.com', '09780364639', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Ei_Thu_Kyaw - JA (MT).pdf'),
('N Htar Yadanar', 'sanhtaryadanar@gmail.com', '09453441281', 'General/Other', 'communication', 'active', 'CV Lead Tracker', 'CV: San Htar Yadanar - Junior Accountant (MT).pdf'),
('Khin Zar Wai Phyo', 'khinzarwaijucy@gmail.com', '09955784067', 'Engineering', 'sql, excel, communication', 'active', 'CV Lead Tracker', 'CV: Khin Zar Wai Phyo -JA (MT).pdf'),
('Thinzar Theint', 'thinzartheint98@gmail.com', NULL, 'HR & Admin', 'communication', 'active', 'CV Lead Tracker', 'CV: Thinzar Theint - JA (MT).pdf'),
('Shwe Zin Oo', NULL, '09797741329', 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Shwe Zin Oo -JA (MT) (2).pdf'),
('Hsu Myat Myat Than', 'hsumyatmyatthan12@gmail.com', '09777152439', 'Sales & Marketing', 'git, excel, communication', 'active', 'CV Lead Tracker', 'CV: Hsu Myat Myat Than - JA (MT).pdf'),
('Shwe Sin', 'shwesin1212025@gmail.com', NULL, 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Shwe Sin - JA (MT).pdf'),
('Soe Yadanar', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Soe Yadanar - Junior Accountant (MT).pdf'),
('Yut Mar Yar', 'yutmaryar@gmail.com', NULL, 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Yut Mar Yar -Junior  Accountant (MT).pdf'),
('Ngwe Zin Thaw', 'ngwesinthaw264@gmail.com', '09404165952', 'Management', 'excel, leadership, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Ngwe Zin Thaw - JA (MT).pdf'),
('Ei Mon Swe', 'eilay0263@gmail.com', '959740964611', 'Finance & Accounting', 'sql, excel, communication, project management', 'active', 'CV Lead Tracker', 'CV: Ei Mon Swe - JA (MT).pdf'),
('Khaint Zin Thant', NULL, '09428132277', 'Engineering', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Khaint Zin Thant  - Junior Accountant (MT).pdf'),
('Aye Chan Thu', 'Ayechanthu286@gmail.com', '09446160792', 'Finance & Accounting', 'express, excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Aye Chan Thu - JA (MT).pdf'),
('Aye Htet Khaing', NULL, '09775423961', 'Finance & Accounting', 'excel, analytical', 'active', 'CV Lead Tracker', 'CV: Aye Htet Khaing - JA (MT).pdf'),
('Honey Oo', 'honey57118@gmail.com', NULL, 'Management', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Honey Oo - Junior Accountant (MT).pdf'),
('Eain Dray La Pyae', 'carolinealex1324@gmail.com', '09976543517', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Eain Dray La Pyae - Junior A (MT).pdf'),
('Nant May Kyi Oo', NULL, '09764704898', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Nant May Kyi Oo _ JA (MT).pdf'),
('Than Htay', NULL, '09425045018', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Than Htay - JA (MT).pdf'),
('Pann Ei Phyu', 'pannphyukhaing03@gmail.comEmail', NULL, 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Pann Ei Phyu - JA (MT_.pdf'),
('Lae Shwe Zin Phone', 'shwesatkyarr@gmail.comComputer', '0920102007', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Lae Shwe Zin Phone - JA (MT).pdf'),
('Naing Oo Lwin', 'naingoolwin361@gmail.com', '09988345435', 'General/Other', 'excel, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Naing Oo Lwin - JA (MT).pdf'),
('Thae Su Htwe', 'thaesuhtwe070@gmail.com', NULL, 'Engineering', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: THAE SU HTWE - JA (MT).pdf'),
('Aeindani Kyaw Kyaw', 'aeindanikyaw@gmail.com', '09790598861', 'Finance & Accounting', 'excel, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Aeindani Kyaw Kyaw - JA (MT).pdf'),
('Khaing Khaing Mar', NULL, '09783410097', 'Engineering', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Khaing Khaing Mar - JA (MT).pdf'),
('May Zin Oo', 'mayzinoo.ccta@gmail.com', '09688571354', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: May Zin Oo - JA (MT).pdf'),
('Min Khin Khin', NULL, NULL, 'Management', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Min Khin Khin - JA (MT).pdf'),
('No No Ko', 'Townshipnonoko2061998@gmail.com', '09972610729', 'Finance & Accounting', 'communication', 'active', 'CV Lead Tracker', 'CV: No No Ko- JA (MT).pdf'),
('Phue Mo Zin Khaing', 'phuemozinkhaing6700@gmail.com', '09971479345', 'Management', 'sql, excel', 'active', 'CV Lead Tracker', 'CV: Phue Mo Zin Khaing - JA (MT).pdf'),
('N Yu May', 'kangmary208@gmail.com', '09773705239', 'Finance & Accounting', 'sql, excel', 'active', 'CV Lead Tracker', 'CV: San Yu May-JA (MT).pdf'),
('Lwin Lwin Chaw', NULL, '959425015279', 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Lwin Lwin Chaw - JA (MT).pdf'),
('Linn Thawtar', 'linnthawtar67@gmail.com', '09796790935', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Linn Thawtar - JA (MT).pdf'),
('Ei Shwe Zin', 'eishwesin298783@gmail.com', '09752929455', 'Sales & Marketing', 'git, excel, communication', 'active', 'CV Lead Tracker', 'CV: Ei Shwe Zin - JA (MT).pdf'),
('Myo Khai Khai Zaw', 'myorio214@gmail.com', '09771446770', 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Myo Khai Khai Zaw - JA (MT).pdf'),
('Zaw Myo Tun', NULL, NULL, 'Engineering', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Zaw Myo Tun - Junior Accountant (MT).pdf'),
('Zin May Kyaw Myo', 'zinmaykyawmyo@gmail.com', NULL, 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Zin May Kyaw Myo - Junior Accountant (MT).pdf'),
('Wai Wai Oo', 'waioo.ymt@gmail.com', '09759320302', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Wai Wai Oo - JA (MT).pdf'),
('Khine Khine Win', NULL, '09984669259', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Khine Khine Win - JA (MT).pdf'),
('Aye Thazin Oo', NULL, NULL, 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Aye Thazin Oo - JA (MT).pdf'),
('May Myat Mon', NULL, NULL, 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: May Myat Mon - Junior Accountant (MT).pdf'),
('Aye Thidar Htet', 'ayethidarhtetath007@gmail.com', NULL, 'Management', 'excel, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Aye Thidar Htet - JA (MT).pdf'),
('Phyo Phyo Myint Swe', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Phyo Phyo Myint Swe - JA (MT).pdf'),
('Kathy Oo', 'kathyoo249@gmail.com', '09755771501', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Kathy Oo - JA (MT).pdf'),
('Thandar Lwin', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Thandar Lwin - JA (Hotel)MT (1).pdf'),
('May Thiri Nwe', 'maythirinwe85@gmail.com', '09260222001', 'Management', 'excel, analytical', 'active', 'CV Lead Tracker', 'CV: May Thiri Nwe - JA (Hotel)MT.pdf'),
('Zin Nwe Htun', 'ygnzinnwetun67@gmail.co', NULL, 'Finance & Accounting', 'sql, excel, powerpoint, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Zin Nwe Htun - Junior Accountant (Thanlyin)MT.pdf'),
('Ma Than Htay', NULL, '09425045018', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Ma Than Htay (JA ) MT.pdf'),
('Moe Ndar', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Moe Sandar - JA (MT).pdf'),
('Thet Hmue Khin', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Thet Hmue Khin - JA (Dagon Seik)MT.pdf'),
('Phyu Pyar Win', 'phyupyarwin2024hot@gmail.com', '09950279631', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Phyu Pyar Win - JA (MT).pdf'),
('May Thu Htun', 'y72054@gmail.com', '09980616446', 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: May Thu Htun - Junior Accountant (MT).pdf'),
('Naw Thae Mon N', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Naw Thae Mon San - JA (MT).pdf'),
('Khin Thida Nyein', 'khinthidanyein2001@gmail.com', '09966429926', 'Management', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Khin Thida Nyein - JA (North Dagon)MT.pdf'),
('Thazin Su Su N', 'thazinsususan@gmail.com', '09448455858', 'Management', 'git, excel, powerpoint, problem solving', 'active', 'CV Lead Tracker', 'CV: Thazin Su Su San - JA (MT).pdf'),
('Khin Thet Thet Aung', 'khinthetthetktta@gmail.com', '959788405168', 'Finance & Accounting', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Khin Thet Thet Aung - JA (Hlaing)MT (1).pdf'),
('Ngon Hlaing Thae', 'ngonhlaingthae13@gmail.com', '959252724613', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Ngon Hlaing Thae - JA (MT).pdf'),
('Thun Yupar Hlaing', 'hlaingthunyupar@gmail.comAddress', '09429924462', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Thun Yupar Hlaing - JA (MT).pdf'),
('Linkar Hnin Wai', 'linkarhninwai@gmail.co', '09883959267', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Linkar Hnin Wai - JA (MT).pdf'),
('Win Ndar Htun', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Win Sandar Htun - JA (MT) (2).pdf'),
('Phyu Sin Thaw', 'mathor5544@gmail.com', '09785969698', 'Engineering', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Phyu Sin Thaw - Junior Accountant (MT).pdf'),
('Yu War Khine', NULL, '09980476250', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Yu War Khine - JA (MT).pdf'),
('N Nu Htwe', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: San Nu Htwe - JA (MT).pdf'),
('Thi Thi Aung', 'thithiaung0002@gmail.com', '09973238340', 'HR & Admin', 'communication', 'active', 'CV Lead Tracker', 'CV: Thi Thi Aung - Junior A (MT).pdf'),
('Mi Mi Khaing', NULL, '09978393357', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Mi Mi Khaing - JA (MT).pdf'),
('Hla Myo Htet', 'Hlamyohtet133@gmail.com', '09785833474', 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Hla Myo Htet - Junior Accountant (MT).pdf'),
('Eaint Nge Hmue', NULL, NULL, 'Finance & Accounting', 'communication', 'active', 'CV Lead Tracker', 'CV: Eaint Nge Hmue - Junior Accountant (MT).pdf'),
('Ohnmar Aye', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Ohnmar Aye - Junior Accountant (MT0.pdf'),
('Kaung Kin Pyar', 'kaungkinpyarmf@gmail.com', '09963856344', 'Engineering', 'sql, excel', 'active', 'CV Lead Tracker', 'CV: Kaung Kin Pyar - JA (MT).pdf'),
('Aye Myat Soe', 'ayemyatsoe3897@gmail.com', NULL, 'Management', 'excel, communication, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: Aye Myat Soe - Junior A (MT).pdf'),
('Khaing Khin Oo', NULL, NULL, 'Finance & Accounting', 'analytical', 'active', 'CV Lead Tracker', 'CV: Khaing Khin Oo - Junior A (MT).pdf'),
('Khaing Win Win Zin', NULL, '959750269511', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Khaing Win Win Zin - Junior Accountant (MT).pdf'),
('Yin Mon Aung', 'ma123@gmail.com', '09953875295', 'Management', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Yin Mon Aung - Junior Accountant (MT).pdf'),
('Shwe Phyu Win', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Shwe Phyu Win -Junior A (MT).pdf'),
('Nan Htike Wai', 'nannanhtike1234@gmail.com', NULL, 'Engineering', 'sql, excel', 'active', 'CV Lead Tracker', 'CV: Nan Htike Wai - Junior Accountant (MT).pdf'),
('Thuzar Aung', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Thuzar Aung - Assistant A (MT).pdf'),
('Myat Thazin', 'mayzin204007@gmail.com', '09792148003', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Myat Thazin - JA (MT).pdf'),
('Thinzar Nyein', 'thinzarnyein123@gmail.com', '09260978533', 'General/Other', 'excel', 'active', 'CV Lead Tracker', 'CV: Thinzar Nyein - Junior Account (MT).pdf'),
('Phyo Pa Pa Aung', 'phyopapaaung363@gmail.com', NULL, 'Education', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Phyo Pa Pa Aung - Junior Accountant (MT).pdf'),
('Yuwar Khine', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Yuwar Khine - Junior A (MT).pdf'),
('Mar Mar Soe', 'marmarsoe2k17@gmail.com', NULL, 'Sales & Marketing', 'problem solving', 'active', 'CV Lead Tracker', 'CV: Mar Mar Soe - Junior A (MT).pdf'),
('Ingyin Thant', 'ingyinthant886@gmail.com', '09755228554', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Ingyin Thant - Junior A (MT).pdf'),
('Hnin Yoon Pann Eain', 'hninyoonpanneain1217@gmail.com', '09422996594', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Hnin Yoon Pann Eain - Assistant Accountant (MT).pdf'),
('Hsu Mon Aung', 'sumon.me2019@gmail.com', '09775636502', 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Hsu Mon Aung - Junior Accountant (MT).pdf'),
('Aye Aye Nwe', NULL, '09266319792', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Aye Aye Nwe - JA (MT).pdf'),
('Wit Yee Aye', 'wityeeaye23@gmail.com', '09984220494', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Wit Yee Aye - JA (MT).pdf'),
('Personal Information :', 'soemoethu1016@gmail.com', '09771984052', 'Engineering', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Ju acc.pdf'),
('Thin Mary Tun', 'thinmarytun2001@gmail.comContact', '09777081641', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Thin Mary Tun - JA (MT) (1).pdf'),
('Junior Accountant', 'nin@gmail.com', '0961803639', 'Finance & Accounting', 'excel, powerpoint, analytical', 'active', 'CV Lead Tracker', 'CV: Mya - JA (MT).pdf'),
('Thiri Moe Oo', NULL, '09799807611', 'Management', 'excel, powerpoint, leadership', 'active', 'CV Lead Tracker', 'CV: thiri moe oo  - JA (MT).pdf'),
('Thin Thin Hlaing', 'thin84650@gmail.com', NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Thin Thin Hlaing - JA (Hmwabi)MT.pdf'),
('Win Thiri', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Win Thiri - JA (MT).pdf'),
('Zon Nadi Lwin', 'zonnadilwin@gmail.com', NULL, 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Zon Nadi Lwin - JA (MT).pdf'),
('Khaing Thin Kyi Resume', 'eieinyeinsmg1@gmail.com', '09407514499', 'Engineering', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: KTK - JA (MT).pdf'),
('Aye Aye Khaing', 'maayekhaing627@gmail.com', '09981263866', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Aye Aye Khaing - JA (MT).pdf'),
('Myo Thinzar Khine', 'mthinzar364@gmail.com', '09767368420', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Myo Thinzar Khine - JA (MT).pdf'),
('Ma Shun Wa Di', 'kimutosan@gmail.com', NULL, 'Engineering', 'excel, project management', 'active', 'CV Lead Tracker', 'CV: Ma Shun Wa Di Swe - JA (MT).pdf'),
('Wai Wai Phyo', 'o779@gmail.com', '09454719172', 'Management', 'sql', 'active', 'CV Lead Tracker', 'CV: Wai Wai Phyo - JA (MT).pdf'),
('Ma Ei Ei Phyu', 'lay1296@gmail.com', '09784584899', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Ma Ei Ei Phyu - JA (mayagone)MT.pdf'),
('Poe Hayman Aung', 'EXPERIENCEpoehaymanaung1999@gmail.com', '+959756068682', 'HR & Admin', 'communication', 'active', 'CV Lead Tracker', 'CV: Poe Hayman Aung - JA (MT).pdf'),
('Aye Mon Aung', 'amonaung26@gmail.com', '09259791054', 'Finance & Accounting', 'problem solving', 'active', 'CV Lead Tracker', 'CV: Aye Mon Aung - JA (SPT) MT.pdf'),
('Pan Ei N', NULL, '09674087882', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Pan Ei San - Junior Accountant (MT).pdf'),
('Hsu Thin Moe', 'nimoe296@gmail.com', '09950563734', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: HTM - JA (MT).pdf'),
('Yan Aung Soe', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Yan Aung Soe - JA (MT).pdf'),
('May Thazin Aung', 'mayzinaung227tt@gmail.com', NULL, 'HR & Admin', 'excel, powerpoint, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: May ThaZin Aung - JA (Htaung Kyant)MT.pdf'),
('Su Hlaing Kyaw', 'suhlaingkyaw28@gmail.com', '959772506352', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Su Hlaing Kyaw - JA (MT).pdf'),
('Ma Hsie Hr Oo', 'sanmie058@gmail.com', '09761717247', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Ma Hsie Hsar Oo - JA (MT).pdf'),
('Yamin Eaindray', 'eaindrayy415@gmail.com', '09951282054', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Yamin Eaindray - JA (MT) (2).pdf'),
('La Min', 'laminwai188@gmail.com', '09777112411', 'Management', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: La Min - JA (No exp)MT.pdf'),
('Su Thiri Kyaw', 'suthirikyaw2000@gmail.com', '09980911723', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Su Thiri Kyaw- JA (MT).pdf'),
('Zin Lin Myat', NULL, '09795415257', 'Finance & Accounting', 'powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Zin Lin Myat - JA (MT).pdf'),
('Thae Su Win', 'sthae0391@gmail.com', '09953251422', 'General/Other', 'excel', 'active', 'CV Lead Tracker', 'CV: Thae Su Win - JA (Tharketa) MT.pdf'),
('Aye Myint Myat Myo', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Aye Myint Myat Myo - JA  (MT).pdf'),
('Than Dar Soe', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Than Dar Soe - JA (MT).pdf'),
('Aye Nyein Han', 'einhan97@gmai.com', '9424450482', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Aye Nyein Han - JA (Rest)MT.pdf'),
('Myat Hsu Hlaing', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Myat Hsu Hlaing JA(MT).pdf'),
('Thuzar Win Pyae', 'thuzarwinpyae1992@gmail.com', '09972022795', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Thuzar Win Pyae - Acc (MT).pdf'),
('Eaint Min Khant', 'eaintminkhant3@gmail.com', '09260003760', 'Finance & Accounting', 'excel, powerpoint, problem solving', 'active', 'CV Lead Tracker', 'CV: Eaint Min Khant - Accountant (MT).pdf'),
('Khaing Moh Moh Ko', 'khaingmohmohko2696@gmail.com', '09795867376', 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Khaing Moh Moh Ko - Accountant (MT).pdf'),
('Khine Zin Latt', 'khinglaylatt94@gmail.com', '959250072826', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Khine Zin Latt - Accountant (MT).pdf'),
('Eaindray Thet Win', 'eain270919@gmail.com', '959798445276', 'Engineering', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Eaindray Thet Win - Accountant (MT).pdf'),
('Aye Zin Mar', NULL, '09756802005', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Aye Zin Mar - Accountant (MT).pdf'),
('Khin Zar Chi Thein', 'khinzarchithein2310@gmail.com', '+959455525388', 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Khin Zar Chi Thein - Accountant (MT).pdf'),
('May Thazin Tun', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: May Thazin Tun - Accountant (MT).pdf'),
('Tin Aung', 'naeim12acc@gmail.com', '959780279391', 'Sales & Marketing', 'excel, photoshop', 'active', 'CV Lead Tracker', 'CV: TinAung - Accountant (MT).pdf'),
('Nweni Aye', 'nweniaye8315@gmail.com', '09983173914', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Nweni Aye - Accountant (MT).pdf'),
('Chaw Thant Kyi', 'chawthant123@gmail.com', NULL, 'Engineering', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Chaw Thant Kyi - Accountant (MT).pdf'),
('Ms Khin May Win', 'khinmaywin2018@gmail.com', '09258835607', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Ms Khin May Win - Accountant(MT).pdf'),
('Khin Moh Moh Kyaw', 'Khinmohmohkyawk3@gmail.com', NULL, 'Engineering', 'sql, aws, excel, analytical', 'active', 'CV Lead Tracker', 'CV: Khin Moh Moh Kyaw - Accountant (MT).pdf'),
('Chit Su Khaing', NULL, '09420120483', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Chit Su Khaing - Accountant (MT).pdf'),
('Kay Thwe Moe', 'irisphyo77@gmail.com', '0943016316', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Kay Thwe Moe - Accountant (MT).pdf'),
('Tin Yadanar Aung', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Tin Yadanar Aung - Accountant (MT).pdf'),
('Aye Aye Nyein', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Aye Aye Nyein - Inventory Accountant (MT).pdf'),
('Tin Tin Win', 'tintinwinmaungmaung@gmail.com', '09421106082', 'Management', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Tin Tin Win - Accountant (MT).pdf'),
('Zin Mar Khaing', 'y50519@gmail.com', '09788214817', 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Zin Mar Khaing - Accountant (MT).pdf'),
('Htwe Htwe Hlaing', NULL, '09961759006', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Htwe Htwe Hlaing - Accountant (MT).pdf'),
('Zay Lin Htet', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Zay Lin Htet - Accountant (MT).pdf'),
('Persional Deetails', 'theintnwe75@gmail.com', NULL, 'General/Other', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Thin Thin Nwe CV Form -Position For Accountant.pdf'),
('Wai Wai Lwin', 'lwai94048@gmail.co', '09986021566', 'Engineering', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Wai Wai Lwin - Accountant (MT).pdf'),
('Zun Thiri Lin Ap', 'thirilynn91@gmail.com', NULL, 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Zun Thiri Lin - AP (MT).pdf'),
('Phway Phway Myint Wai', 'phwayphwaywinmyint2023@gmail.comPhoneNumber', NULL, 'Engineering', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Phway Phway Myint Wai - Accountant (MT).pdf'),
('Aye Thu Aung', 'athu.j799@gmail.com', '959740978719', 'Finance & Accounting', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Aye Thu Aung - Accountant (MT).pdf'),
('Ei Ei Chan Myae', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Ei Ei Chan Myae - Accountant (MT).pdf'),
('Ms. Khin Thandar Kyaw', 'kt430074@gmail.com', '09676123360', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: KTDK CV -Accountant (NOK) MT.pdf'),
('Khin Moh Moh Kyaw', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Khin Moh Moh Kyaw 1 - Accountant (MT).pdf'),
('Khing Thi Thi', 'lwizar204@gmail.com', '959977606505', 'Management', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Khing Thi Thi - Accountant (MT).pdf'),
('Khaing Zin Thant', NULL, '09757882636', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Khaing Zin Thant - Accountant (MT).pdf'),
('War War Oo', 'Yangon.warwaroo1403@gmail.com', '09401544986', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: War War Oo- Accountant (MT).pdf'),
('Yamin Pwint', 'yaminpwint112@gamil.comCERTIFICATES', '09799526723', 'Finance & Accounting', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Yamin Pwint - Accountant (MT).pdf'),
('Ei Thandar', NULL, '09775328729', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Ei Thandar - Accountant (MT0.pdf'),
('In Jinn Phyu', 'injinnphyu1997@gmail.com', NULL, 'Finance & Accounting', 'excel, project management', 'active', 'CV Lead Tracker', 'CV: In Jinn Phyu - Accountant (MT).pdf'),
('Thi Thi N', 'thithis084@gmail.com', '959943280084', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Thi Thi San - Accountant VIP (MT).pdf'),
('Ei Ei Khaing', 'eichaw3201994@gmail.com', '09975380166', 'Management', 'excel, powerpoint, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Ei Ei Khaing - Accountant (MT).pdf'),
('Aye Aye Nyein', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Aye Aye Nyein - Accountant (MT).pdf'),
('Htay Htay Kywal', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Htay Htay Kywal - Accountant (MT).pdf'),
('Hnin Yu Wai', NULL, '09796325420', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Hnin Yu Wai - Accountant (MT).pdf'),
('Akari Kyaw', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Akari Kyaw - Accoutant (MT).pdf'),
('Thu Zar Mon', NULL, '09981523320', 'Sales & Marketing', 'communication', 'active', 'CV Lead Tracker', 'CV: Thu Zar Mon - Accountant (MT).pdf'),
('Theingi Soe N', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Theingi Soe San - Accountant (MT).pdf'),
('Curriculum Vitae', 'nyeinsusunyein94@gmail.com', '09750811813', 'Finance & Accounting', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Nyein - Accountant (MT).pdf'),
('Kay Thwe Thwe Tun', 'kaythwethwetun61@gmail.com', NULL, 'Management', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Kay Thwe Thwe Tun - Accountant (MT).pdf'),
('Zar Li Naing', 'zarlinaing333@gmail.comP', '09751113040', 'Customer Service', 'sql, excel, powerpoint, communication, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: Zar Li Naing - Accountant (Latha)MT.pdf'),
('May Ndar Aung', '2000maysandar@gmail.com', '09770245427', 'Management', 'aws, excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: May Sandar Aung - Accountant (Thanlyin).pdf'),
('Pwint Thitr Lin', 'pwintthitsarlin01@gmail.com', '09963668417', 'Engineering', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Pwint Thitsar Lin - Accountant (MT).pdf'),
('Htet Thiri Wai', 'htet14thiri96@gmail.com', '09420284460', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Htet Thiri Wai - Accountant (MT).pdf'),
('Khin Myat Noe', 'khinmyatnoe7770@gmail.com', '09776085902', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Khin Myat Noe - Accountant (MT_.pdf'),
('Moht Moht Lwin', 'mohtmohtlwin23@gmail.com', '95263673364', 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Moht Moht Lwin - Accountant (MT).pdf'),
('Thet Su N', 'floraluvheather@gmail.com', '09777339484', 'Customer Service', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Thet Su San - Accountant (Res)MT.pdf'),
('Myo Myo Thwe', NULL, '09973326881', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Myo Myo Thwe - Accountant (MT).pdf'),
('Khin Yadanar Thein', 'yadanar14.10.91@gmail.com', '09982662457', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Khin Yadanar Thein - Accountant (Res)MT.pdf'),
('Phone Myat Aung', 'phonemyataung15502@gmail.com', '9256275868', 'Management', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Phone Myat Aung - Accountant (Construction)MT.pdf'),
('Thandar Aung', 'thandaraung8309873@gmail.com', '09960670044', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Thandar Aung - Accountant (MT).pdf'),
('Mayble Shwe', 'maybleshwe@gmail.com', '09765440216', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Mayble Shwe - Accountant (MT).pdf'),
('Su Mon Kyaw', 'sumonkyaw522@gmail.comSU', '09780272533', 'Management', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Su Mon Kyaw - Accountant (MT).pdf'),
('K Zin Kyaw', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: K Zin Kyaw - Accountant (MT) (1).pdf'),
('Yati Pwint Oo', 'yatipwintoo199200@gmail.com', '09945007555', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Yati Pwint Oo -  Accountant (Hotel)MT.pdf'),
('Ndar Myo', 'myomyo126996@gmail.com', '09787977741', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Sandar Myo - Accountant (MT) (1).pdf'),
('Zwel Htet Myo', NULL, '09940623902', 'Finance & Accounting', 'express, git, excel', 'active', 'CV Lead Tracker', 'CV: Zwel Htet Myo - Accountant (MT).pdf'),
('May Thin Kyi', 'maythinkyiriya@gmail.com', NULL, 'Operations', 'excel', 'active', 'CV Lead Tracker', 'CV: May Thin Kyi  - Accountant (MT).pdf'),
('Thi Da Htwe', 'thidarhtwe714@gmail.com', '09974250430', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Thi Da Htwe - Accountant (MT).pdf'),
('Name -ma Thuzar Aung', NULL, '09950708824', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Thu Zar Aung - Bank Advisor (Bago)MT.pdf'),
('Yadanar Htun Les', 'adanarh180@gmail.com', '09454219452', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Yadanar Htun  Sales (MT).pdf'),
('Theint Shwe Sin', NULL, '09797231585', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Theint Shwe Sin - Sales (Bago)MT.pdf'),
('Khaing Thazin Phoo Bank', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Khaing Thazin Phoo - Bank Advisor (Bago)MT.pdf'),
('Thae Hsu Thitr', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Thae Hsu Thitsar - Sales - Bago (MT).pdf'),
('Race - Myanmar', NULL, '09697984503', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Thet Su Wai - Bank Adviosr (Bago)MT.pdf'),
('Race - Myanma R', NULL, '09779861007', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Zaw Myint Myat - Bank Advisor (Bago)MT.pdf'),
('Race - Myanma R', NULL, '09785656889', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Pyae Pyae Phyo Zin - Bank Advisor (Bago)MT.pdf'),
('Hsu Nandar Aung Bank', NULL, NULL, 'Education', NULL, 'active', 'CV Lead Tracker', 'CV: Hsu Nandar Aung - Bank Advisor (Bago)MT (1).pdf'),
('Lin Htike Htike Than', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Lin Htike Htike Than - Bank Advisor (Bago)MT.pdf'),
('Race - Myanma R', NULL, '09750389922', 'Management', 'express', 'active', 'CV Lead Tracker', 'CV: Saw Pyae Phyoe Htun - Bank Advisor (Bago)MT.pdf'),
('Race - Myanmar', NULL, '09665581456', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Hnin Wai Wai Lwin - Bank Advisor (Bago)MT.pdf'),
('Race - Myanmar', NULL, '0996287674', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Nyan Lin Aung - Bank Advisor (Bago)MT.pdf'),
('Bank Advisor (bago)', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Thin Thin Thu - Bank Adviosr (Bago)MT.pdf'),
('Race - Myanma R', NULL, '09989146916', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Lwin Ko Aung - Bank Advisor (Bago)MT.pdf'),
('Kyaw Soe Han', 'kyawsoehan149@gmail.com', '09955797973', 'Management', 'aws, git, excel, communication, project management, analytical', 'active', 'CV Lead Tracker', 'CV: Kyaw Soe Han - Account Executive (MT).pdf'),
('Naylinnhtetnaing Bd', NULL, '0943127663', 'Management', 'git, excel, leadership', 'active', 'CV Lead Tracker', 'CV: NayLinnHtetNaing-BD Manager (MT).pdf'),
('Kyawtsusushin Business D', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: KyawtSuSuShin - Business D M(MT).pdf'),
('Mo Zin Phoo Bd', 'nann304899@gmail.com', '09977385337', 'Management', 'git, excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Mo Zin Phoo - BD Manager (MT).pdf'),
('Sai Thant Zin Naing', 'nnaing1990@gmail.com', '09972168486', 'Management', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Sai Thant Zin Naing - BD Manager (MT).pdf'),
('Htakehtar Bd', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: HtakeHtar - BD Manager (MT).pdf'),
('Kyi May Aung Bd', 'Kyimayaung291166@gmail.com', '09964815824', 'Management', 'excel, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Kyi May Aung - BD Manager (MT).pdf'),
('Htet Paing Soe Bd', 'paingpaingsbg1@gmail.com', '09777000119', 'Management', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Htet Paing Soe - BD Manager (MT).pdf'),
('Shun Lei Lei Ndi', NULL, NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Shun Lei Lei Sandi - Auto CAD Engineer (MT).pdf'),
('South Okkalapa Township, Yangon', 'suwaihnin3@gmail.com', '959979108041', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Su Wai Hnin - Auto CAD Engineer (MT).pdf'),
('About Me', 'hninnulwin.rc@gmail.com', '959428315098', 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Hnin Nu Lwin -Auto CAD Engineer (MT).pdf'),
('Ye Zaw Htet', 'yezawhtetcivil@gmail.com', '959751724005', 'Engineering', 'excel, powerpoint, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Ye Zaw Htet - Auto CAD Engineer (MT).pdf'),
('Bachelor Of Science (physics)', 'mawwaiyanlinn@gmail.com', NULL, 'Engineering', 'excel, powerpoint, photoshop, communication', 'active', 'CV Lead Tracker', 'CV: Wai Yan Linn Maw - Auto CAD Engineer (MT).pdf'),
('Shyun Lei Leisandi', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Shun Lei Lei Sandi - Auto CAD Engineer (Portfolio).pdf'),
('Okkar Head Of Marketing', 'okkar.mk@gmail.com', NULL, 'Management', 'git, leadership', 'active', 'CV Lead Tracker', 'CV: Okkar - Head of Marketing (MT).docx'),
('Aung Nyein Chan Operation', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Aung_Nyein_Chan_- Operation Manager (MT).docx'),
('Personal Information', 'maypyae2487@gmail.com', NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: May Pyae Sone Han - HR Executive (MT).docx'),
('Hein Htet Aung Hr', NULL, '09951195434', 'General/Other', 'excel', 'active', 'CV Lead Tracker', 'CV: Hein Htet Aung - HR Intern (MT).docx'),
('Thet Thet Aung Custome', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Thet Thet Aung - Custome Service (MT).docx'),
('Thet Phyo Wai', 'thetwaiphyoe.503@gmail.com', '09766670708', 'Management', 'leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Thet Phyo Wai -Sales Manager (Telecom)MT.docx'),
('Ma Khin Moe Moe', 'Khinmoemoe0219@gmail.com', '09974855852', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Ma Khin Moe Moe - Sales Admin (MDY)MT.docx'),
('Min Thu Aung', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Min Thu Aung - Sales (MT).docx'),
('Yu Yu Aung', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Yu Yu Aung - Sales & Marketing M (MT).docx'),
('Eea Hr', NULL, '09455208582', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: EEA HR Executive (Insein) MT.docx'),
('Cho Zin Latt Hr', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Cho Zin Latt - HR Executive (MT).docx'),
('Khin Khin Myint Procurement', 'khinkhinmyint002@gmail.com', '0997224274', 'Operations', 'excel', 'active', 'CV Lead Tracker', 'CV: Khin Khin Myint - Procurement Executive (MT).docx'),
('Aung Thu Aye', 'aungthuaye@mytel.com.mm', '9691050988', 'General/Other', 'communication', 'active', 'CV Lead Tracker', 'CV: Aung Thu Aye - Telecom Engineer (MT).docx'),
('Personal Data', 'ngweni686@gmail.com', '09958360993', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Nwe Ni - HR & Admin Executive (MT).docx'),
('Daw Lae Lae Hlaing', NULL, NULL, 'Management', 'git, excel', 'active', 'CV Lead Tracker', 'CV: Lae Lae Hlaing - Media Production (MT).docx'),
('Yaminn Thant', 'yaminnthant76@gmail.com', '09982427979', 'Finance & Accounting', 'excel, powerpoint, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Yaminn - Junior Banking (MT).docx'),
('Aung Kaung Pwint Noc', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Kaung Pwint - NOC Engineer (MT).docx'),
('Government Technical Institute Myingyan', NULL, '09977495293', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Chit Su Wai - Engineer no exp (NPT) MT.docx'),
('W Thandar Procurement', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Saw Thandar CV - Procurement Manager(1).docx'),
('Maung Maung Qa', NULL, NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Maung Maung - QA & IT manager (MT).docx'),
('Psw Warehouse', NULL, NULL, 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: PSW - Warehouse Manager (MT).docx'),
('Eaindra Khin Customer Service', NULL, '09978509445', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Eaindra Khin - Customer Service (MT).docx'),
('May Thanda Soe', 'mtdsoe@gmail.com', '09771356457', 'Engineering', 'sql', 'active', 'CV Lead Tracker', 'CV: May Thanda Soe - Data Analyst (MT).docx'),
('Zayar Maung', 'zayarmaungzl95.zl@gmail.com', '09666584014', 'Engineering', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Zayar Maung (Electrical Engineer).docx'),
('Aye Nandar', NULL, NULL, 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Aye Nandar - Finance Manager (MT).docx'),
('Aung Min Hein', 'aungminhein22697@gmail.com', '09269785050', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Min Hein - Sale Engineer (MT).docx'),
('Phyo Thu Khin', 'phyothukhin86@gmail.com', NULL, 'General/Other', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Phyo Thu Khin - Procurement M (MT).docx'),
('Aung Zin Myo', NULL, '09883343338', 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Aung Zin Myo - Sales & M (MT).docx'),
('Swe Swe Oo Hr', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Swe Swe Oo - HR Manager (MT).docx'),
('Roshan Kumar', 'roshankumar.51@gmail.com', '09977292947', 'Management', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Roshan kumar - Executive manager, inventory controller.docx'),
('Ye Win Aung', 'yewintaung8800@gmail.com', NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Ye Win Aung -  Admin&HR Mgr (MT).docx'),
('Theinhtayaung Maintiance', 'theingyi756@gmail.com', '09977029173', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: theinhtayaung - Maintiance Engineer(MT).docx'),
('Thin Thiri Aung Payroll', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Thin Thiri Aung - Payroll Executive (MT).docx'),
('Mr.pyae Lin Phyoe', 'Email-nick91585@gmail.com', '09674154668', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Pyae - Sales & Marketing (MT).docx'),
('Ei Thandar Maw', 'eithandarmaw777@gmail.com', '09977033989', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Ei Thandar Maw.docx'),
('Personal And Contact Information', 'kyawthetthet953@gmail.com', '959443437054', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Kyaw Thet - Head of Sales (35 lakhs)MT.docx'),
('Min Min Ei', 'minminei186@gmail.com', '09958339016', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Min Min Ei - HR & Admin Manager (MT).docx'),
('Yadanar Htun Merchandising', 'htunyadanar45@gmail.com', NULL, 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Yadanar Htun - Merchandising (MT).docx'),
('Aung Pyae Phyo Qa', NULL, NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Pyae Phyo -QA (MT).docx'),
('Min Khant Zaw Receptionist', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Min Khant Zaw - Receptionist (MT).docx'),
('Mi Mi N Qc', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Mi Mi San - QC (MT).docx'),
('Aung Min Oo', 'minmin11rockergyi@gmail.com', '09794850080', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: AUNG MIN OO - Export & Import Document.docx'),
('Khin Khin Thet', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Khin Khin Thet - Executive pathein.docx'),
('Nyi Nyi Lynn Htet', 'nyinyilinhtet219@gmail.com', '09956218886', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Nyi Nyi Lin Tun - HR Executive (Mingalar)MT.docx'),
('Career Highlights', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: NayLinAung - Sales Manager (MT).docx'),
('Myo Aung Hr', NULL, NULL, 'HR & Admin', 'photoshop', 'active', 'CV Lead Tracker', 'CV: Myo Aung - HR Manager (MT).docx'),
('Career History', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Myint Mo Oo - Modern Trade Sales Manager (MT).docx'),
('Nyi Nyi Lwin It', 'n2lwin88@gmail.com', '09665614449', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Nyi Nyi Lwin - IT Assistant (MT).docx'),
('Khin Thuzar Myo', 'Khinthuzarmyo13@gmail.com', '09971665637', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Khin Thuzar Myo - Finance Assistant (Microfin)MT.docx'),
('Pyae Phyo Khaing', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Pyae Phyo Khaing - Sales Manager (MT).docx'),
('Nwe Nwe Oo', 'nwenwe.oo111991@gmail.com', '09778111722', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Nwe Nwe Oo - Senior Sales Admin (MT).docx'),
('Aung Zin Phyoe', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Zin Phyoe - Senior IT Officer (MT).docx'),
('Nyi Nyi Lin Thu', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Nyi Nyi Lin Thu - IT Officer (MT).docx'),
('Poe Noe Noe Naing', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Poe Noe Noe Naing - Page Admin (MT).docx'),
('Pa Pa N Purcher', NULL, '09756693724', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Pa Pa San - Purchsaer (Bago)MT.docx'),
('Hnin Phyu Moe', 'hninphyu.moe2017@gmail.com', '09459292817', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Hnin Phyu Moe - Executive (Pathein).docx'),
('Hnin Pwint Hr', 'hninpwint2322021@gmail.com', '09767191223', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Hnin Pwint - HR Assistant (MT).docx'),
('Phyo Thazin', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Phyo Thazin 15.docx'),
('Aung La Min', 'aunglaminthet506@gmail.com', '09960062263', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Aung La Min - Sales (Taungoo) MT.docx'),
('Contact Information', 'shweyaminaye1292000@gmail.com', '9942912000', 'General/Other', 'excel', 'active', 'CV Lead Tracker', 'CV: Shwe Yamin Aye - IT Staff (MT).docx'),
('Nay Myo Khant Noc', NULL, NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Nay Myo Khant - NOC Engineer (MT).docx'),
('Nn Win General', 'sannwin1984@gmail.com', '09684489435', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Sann Win - General Manager (MT).docx'),
('Name Zaw Naing', 'kothargyee.pma@gmail.com', '09262500533', 'Operations', NULL, 'active', 'CV Lead Tracker', 'CV: ZawNaing- Logistic & Proecurement (MT) 20 lakhs.docx');