-- ============================================
-- CV Lead Tracker - Batch 1 of 5
-- Leads 1 to 500
-- ============================================

INSERT INTO leads (name, email, phone, current_position, skills, status, source, notes) VALUES
('Zawng Hkawng', 'zawng4@gmail.com', '09767610030', 'Management', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: Zawng Hkawng - Senior Network Engineer (MT) (2) (1).pdf'),
('H T U N', 'eizinmartun092@gmail.com', '9798854087', 'Engineering', 'python, mysql, sql, communication', 'active', 'CV Lead Tracker', 'CV: Ei Zin Mar Htun - NOC (MT).pdf'),
('Pan Ei Kyaw Cashier', 'paneikyaw058@gmail.com', '09980195394', 'General/Other', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Pan Ei Kyaw - Cashier (MT).pdf'),
('Cv.syph(1)', 'shweyeepoehan.jitjit@gmail.com', '09766472505', 'Management', 'excel, communication, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: CV.SYPH(1).pdf'),
('Mmzoo Secretary', 'moemayzinoo@protonmail.com', '09267547396', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: MMZOo- Secretary (MT).pdf'),
('About Myself', 'Aungzawhtetaungxidocudar@gmail.com', '09954544670', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Zaw Htet Aung - Warehouse M (MT).pdf'),
('Ko Ko Lat', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Ko Ko Lat - Sales & Marketing Manager (MT) (1).pdf'),
('Pyae Phyo Receptionist', 'ppthura19@gmail.com', '09456924563', 'Operations', 'excel', 'active', 'CV Lead Tracker', 'CV: Pyae Phyo - Receptionist (MT).pdf'),
('Pann Wutye Khaing Hr', 'pannwutye48@gmail.com', NULL, 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Pann Wutye Khaing - HR Assistant (MT).pdf'),
('Hein Htet Zaw It', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Hein Htet Zaw - IT Assistant (MT).pdf'),
('Ma. Kristela Carlota Tamonte', 'mk.carlotat@gmail.com', '959894685032', 'Management', 'aws, communication', 'active', 'CV Lead Tracker', 'CV: Ma+kristela+CV- QA (F) MT.pdf'),
('Aye Thet Zin Hr', 'ayethetzin2000@gmail.com', '09757947090', 'Data & Analytics', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Aye Thet Zin - HR Assistant (MT).pdf'),
('Ung Oo Zin', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Saung Oo Zin - Sales Operator (MT).pdf'),
('Thant Zin Oo', 'thantzin.link7@gmail.com', '09965906637', 'Management', 'excel, communication, project management', 'active', 'CV Lead Tracker', 'CV: Thant Zin Oo - Sales & Marketing (MT).pdf'),
('Hein Tay Zar', NULL, '09251670466', 'Management', 'git, leadership', 'active', 'CV Lead Tracker', 'CV: Hein Tay Zar - Senior Marketing Executive (MT).pdf'),
('Personal Details', NULL, NULL, 'Design', 'java, javascript, illustrator, communication', 'active', 'CV Lead Tracker', 'CV: Ye Yint Aung - Graphic Designer (MT).pdf'),
('Mariner Enterprise Co,ltd.', 'htetaunglinn15500@gmail.com', '09794878840', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Htet Aung Lin - Data Entry (MT).pdf'),
('Jone Hr', 'jimincrystal98@gmail.com', '9785339261', 'HR & Admin', 'communication', 'active', 'CV Lead Tracker', 'CV: Jone - HR Assistant (NPT) MT.pdf'),
('Yeminaung', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: YeMinAung - Senior Sales (MT).pdf'),
('Kyaw Tun Training', 'kyawhtun1975@gmail.com', '09797045046', 'Management', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Kyaw Tun -Training Manager (MT).pdf'),
('Personal Details', '9aungpyaephyo@gmail.com', '09261975006', 'Management', 'git, excel, photoshop', 'active', 'CV Lead Tracker', 'CV: Aung Pyae Phyo - Media Production (MT).pdf'),
('Personal Particular', 'kooo.nl36@gmail.com', '09780779640', 'Management', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Aye Min Oo - HR & Admin.pdf'),
('Technological University', 'fantasticboylay6420@gmail.com', '959770589664', 'Management', 'powerpoint, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Soe Moe Naing - M & E (NPT) MT.pdf'),
('Thin Htet Zar Corporate', '3@gmail.com', '09776160922', 'Management', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Thin Htet Zar - Corporate RM (MT).pdf'),
('Myat Thandar Htet', 'mamamyatofficial@gmail.com', '959796254974', 'Management', 'git, excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Mya Thandar Htet - Head of Marketing (MT).pdf'),
('Thanyawzin Moe Korean Translator', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Thanyawzin Moe - Korean Translator (MT)_removed.pdf'),
('Hsu Ei N', 'hsueisansan@gmail.com', '959956885854', 'Management', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Hsu Ei San - Executive Assitant (Ma Lwin).pdf'),
('Naing Win', 'civilnaingwin2naingwincivil@gmail.com', '09448004954', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Naing Win - Senior Site Engineer (MT).pdf'),
('Khin Mar Lar Zin', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Khin Mar Lar Zin - Merchansiding Supervisor (MT).pdf'),
('May Thingyan Hr', 'malaysisar1993@gmail.com', '09795859294', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: May Thingyan - HR (MT).pdf'),
('Aung Hein Htet', NULL, '09972747177', 'Management', 'aws', 'active', 'CV Lead Tracker', 'CV: Aung Hein Htet - Corporate S (MT).pdf'),
('Pwint Swe', 'pwintooswe.pp@gmail.com', NULL, 'Management', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: PWINT SWE - Executive Assistant (MT).pdf'),
('Ko Shane Slaes', 'shanethiha.tgo@gmail.com', '09
770840487', 'Sales & Marketing', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Ko Shane - Slaes (Taungoo)MT.pdf'),
('Thein Soe Hr', NULL, '09765652802', 'HR & Admin', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Thein Soe - HR Executive (MT).pdf'),
('Su Myat Hein', '99@gmail.com', '09967013018', 'Sales & Marketing', 'communication', 'active', 'CV Lead Tracker', 'CV: Su Myat Hein - English Translator (MT) (1).pdf'),
('Government Technical Institute', 'chitsuwai745@gmail.com', '09977495293', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Ma_Chit Su Wai- M& E Engineer (NPT)MT.pdf'),
('Curriculum Vitae', 'zawwin.naing97@gmail.com', '09980647849', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Zaw Win Naing- Territory Sales Representative (MT).pdf'),
('Tin Maung Latt', 'tmlatt@gmail.com', '09250954642', 'Management', 'leadership, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Tin Maung Latt - Warhouse Mangaer (MT).pdf'),
('Kaung Si Lwin', 'kaungsilwin77@gmail.com', '09448875885', 'General/Other', 'communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Kaung Si Lwin - Sales (TGI)MT.pdf'),
('Khaing Wah Wah', 'khaingwarwar3546@gmail.com', '09761541415', 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Khaing Wah Wah - Sales Admin (MT).pdf'),
('Khant Paing Oo', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Khant Paing Oo - Sales (MT).pdf'),
('Hsu Mon Aung', 'kalay.sumonaung@gmail.com', '09984494356', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Hsu Mon Aung - Sales Manager (MT).pdf'),
('Race - Myanmar', NULL, NULL, 'Customer Service', NULL, 'active', 'CV Lead Tracker', 'CV: Moe Khant Aung - Showroom Sales (MT).pdf'),
('Yaty Swe Hlaing', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Yaty Swe Hlaing- Senior HR Executive (MT).pdf'),
('Aye Aye Aung Warehouse', 'msayeaye111@gmail.com', '09954007723', 'Operations', 'excel, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Aye Aye Aung - Warehouse Manager(MT).pdf'),
('Curriculum Vitae', 'susunyeinaung.ygn.2019@gmail.com', '09254572618', 'HR & Admin', 'aws, excel, leadership', 'active', 'CV Lead Tracker', 'CV: Su Su Nyein Aung - HR Executive (MT).pdf'),
('Win Pyae Kyaw', NULL, '959974573346', 'Management', 'excel, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Win Pyae Kyaw - Sales (Modern Trade) MT.pdf'),
('Thu Zar Aye', 'thuzarmicd@gmail.com', NULL, 'Management', 'aws', 'active', 'CV Lead Tracker', 'CV: Thu Zar Aye - Sales Supervisor (MT).pdf'),
('May Yadanar Soe', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: May Yadanar Soe - Sales & Casheir (MT).pdf'),
('Curriculum Vitae', NULL, '09962860550', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Ko Ko Naing - M & E Engineer (MT).pdf'),
('Mr. Kyaw Moe Thu', '574@gmail.com', '959954556778', 'Engineering', 'communication', 'active', 'CV Lead Tracker', 'CV: Kyaw Moe Thu - Fiber Work Eng (MT).pdf'),
('Cherry Hr', 'cherrymyatnoe12@gmail.com', '959777187598', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Cherry - HR Assistant (MT).pdf'),
('Yangon, Myanmar', 'moemyintkyaw.mmk1994@gmail.com', '959772547211', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Moe Myint Kyaw - M & E Engineer (MT).pdf'),
('Hnin Oo', 'hninoolwin42@gmail.com', '09421127830', 'Engineering', 'communication', 'active', 'CV Lead Tracker', 'CV: hnin oo - Junior Engineer (MT).pdf'),
('Eaindray Thet Customer Service', NULL, NULL, 'Customer Service', NULL, 'active', 'CV Lead Tracker', 'CV: Eaindray Thet  - Customer Service (MT).pdf'),
('Ar Hman Sitt Hmue', 'skoolamsh1993@gmail.com', '09440100723', 'HR & Admin', 'git, communication', 'active', 'CV Lead Tracker', 'CV: Ar Hman Sitt Hmue - Content Writer (MT).pdf'),
('Su Twetar Aung Customer', NULL, NULL, 'Customer Service', NULL, 'active', 'CV Lead Tracker', 'CV: Su Twetar Aung - Customer Service (MT).pdf'),
('Yoon Ndi Htun Cashier', 'yoonsandihtun482@gmail.co', '09798096839', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Yoon Sandi Htun - Cashier (MT).pdf'),
('Htet Htet Soe Lps', NULL, '09969043762', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Htet Htet Soe - LPS (MT).pdf'),
('Certifications Core Qualification', 'nyeinchansukyi779@gmail.comPROFESSIONAL', NULL, 'Operations', 'excel, powerpoint, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Nyein Chan Su Kyi - Procurement Executive (MT).pdf'),
('Joseph Site Engineer', NULL, NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Joseph - Site Engineer (MT).pdf'),
('Kaung Htet', 'kaunghtetkyaw2061998@gmail.com', '09694392124', 'Management', 'leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Kaung Htet Kyaw - Operation Supervisor (MT).pdf'),
('Hnin Yu Digital M', 'hninyuyuhlaing303@gmail.com', '959969570924', 'Sales & Marketing', 'git, excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Hnin Yu - Digital M M(MT).pdf'),
('Ahlone, Yangon', NULL, '+959777240619', 'Sales & Marketing', 'leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Htun Htun Win - English Transator (MT).pdf'),
('Certified In Networking', 'aung.aks086@gmail.com', NULL, 'Engineering', 'communication', 'active', 'CV Lead Tracker', 'CV: Aung Khaing Soe - NOC Engineer (MT).pdf'),
('Shun Lae Yee', 'shunlaeyee96@gmail.com', NULL, 'Healthcare', 'excel, powerpoint, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Shun Lae Yee - Sales Admin (MT)1.pdf'),
('Personal Information', 'yuyapaing.ds@gmail.com', '959949252010', 'Management', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Yu Pa Aung - Visual Merchandising (MT).pdf'),
('Htet Myat Myat Htun', NULL, '09756941035', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Htet Myat Myat Htun - Sales & Cashier (MT).pdf'),
('Yu Mon Aug', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Yu Mon Aug - SA (NPT)MT.pdf'),
('Aye Thinzar Zaw', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Aye Thinzar Zaw - Finance Assistant (Mirco)MT.pdf'),
('Yin Mar Htwe Receptionist', 'yinnmarhtwe230@gmail.com', NULL, 'Management', 'problem solving', 'active', 'CV Lead Tracker', 'CV: YIN MAR HTWE - Receptionist (MT).pdf'),
('Mr.aung Soe Lin', 'aungsoelin063@gmail.com', '09751453966', 'Management', 'excel, leadership, communication, project management', 'active', 'CV Lead Tracker', 'CV: Aung Soe Lin - Site Engineer (MT).pdf'),
('Htet Aung Shine Noc', 'has.nyinyi15796@gmail.com', '09254456445', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Htet Aung Shine - NOC (MT).pdf'),
('Thet Su Hliang Portfolio', 'thetsuhlaing4232@gmail.com', NULL, 'Management', 'leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Thet Su Hliang - Portfolio Manager (MT).pdf'),
('Tin Niang Tun', NULL, '09761664740', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Tin Niang Tun - Sales (MDY)MT.pdf'),
('Nang Hsu Thiri Nwe', 'hsuthirinwe99@gmail.com', '09442942743', 'Engineering', 'excel, powerpoint, analytical', 'active', 'CV Lead Tracker', 'CV: Nang Hsu Thiri Nwe - Sales (TGI)MT.pdf'),
('Aung Myo Than Korean', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Myo Than - Korean Translator (MT).pdf'),
('Name Aung Aung Lin', 'mraunglyn550@gmail.com', '959770169149', 'HR & Admin', 'java, javascript, mysql, sql, git, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Aung Aung Lin - Web Developer (MT).pdf'),
('Nay Chi Nway English', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Nay Chi Nway - English Translator (MT).pdf'),
('Nay Htet Aung Corporate', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Nay Htet Aung - Corporate Sales (insurance)MT.pdf'),
('Technical Skills', 'thazin211090@gmail.com', '959421172258', 'Engineering', 'mysql, postgresql, sql, leadership', 'active', 'CV Lead Tracker', 'CV: KHAING THAZIN MIN - Database Administrator (Microfincance)MT.pdf'),
('Mpwm Hr', 'mayphyowaimaung@gmail.com', NULL, 'HR & Admin', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: MPWM- HR Manager (NPT) MT.pdf'),
('Career Objective', 'henryedwardwalter46@gmail.com', '9785050118', 'Management', 'aws, excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Han Htet Zaw_Network Engineer (MT).pdf'),
('Aung Ko Myo', NULL, '959454521472', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Ko Myo - Manager FA (MT).pdf'),
('Theint Thinzar Win Lps', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Theint Thinzar Win - LPS (MT).pdf'),
('Strategic Leadership', 'saizinhlaing@gmail.com', '09970000985', 'Management', 'excel, leadership, communication, project management, analytical', 'active', 'CV Lead Tracker', 'CV: Kalix Liam - Head of Sales and Marketing (MT).pdf'),
('Moe Thet Aung Admin', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Moe Thet Aung - Admin & HR - Beverage (MT).pdf'),
('Ei Ei Phyoe', NULL, '09955960621', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Ei Ei Phyoe- Sales & Marketing (MT).pdf'),
('Personal Information', NULL, '09426473592', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Yu Swe Naing - HR & Admin (MT).pdf'),
('Aung Naing Tun Portfolio', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Naing Tun - Portfolio (MT).pdf'),
('Tun Yadanar Thein', 'yadanar231123@gmail.com', '09669996987', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Tun Yadanar Thein - Sales (MDY) MT.pdf'),
('Curriculum Vitae', 'nyinyihtun1319@gmail.com', '09425018866', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Nyi Nyi Htun - Modern Trade (MT).pdf'),
('Curriculum Vitae', 'wailwinmoe2022@gmail.com', '09793695712', 'Management', 'leadership', 'active', 'CV Lead Tracker', 'CV: Wai Lwin Moe - Corporate Sales Executive (MT).pdf'),
('Hlaingtharyar Township, Yangon.', 'khin.thaw87@gmail.com', NULL, 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Khin Kyi Kyi Thaw-HR Executive (HTY)MT.pdf'),
('Tin Nilar Win Hr', 'tinnila993@gmail.com', '959401553066', 'HR & Admin', 'excel, leadership, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Tin Nilar Win - HR Manager (MT).pdf'),
('Ware Hose Incharge', '8@gmail.com', '09978035880', 'Customer Service', 'communication', 'active', 'CV Lead Tracker', 'CV: Lwin Aung Aye - CCTV Operator (MT).pdf'),
('Thuzar Hr', NULL, '09794124430', 'Management', 'leadership, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: Thuzar-HR Manager (MT).pdf'),
('Thin Thin Nwe Cashier', 'theintnwe75@gmail.com', NULL, 'General/Other', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Thin Thin Nwe - Cashier (MT).pdf'),
('Dear Sir/madam,', '1hein.sithu98@gmail.com', '09448535809', 'Sales & Marketing', 'express, git', 'active', 'CV Lead Tracker', 'CV: Hein Si Thu - Digital Marketing E (MT.pdf'),
('Curriculum Vitae', NULL, NULL, 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Nilar Win Shwe - Korean Translator (MT).pdf'),
('Education Background', 'maymyatthaw8893@gmail.com', '09758327690', 'Management', 'excel, powerpoint, communication, analytical', 'active', 'CV Lead Tracker', 'CV: May Myat Thaw - Trade Data (MT).pdf'),
('Htun Lin Aung', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Htun Lin Aung - Sales (MDY)MT.pdf'),
('Suyuyamyat Cashier', 'yuya279@icloud.com', NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: SuYuYaMyat - Cashier (MT).pdf'),
('Khin Myo Win Cusotmer', 'okhin98@gmail.com', '9692773924', 'General/Other', 'communication', 'active', 'CV Lead Tracker', 'CV: Khin Myo Win - Cusotmer Service (MT).pdf'),
('Kyi Phyu Thant', 'kyiphyuthant2020.tgi@gmail.com', '09457778601', 'General/Other', 'analytical', 'active', 'CV Lead Tracker', 'CV: Kyi Phyu Thant CV(1).pdf'),
('Aung Myo Htut', 'htutaungmyo567@gmail.com', '09958343917', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Myo Htut - Sales  Rep(MT).pdf'),
('Hr And Admin', NULL, '09891160348', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: HR and admin executive.pdf'),
('Tint Wai Tun Procurement', 'tintwaitun.twt1992@gmail.com', '09973623539', 'Sales & Marketing', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: TINT WAI TUN - Procurement Executive (MT).pdf'),
('Khin E Oo Shwe', 'khineooshwe@gmail.com', '9401676399', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Khine Oo Shwe - Site Engineer (MT).pdf'),
('Yan Naing Soe', 'yn0918879@gmail.com', '09660940927', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Yan Naing Soe - Sales (Bago)MT.pdf'),
('Bhone Sitt Paing', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Bhone Sitt Paing - Sales Rep (South Oak)MT.pdf'),
('Hsu Ei N', 'hsueisansan@gmail.com', '959956885854', 'Management', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Hsu Ei San - Executive Assistant (MT).pdf'),
('Thwe Thet Htar', 'thwe.thet.htar9@gmail.com', NULL, 'Management', 'aws, azure, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Thwe Thet Htar - Executive Assistant (MT).pdf'),
('Thet Su Mon Cashier', 'zaysumon995@gmail.com', '09958369804', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Thet Su Mon - Cashier (Hintada)MT.pdf'),
('Kay Thi Data Entry', 'kay391851@gmail.com', '+959788466907', 'Finance & Accounting', 'communication', 'active', 'CV Lead Tracker', 'CV: Kay Thi - Data Entry (MT).pdf'),
('Aung Myo Hein', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Myo Hein - Senior FA (TGI) MT.pdf'),
('Wai Yan Oo Sotre', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Wai Yan Oo - Sotre Keeper (MT).pdf'),
('Poe Yu Hlaing Site', 'poeyuhlaing1997@gmail.com', '959779761145', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Poe Yu Hlaing - Site Engineer (MT).pdf'),
('Aung Myo Sann', 'aungmyosann2017@gmail.com', '0946655375', 'Engineering', 'java, javascript, postgresql, sql, docker', 'active', 'CV Lead Tracker', 'CV: Aung Myo San - Full Stack Software Engineer (MT).pdf'),
('Aung Thura Soe', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Thura Soe - Sales Manager (MT).pdf'),
('Hr Manager', 'zzk444x@gmail.com', '+959783687323', 'HR & Admin', 'excel, leadership, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Khine Zar Zar Lin - HR Manager (MT).pdf'),
('Corporate Sales Executive', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Khaing Thazin Thwe - Corporate Sales Executive (MT).pdf'),
('Nilar Khaing Cashier', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Nilar Khaing - Cashier (MT).pdf'),
('Pwint Oo Swe', 'pwintooswe.pp@gmail.com', NULL, 'Management', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: Pwint Oo Swe - Executive Assistant (MT).pdf'),
('Critical Thinking', 'Thingangyunzawwintun.mm@gmail.comExperience', '09972797154', 'Management', 'excel, powerpoint, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Zaw Win Tun_ M & E Engineer (MT).pdf'),
('With Photo Staff', NULL, '09250245900', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: WITH PHOTO (1)HR staff.pdf'),
('Smkla Tax A', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: SMKLA - Tax A (MT).pdf'),
('Working Experience', 'waiphyoeoo2009@gmail.com', '0943097139', 'Management', 'aws, communication', 'active', 'CV Lead Tracker', 'CV: Wai Phyoe Oo - Chief Engineer (MT).pdf'),
('Su Su', 'sus69665@gmail.com', '09440042505', 'HR & Admin', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Su-Su-Sandi-goodcv.com-240323.132803.pdf'),
('Ayechanmoe Medical Slaes', 'ayechanmoe1010@gmail.com', '09421094890', 'Sales & Marketing', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: AyeChanMoe  - Medical Slaes Executive (MT).pdf'),
('Kay Thin Oo Cashier', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Kay Thin Oo - Cashier (MT).pdf'),
('Aung Naing Ae', NULL, '09455575039', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Naing - AE (NPT) MT.pdf'),
('N Mya Thida Tun', 'sanmyathidatun@gmail.com', NULL, 'Sales & Marketing', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: San Mya Thida Tun - Japanese Teacher (MT).pdf'),
('Kyaw Zan Htet', 'kyawzinhtetgit@gmail.com', '959885309563', 'Engineering', 'git', 'active', 'CV Lead Tracker', 'CV: Kyaw Zan Htet - IT Supervisor (MT).pdf'),
('Hein Min Htet', 'hminhtet591@gmail.com', '09977049032', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Hein Min Htet - Manager FA (MT).pdf'),
('Set Naing Phyo Hr', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Set Naing Phyo - HR Assistant (MT).pdf'),
('Ingyin Mon Portfolio', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Ingyin Mon - Portfolio (MT).pdf'),
('Ms. Pa Pa Win', 'winp5688@gmail.com', '09787934704', 'Management', 'git, excel', 'active', 'CV Lead Tracker', 'CV: Pa Pa Win  - Corporate Relationship Manager (Pathein).pdf'),
('Phue Ya Mone Soe', 'phuep1997@gmail.com', '09967989695', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Phue Ya Mone Soe  - LPS (MT).pdf'),
('Myat Thet Hr', 'myatthet31@gmail.com', '09799220867', 'HR & Admin', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Myat Thet - HR Manager (NPT) MT.pdf'),
('Nandar Lyan Hr', 'nandarlyan0@gmail.com', '09768239636', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Nandar Lyan - HR Assistant (MT).pdf'),
('Htz It Support', 'heintayzar49@gmail.com', '959254381183', 'Engineering', 'git, excel, problem solving', 'active', 'CV Lead Tracker', 'CV: HTZ  - IT Support (MT).pdf'),
('Hnin Ei Phyu', 'cbaby5769@gmail.com', '09444105425', 'Education', NULL, 'active', 'CV Lead Tracker', 'CV: Hnin Ei Phyu - Chinese T (MT).pdf'),
('Ms. Jacqueline Buu Bu', 'Jacquelinebuubu15@gmail.com', NULL, 'Sales & Marketing', 'git, excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Jacqueline Buu Buu - Englsih Translator (MT).pdf'),
('Thu Thu Htet Hr', 'thuthuhtet9296@gmail.com', '09692806115', 'Management', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Thu Thu Htet - HR Manager (MT).pdf'),
('Race - Myanmar', NULL, '09769768072', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Khaing Cho Zin Myint - Showroom Sales Staff (MT).pdf'),
('Graphic Designer', NULL, NULL, 'Design', NULL, 'active', 'CV Lead Tracker', 'CV: Zaw Myo Thu - Graphic Designer (MT).pdf'),
('Ayemyatthinkyi Business Analyst', 'ayemyatayemyat.mdy@gmail.com', '959401668026', 'Engineering', 'excel, project management, problem solving', 'active', 'CV Lead Tracker', 'CV: AyeMyatThinKyi_Business Analyst (MT).pdf'),
('Working Experience', NULL, '09950302069', 'Sales & Marketing', 'communication', 'active', 'CV Lead Tracker', 'CV: Ye Yint Kyaw Myint Htay - Data Collector (Meikhtila)MT.pdf'),
('Contact Me', 'mr.aungthuya@gmail.com', NULL, 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Aung Thu Ya - Media Production (MT).pdf'),
('Shwe Sin Phyo Cashier', 'aerizin2484@gmail.com', '09962693689', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Shwe Sin Phyo - Cashier (NPT)(MT).pdf'),
('Zune Phuu Wai', 'zunephuuwai197@gmail.com', '959962139995', 'Engineering', 'excel, analytical', 'active', 'CV Lead Tracker', 'CV: Zune Phuu Wai - Junior Auditor (MT).pdf'),
('Hein Htet Aung', 'ygn.unclehein612@gmail.com', '09758819247', 'Sales & Marketing', 'git', 'active', 'CV Lead Tracker', 'CV: Hein Htet Aung - Sales (MT).pdf'),
('Zau Lung Noc Engineer', 'lungzau7@gmail.com', '09755816412', 'Engineering', 'communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Zau Lung -NOC Engineer (MT).pdf'),
('Ingyin Phyoe Content Writer', NULL, '09267671528', 'Sales & Marketing', 'git', 'active', 'CV Lead Tracker', 'CV: Ingyin Phyoe - Content Writer (MT).pdf'),
('Nay Aung Lin Procurement', 'nayaglinn.2018@gmail.com', '95945123629', 'HR & Admin', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Nay Aung Lin - Procurement Executive (MT).pdf'),
('Nda Thin Procurement', 'sandathin@yahoo.com', NULL, 'Operations', 'excel, project management', 'active', 'CV Lead Tracker', 'CV: Sanda Thin - Procurement Manager (MT).pdf'),
('Zin Mar Oo', 'zinmar15692@gmail.com', '959424500048', 'Management', 'git, excel, leadership, communication, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: Zin Mar Oo - Sales & M Manager (MT).pdf'),
('A Mi Kyaw Moe', NULL, '959423689377', 'Engineering', 'excel, problem solving', 'active', 'CV Lead Tracker', 'CV: A Mi Kyaw Moe - NOC Engineer (MT).pdf'),
('Yell Htet Lwin Hr', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Yell Htet Lwin -HR Assistant (MT).pdf'),
('Yangonhein Htet Zaw', NULL, NULL, 'Engineering', 'leadership', 'active', 'CV Lead Tracker', 'CV: Hein Htet Zaw - IT Engineer (MT).pdf'),
('Curriculum Viate', 'hninyuwai519@gmail.com', '959402703345', 'HR & Admin', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Hnin Yu Wai - HR & Admin Manager (NPT).pdf'),
('May Zun Win Hr', 'mayzonwin9@gmail.com', '09676178156', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: May Zun Win - HR Assistant (Thinganyun)MT.pdf'),
('Ma Phyu Sin Thwe', NULL, '09445055405', 'HR & Admin', 'aws, excel, communication', 'active', 'CV Lead Tracker', 'CV: Ma Phyu Sin Thwe -Senior HR Executive (MT).pdf'),
('Ye Htet Oo Hr', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Ye_Htet_Oo_- HR Executive (MT).pdf'),
('Kamayut Township, Yangon.', 'ngwewun.pchi8@gmail.com', '+959740012057', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Win Nay Yee Kyaw - Operation Supervisor (MT).pdf'),
('Thw Thw N', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Thw Thw San - Sales & Marketing (MT).pdf'),
('Race - Myanmar', 'aungthihamyanmar758@gmail.com', '09965552892', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Thi Ha - Territory Sales (MT).pdf'),
('Than Than Aye Hr', 'thanthanaye.mm88@gmail.com', '+959799640453', 'HR & Admin', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Than Than Aye - HR Assistant (MT).pdf'),
('Thet Htar Swe Hr', 'thethtarswe546@gmail.com', NULL, 'Management', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: Thet Htar Swe - HR Manager (MT).pdf'),
('Personal Information', 'swezinmon7777777@gmail.com', '09753119335', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Swe Zin Thet Naing - HR Executive (MT).pdf'),
('Su Mon Aung', 'happyfamilytype@gmail.com', '09979168684', 'HR & Admin', 'aws, excel, powerpoint, photoshop, communication', 'active', 'CV Lead Tracker', 'CV: Su Mon Aung - Senior HR Executive (MT).pdf'),
('Aye Nandar Kyaw Cashier', 'aw1720@gmail.com', '09779590959', 'Finance & Accounting', 'communication', 'active', 'CV Lead Tracker', 'CV: Aye Nandar Kyaw - Cashier (NPT)MT.pdf'),
('Theingi Cashier', 'tgi500048@gmail.com', '09794617436', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Theingi - Cashier (MT).pdf'),
('Ye Htut Win', 'Yangonyehtutnaing107@gmail.com', '09678372552', 'General/Other', 'photoshop', 'active', 'CV Lead Tracker', 'CV: Ye Htut Win - Junior Graphic Designer (MT).pdf'),
('Win Htun Oo', 'winhtunoo.who@gmail.com', '959972181781', 'Engineering', 'java, javascript, react, mysql, sql, git, photoshop', 'active', 'CV Lead Tracker', 'CV: Win  Htun Oo - iOS Developer (MT).pdf'),
('Pay Roll', 'mahar2871997@gmail.com', '959754944060', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Mahar’s+Official+-Pay roll assistant (MT).pdf'),
('Professional Experience', 'jonhhtet92@gmail.com', '959442085672', 'Engineering', 'excel, leadership, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Wai Yan Htet- Telecom Installation Engineer (MT).pdf'),
('Mimi Min Htet Cashier', 'dawmememinnhtet@gmail.com', '09752610004', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Mimi Min Htet _ Cashier (Pathein)MT.pdf'),
('Ei Paing Paing Htet', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Ei Paing Paing Htet - Junior Recruiter (MT).pdf'),
('May Thandar Kyaw', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: May Thandar Kyaw - Sales Operator (MT).pdf'),
('Ma War War Thin', 'warwarthinnn@gmail.com', NULL, 'Engineering', 'sql, excel', 'active', 'CV Lead Tracker', 'CV: Ma War War Thin - Senior Cashier (MT).pdf'),
('Shwe Yi Hnin Lwin', 'shweyihninlwin.ptn@gmail.com', '09661506696', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Shwe Yi Hnin Lwin - Junior Executive.pdf'),
('Yair Yint Yan Naing', '959987895715yyeyint586@gmail.com', NULL, 'HR & Admin', 'communication', 'active', 'CV Lead Tracker', 'CV: Yair Yint Yan Naing - QC (Bank) MT.pdf'),
('Aye Nyein Moe Qa', 'nyeinnyeinmoe365@gmail.com', '09250508675', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Aye Nyein Moe - QA (MT).pdf'),
('Naing Lin', 'kolinn18989@gmail.com', '09740971041', 'Management', 'express, excel, photoshop, illustrator, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Naing Lin - Sales Manager (MT).pdf'),
('Tin Tin Naing', 'g@gmail.co', '959450672663', 'Management', 'git', 'active', 'CV Lead Tracker', 'CV: Tin Tin Naing - Manager Financial Advisor (MT).pdf'),
('Moe Moe Hlaing Qa', 'moemh5032@gmail.com', '09772774514', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Moe Moe Hlaing - QA (MT).pdf'),
('Digital Marketing Executive', 'tinzarkyaw227@gmail.com', NULL, 'Sales & Marketing', 'git, photoshop, communication', 'active', 'CV Lead Tracker', 'CV: Tin Zar Kyaw -Digital Marketing Executive (MT).pdf'),
('Chaw Su Mon Hr', 'chawsumon107@gmail.com', NULL, 'HR & Admin', 'aws, excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Chaw Su Mon - HR Assistant (MT).pdf'),
('Co Ntact', NULL, NULL, 'Engineering', 'excel, powerpoint, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Ye Lin Htun - M& E (MT).pdf'),
('Mr.lin Htet Aung', NULL, '95940262914', 'Engineering', 'excel, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Lin Htet Aung - M & E (MT).pdf'),
('Win Htike It', 'winhtike169064@gmail.com', '09254218307', 'Engineering', 'excel, communication, project management', 'active', 'CV Lead Tracker', 'CV: Win Htike - IT (MT).pdf'),
('Min Thitr', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Min Thitsar -Sales (Bago).pdf'),
('Hnin Ei Phyu Hr', 'hsuhtetmyat2280@gmail.com', '09666866449', 'Management', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Hnin Ei Phyu - HR Assistant (MT).docx.pdf'),
('Audit Assitancecontact', 'waip13976@gmail.com', '959771671485', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Wai Phyo Kyaw - Content Writer (Freelance)MT.pdf'),
('Zarni Data Entry', 'primexyro@outlook.com', NULL, 'Engineering', 'photoshop', 'active', 'CV Lead Tracker', 'CV: Zarni - Data Entry (MT).pdf'),
('Ye Win Htun', 'yewinhtun024680@gmail.com', '09421166586', 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Ye Win Htun - Corporate RM (MT).pdf'),
('Race - Myanmar', 'theimnyuntswe@gmail.com', '09400506768', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Thein Nyut Swe - Medical Sales Rep (MT).pdf'),
('Aung Pyae Phyo Medical', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Pyae Phyo - Medical Rep (MT).pdf'),
('Ba History', NULL, '09455487028', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Khin Thandar Cho - Korean Translator (MT).pdf'),
('Htun Eain Wint', 'htuneainwint97@gmail.com', '09976369563', 'Management', 'sql, excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Htun Eain Wint - Sales Admin (MT).pdf'),
('Educationwai Wai Soe', 'waiwaisoe3122@gmail.com', NULL, 'Management', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: Wai - Assistant Sales (Real Estate)MT.pdf'),
('Phu Pwint Thaw Hr', 'phupwintthaw3598@gmail.com', '09953713600', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Phu Pwint Thaw - HR Assistant (MT).pdf'),
('Mya Bel Oo', 'myasabaloo.mm@gmail.com', NULL, 'Operations', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Mya Sabel Oo - Sales Admin (MT).pdf'),
('Race - Myanma R', NULL, '09897725302', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Nyein Nyein Thandar Oo - Korean Translator (MT).pdf'),
('Aung Myat Thu', 'kothucnt173@gmail.com', NULL, 'Engineering', 'git', 'active', 'CV Lead Tracker', 'CV: Aung_Myat_Thu_ Senior Network Engineer (MT).pdf'),
('Zar Chi Oo', 'zarchioo972@gmail.com', '09260347059', 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Zar Chi Oo - Senior Accountant (MT).pdf'),
('Aung Naing Thu', NULL, '09968368909', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Naing Thu - Sales Promoter (MT).pdf'),
('U Than Myint Naing', 'htetthinzarlynn22@gmail.com', '09790281451', 'HR & Admin', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Htet Thinzar Lynn -HR Intern (MT).pdf'),
('Yangon, Myanmar', 'moemyintkyaw.mmk1994@gmail.com', '959772547211', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: MOE MYINT  - M & E Enginner (MT).pdf'),
('Electronic Engineerei Shoon Lai', 'setupsshoonlaiei@gmail.com', '09766081730', 'Engineering', 'excel, powerpoint, analytical', 'active', 'CV Lead Tracker', 'CV: Ei_Shoon_Lai - NOC Engineer (MT).pdf'),
('Khin Thu Zar', 'khinthuzar6891@gmail.com', NULL, 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: KhinThuZar-Finance Manager (MT).pdf'),
('Muditar Housing, Baho', 'phyuphyunadi@gmail.com', NULL, 'Customer Service', 'problem solving', 'active', 'CV Lead Tracker', 'CV: Nadi Chan Myae - System Engineer (MT).pdf'),
('Wutyi Moe', 'wutyimoe252294@gmail.com', '959798421678', 'Engineering', 'express, git, communication', 'active', 'CV Lead Tracker', 'CV: WutyiMoe - Junior Translator (MT) LinkedIn.pdf'),
('React, Angular, Next.js, Tailwind', 'byarpar0@gmail.com', '959770386642', 'Engineering', 'python, java, javascript, react, angular, node.js, mongodb, mysql, sql, git', 'active', 'CV Lead Tracker', 'CV: BYAR PAR -Full Stack Developer (MT).pdf'),
('North Shore', 'maythucho19@icloud.com', '959752770485', 'Engineering', 'excel, powerpoint, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: May Thu Cho - English Translator (MT).pdf'),
('Kyaw Zan Htet It', 'kyawzinhtetgit@gmail.com', '959885309563', 'Engineering', 'git', 'active', 'CV Lead Tracker', 'CV: Kyaw Zan Htet - IT (MT).pdf'),
('Kyaw Ye Lin', 'Kyawyelin214@gmail.com', NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Kyaw-Ye-Lin -M & E Engineer (MT).pdf'),
('Curriculum Vitae', 'ps1386627@gmail.com', '09787158408', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Kaung Htet Pyae Sone - Maintain E (MT).pdf'),
('Personal Particulars', 'lmm.hr@goodmorning.com.mm', NULL, 'Management', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Kyaw Zin Win - Production Engineer (MT).pdf'),
('Myo Thiri Tun Secretary', 'myothiri1210@gmail.com', '959455793057', 'Sales & Marketing', 'git, excel, communication', 'active', 'CV Lead Tracker', 'CV: Myo Thiri Tun - Secretary (MT).pdf'),
('Ye Win Bo Hr', NULL, '2020292023', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Ye Win Bo - HR Manager (MT).pdf'),
('Thazin Chit', 'thazinchit83@gmail.com', '09420040775', 'Sales & Marketing', 'git, excel, powerpoint, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Thazin Chit - Sales Manager (MT).pdf'),
('W Yu Nandar Media', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Saw Yu Nandar - Media Production Specialist (MT).pdf'),
('Nwe Nwe Win Cashier', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Nwe Nwe Win - Cashier (Pathein) MT.pdf'),
('Soe Hay Mar Naing', 'soehaymarnaing21@gmail.com', '09794359123', 'Management', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Soe Hay Mar Naing - Portfolio Manager (MT).pdf'),
('Zayar Lynn Graphic Designer', NULL, '09423599613', 'Design', NULL, 'active', 'CV Lead Tracker', 'CV: Zayar Lynn - Graphic Designer (MT).pdf'),
('Curriculum Vite', 'pyaephyopaing.myanmar@gmail.com', '959428202903', 'Management', 'aws, communication', 'active', 'CV Lead Tracker', 'CV: Pyae Phyo Paing - HSE Officer - 25 lakhs (MT).pdf'),
('Htwe Ko', 'htwek231996@gmail.com', '09979775514', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Htwe Ko_HR&Adminofficer (MT).pdf'),
('Haymann Ung Hnin Soe', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Haymann Saung Hnin Soe - English Translator (MT).pdf'),
('Myominmaw Head Of Les', NULL, '959792510436', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: MyoMinMaw - Head of Sales (MT).pdf'),
('Aung Kyaw Kyaw Portfolio', 'aungkyaw3856@gmail.com', '09693948677', 'Management', 'excel, leadership, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Aung Kyaw Kyaw - Portfolio Manager (MT).pdf'),
('Chit Min Tun', 'trumpscout4@gmail.com', '09423536691', 'Customer Service', 'excel', 'active', 'CV Lead Tracker', 'CV: Chit Min Tun - Chinese Translator (MT) (1).pdf'),
('Personal Information', 'hninwittyiwin1994@gmail.com', '09799318638', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Hnin Wut Yee Win - Payroll Assistant (MT).pdf'),
('Soe Myat Maung System', NULL, NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Soe Myat Maung -System Engineer (MT).pdf'),
('Kaung Myat Ko Ko', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Kaung Myat Ko Ko - Sales Executive (MT).pdf'),
('Aung Si Thu', NULL, NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Si Thu - Senior Site Engineer (MT).pdf'),
('Wai Wai Zin', NULL, '09790584207', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Wai Wai Zin - Sales (Bago)MT.pdf'),
('Nyein Chan Oo', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Nyein Chan Oo - Sales (MT).pdf'),
('Yan Naing Oo Portfolio', NULL, NULL, 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: TRM004 - Yan Naing Oo - Portfolio.pdf'),
('Nay Myo Thu Telecom', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Nay Myo Thu - Telecom Maintain Eng (MT).pdf'),
('Marital Status:married', 'htarhtarwin759@gmail.com', '09260358118', 'Management', 'git, excel, project management', 'active', 'CV Lead Tracker', 'CV: Htar Htar Win - Suitable Sales (MT).pdf'),
('Myat Cherry Lin Noc', 'myatcherrylin7@gmail.com', '09771788509', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Myat Cherry Lin - NOC (MT).pdf'),
('Work Experiences', 'khinpyaepyaeaung.pp@gmail.com', '9797729051', 'HR & Admin', 'communication', 'active', 'CV Lead Tracker', 'CV: Khin Pyae Pyae Aung - Persoanl Assistant (Korean Translator)MT.pdf'),
('Hein Thet Myo Hr', 'heinthetmyo@gmail.com', '09740891236', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Hein Thet Myo - HR Manager (MT).pdf'),
('Htun Eain Wint', 'htuneainwint97@gmail.com', '09976369563', 'Management', 'sql, excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Htun Eain Wint - Sales Operation Supervisor (MT).pdf'),
('Thuzar Win Korean Translator', 'thuzarw451@gmail.com', NULL, 'Customer Service', 'communication', 'active', 'CV Lead Tracker', 'CV: Thuzar Win - Korean Translator (MT).pdf'),
('N.r.c No. - 11/takana(n)088704', 'thelnus212@gmail.com', '0997332336', 'HR & Admin', 'communication', 'active', 'CV Lead Tracker', 'CV: Thae Nu San - Trade Data Executive (MT).pdf'),
('Chan Myae Kyaw Personal', NULL, NULL, 'Management', 'java, communication', 'active', 'CV Lead Tracker', 'CV: Chan Myae Kyaw - Personal Assistant (MT).pdf'),
('Ma Khin Yu', 'Mayywadi306@gmail.com', '09979503795', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Khin Min Yu Hlaing - QA (MT).pdf'),
('Soe Naing Hr', 'johnckbt81@gmail.com', '09425275145', 'HR & Admin', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Soe Naing - HR Manager (MT).pdf'),
('Theingi Hlaing Cashier', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Theingi Hlaing - Cashier (MT).pdf'),
('Production Engineer', 'maymi1011@gmail.com', '959781305484', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Ma May Mi Htet Maung - English Translator (MT) (1).pdf'),
('Myominnaing M E', 'nainglaypmn13572580@gmail.com', '09988738793', 'Engineering', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Myominnaing - M & E (NPT)MT.pdf'),
('Mon Mon Htay Procurement', NULL, '09420233393', 'Engineering', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Mon Mon Htay - Procurement Executive (MT).pdf'),
('Soe Yan Naung', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Soe Yan Naung - Sales (Bago)MT.pdf'),
('Race - Myanma R', NULL, '09650300679', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Shwe Yee Thin - Corporate Sales Executive (Pathein)MT.pdf'),
('Htet Paing Myo', 'htetpaingmyo99@gmail.com', '09960669124', 'Management', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Htet Paing Myo - Senior Network Engineer (MT).pdf'),
('Kyaw Zayyar Win Hr', 'kyawzayyarwintun@gmail.com', '959757694508', 'HR & Admin', 'leadership', 'active', 'CV Lead Tracker', 'CV: Kyaw Zayyar Win - HR Assistant (Insein)MT.pdf'),
('Nandar Hr', 'ataung93@gmail.com', '9256299415', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Nandar - HR assistant (NPT) MT.pdf'),
('Race - Myanmar', NULL, '09666677355', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Wai Yan Htet - Driver (MT) merge.pdf'),
('Soe Yan Paing Oo', 'soeyanpaingoo.sypo@gmail.comExperienced', NULL, 'Sales & Marketing', 'leadership, communication, project management', 'active', 'CV Lead Tracker', 'CV: Soe Yan Paing Oo - Marketing Manager (MT).pdf'),
('Su Wutyee Lin', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Su Wutyee Lin - Manager Financial Advsior (MT).pdf'),
('Zaw Min Htet', 'Expertisezawminhtet.cu27@gmail.com', NULL, 'Management', 'aws, excel, leadership', 'active', 'CV Lead Tracker', 'CV: Zaw Min Htet - Senior System E (MT).pdf'),
('Education Qualification', NULL, '09795497204', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: AHK - Sales Super (MT).pdf'),
('Eh Thu Hr', 'ehthu382025@gmail.com', '09785253410', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Eh Thu - HR Assistant (MT).pdf'),
('Thant Zaw Shin', NULL, '09420042419', 'Management', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Thant Zaw Shin - Manager FA (MT).pdf'),
('N.r.c No. - 8/tataka(n)269820', 'mariathetsan269820@gmail.co', '09768084914', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Thet Wady Hlaing - Office & Sale Staff (MT).pdf'),
('Than Htike Zaw Noc', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Than Htike Zaw - NOC Enginner (MT).pdf'),
('Thiha Suitable Les', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Thiha - Suitable Sales (MT)_1.pdf'),
('Educationzay Yar Myo', 'zayyarmyo3627@gmail.com', '959951890000', 'Sales & Marketing', 'git, excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Zay Yar Myo - Digital Marketing Executive (MT).pdf'),
('Eaindra Khin Customer Service', NULL, '09978509445', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Eaindra Khin - Customer Service (MT).pdf'),
('Name -ma Yamin', 'yaminyamin9yamin@gmail.com', '09960874605', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Yamin - Sales (Taungoo)MT.pdf'),
('Ei Yamin Htet', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Ei Yamin Htet - MT.pdf'),
('Mrs. Hnin Wai Aung', NULL, '09780499675', 'HR & Admin', 'aws, excel, communication', 'active', 'CV Lead Tracker', 'CV: Hnin Wai Aung - Corporate RM (MT).pdf'),
('Contact Details:', 'pannphyumaw2020@gmail.com', '09777679746', 'Engineering', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Pann Phyu Maw - M & E (MT).pdf'),
('Hsu Pyae Hlaing Hr', 'spyae3274@gmail.com', '09780441652', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Hsu Pyae Hlaing - HR Assistant (MT).pdf'),
('Junior Accountant', 'htetoolynn1998@gmail.com', '09951898694', 'Finance & Accounting', 'excel, analytical', 'active', 'CV Lead Tracker', 'CV: Htet Oo Lin - Customer Service (MT).pdf'),
('July One Customer Service', NULL, '09258707579', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: July One - Customer Service (MT).pdf'),
('Moe Nyein Shein', 'moenyeinshin1011@gmail.com', NULL, 'Sales & Marketing', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Moe Nyein Shein - Sales & Marketing (MT).pdf'),
('D Zin Lin', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Sa D Zin Lin -Sales Manager (MT).pdf'),
('Eaindray Aung', 'moewathan199678@gmail.com', '09955597304', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Eaindray Aung - Finance Assistant (MT).pdf'),
('Aung Phone Pyae It', NULL, '09785616568', 'Engineering', 'communication', 'active', 'CV Lead Tracker', 'CV: Aung Phone Pyae - IT Assistant (MT).pdf'),
('Korea Translator/', NULL, '09970874913', 'Operations', NULL, 'active', 'CV Lead Tracker', 'CV: Wutt Hmone Zin - Korean Translator (MT).pdf'),
('May Thazin Htwe', 'septembermay4198@gmail.com', '959453503071', 'Management', 'sql, git, communication', 'active', 'CV Lead Tracker', 'CV: May Thazin Htwe -IT Support (MT).pdf'),
('Hein Htet Aung', '1822018@gmail.com', '959772500323', 'Management', 'git, communication', 'active', 'CV Lead Tracker', 'CV: Hein Htet Aung - Sales Team Leader (MT).pdf'),
('Translator', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Thant+Thinzar+Nyi.- Translator (MT) LinkedIn..pdf'),
('Poe Ei Aung Naing', NULL, NULL, 'Management', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Poe Ei Aung Naing - Executive Assistant (MT).pdf'),
('Shwe Yee Phoo Hr', 'shweyeephoo25@gmail.com', '09772655043', 'Sales & Marketing', 'git, excel, photoshop', 'active', 'CV Lead Tracker', 'CV: Shwe Yee Phoo - HR Assistant (MT).pdf'),
('Soe Lwin Lwin Qa', NULL, NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Soe Lwin Lwin - QA.pdf'),
('Myo Pa Pa Hr', 'y99@gmail.com', '09758192972', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Myo Pa Pa - HR Assistant (MT).pdf'),
('Thet Thet Htun Hla', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Thet Thet Htun Hla - Sales Manager (MT).pdf'),
('Ndar Wai Hr', 'waisandar514@gmail.com', '09696290895', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Sandar Wai - HR Assistant (MT).pdf'),
('Aung Kaung Myat It', 'kaungmyata938@gmail.com', '959769506195', 'Engineering', 'azure', 'active', 'CV Lead Tracker', 'CV: Aung Kaung Myat - IT Assistant (MT_.pdf'),
('Pyae Sone Aung Wholele', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Pyae Sone Aung - Wholesale Supervisor (MT).pdf'),
('Htet Min Naing', 'Zayanlay35th@gmail.com', '959692688940', 'Management', 'git, project management', 'active', 'CV Lead Tracker', 'CV: Htet Min Naing - Sales Operator (MT).pdf'),
('Yu Nandar Tun Procurment', 'myhomeaff@gmail.com', '959793660343', 'Operations', 'communication', 'active', 'CV Lead Tracker', 'CV: Yu Nandar Tun - Procurment (MT0.pdf'),
('Thin Thin Myat', '2024@gmail.com', '09254874694', 'Management', 'leadership', 'active', 'CV Lead Tracker', 'CV: Thin Thin Myat - Finance Supervisor (MT).pdf'),
('Mesi University', NULL, '09665984655', 'Sales & Marketing', 'git, excel, communication, project management, analytical', 'active', 'CV Lead Tracker', 'CV: Nyi Nyi Lwin - Digital Marketing Executive (MT).pdf'),
('Thiha Zaw', 'thiha.zaw5@gmail.com', '+959264704751', 'Management', 'aws', 'active', 'CV Lead Tracker', 'CV: Thiha Zaw -Server Operation Engineer (MT).pdf'),
('U Thaung Dan Driver', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: U THAUNG DAN - Driver (MT).pdf'),
('Chan Mya Mya Hnin', NULL, NULL, 'Sales & Marketing', 'communication', 'active', 'CV Lead Tracker', 'CV: Chan Mya Mya_Hnin_ Curriculum Vitae .pdf'),
('Kaung Set Htoo', 'kaungsethtoo00@gmail.com', '09952746538', 'Sales & Marketing', 'communication', 'active', 'CV Lead Tracker', 'CV: kaung set htoo_ (MT).pdf'),
('Chan May Htun Cashier', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Chan May Htun - Cashier (MT).pdf'),
('Personal Information Profile', 'maytzin27@gmail.com', '959883555915', 'HR & Admin', 'excel, photoshop, illustrator', 'active', 'CV Lead Tracker', 'CV: May Tha Zin Aung - HR Assistant (MT).pdf'),
('Thet Naing Oo Noc', NULL, NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Thet Naing Oo - NOC Engineer(MT).pdf'),
('Thazin Nwe Hr', NULL, '09459227928', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Thazin Nwe - HR Assistant (MT).pdf'),
('Jun 2018- Dec 2019', 'myokyawhtun28@gmail.comWork', NULL, 'Sales & Marketing', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Myo-Kyaw-Htun- Social Media (MT).pdf'),
('Linn Ei Phyu Hr', 'lineiphyu9@gmail.com', '959740956625', 'HR & Admin', 'excel, powerpoint, communication, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: Linn Ei Phyu - HR Assistant (MT).pdf'),
('Educational Qualifications', 'shweyeebaamyint@gmail.com', '09262383826', 'Engineering', 'problem solving', 'active', 'CV Lead Tracker', 'CV: Shwe Yee Ba Myint - NOC (MT).pdf'),
('System Engineer', 'htetwailinn96@gmail.com', '09255113461', 'Management', 'java, sql, aws, azure, git', 'active', 'CV Lead Tracker', 'CV: Htet Wai Linn - System Engineer (MT).pdf'),
('Office Cashier', 'nwayylyy@gmail.com', '09766597304', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Office Cashier (MT).pdf'),
('Nyan Lin Htun', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Nyan Lin Htun - Senior Sales Staff (MT).pdf'),
('Carrer History', 'tunnayla01@gmail.com', '959955077739', 'Management', 'express, sql', 'active', 'CV Lead Tracker', 'CV: Tun Nay La - IT Officer (MT).pdf'),
('Race - Myanma R', NULL, '09670347186', 'General/Other', 'communication', 'active', 'CV Lead Tracker', 'CV: Aung Khant Zin - Data Collector (Meikhtila)MT.pdf'),
('Educationkaung Khant Kyaw', 'kaungkhantkyaw43@gmail.com', '959425013537', 'Engineering', 'communication', 'active', 'CV Lead Tracker', 'CV: Kaung_Khant_Kyaw- Network Engineer (MT).pdf'),
('Hkun Naw Network Engineer', 'hkunnaw2006@gmail.com', '09253165311', 'Engineering', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Hkun Naw - Network Engineer (MT).pdf'),
('Pann Phyu Export', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Pann Phyu - Export & Import (NPT) MT.pdf'),
('Tin Nu Htwe Hr', 'tinnuhtwe14@gmail.com', '959946989799', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Tin Nu Htwe - HR Manager (MT).pdf'),
('Khin Yadanar Toe Toe', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Khin Yadanar Toe Toe Zaw - QA (MT).pdf'),
('Tmhr Intern', 'thinmyat569@gmail.com', '09798198850', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: TMMT - HR Intern (MT).pdf'),
('Phyu Phyu Thant Lps', NULL, '09943231052', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Phyu Phyu Thant - LPS (MT).pdf'),
('Min Khant Zaw', 'phyowathone.life@gmail.com', '09786642491', 'Engineering', 'python', 'active', 'CV Lead Tracker', 'CV: Min Khant Zaw - Website & Odoo (MT).pdf'),
('Ms. Eaint Eaint Khin', 'eainteaintkhin@gmail.com', NULL, 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Eaint Eaint Khin - HR & Admin (MT).pdf'),
('Aung Thurain Htun', 'aungthurainhtun399@gmail.com', '09405627940', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Aung Thurain Htun (Senior Site Engineer)(3)_1fba6d46-07c9-4694-9d9f-7eb10cfacf58.pdf'),
('Su Lai Nwe Hr', 'sulainwe44@gmail.com', '09687758024', 'Customer Service', 'git, excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Su Lai Nwe - HR Assistant (MT).pdf'),
('Than Hlaing Win It', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Than Hlaing Win - IT Technician (MT).pdf'),
('Zayar Tun Factory', 'zyar86729@gmail.com', '959795669563', 'Management', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Zayar Tun - Factory Manager (MLM).pdf'),
('Thiha Ko', NULL, '09449795491', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Thiha Ko - Sales (MT).pdf'),
('Ye Min Than', 'yemt.mm@outlook.com', '09448949889', 'Management', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Ye Min Than - Senior Network Engineer (MT).pdf'),
('May Thu Oo Hr', 'ythu240@gmail.com', '9406567473', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: May Thu Oo - HR Assistant (HTY)MT.pdf'),
('Wai Yan Lin Zaw', 'wylz5134@gmail.com', '09965590747', 'Engineering', 'java, javascript, mysql, sql, photoshop, project management', 'active', 'CV Lead Tracker', 'CV: Wai Yan Lin Zaw - IT Officer (MT).pdf'),
('Ah Lain Mar Htoo', 'ahlainmar.job44@gmail.com', '959790813937', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Ma Ah Lain Mar Htoo - HR Assistant (MT).pdf'),
('Nyan Phyo Htet', 'nyanphyohtet563@gmail.com', '09980991464', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Nyan Phyo Htet - NOC Engineer (MT).pdf'),
('Personal Information', NULL, '09953551687', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Ma Htet Htet Aung - HR Assistant (MT).pdf'),
('South Okkala,yangon.', NULL, NULL, 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Htut Aung Wai - Cloud NOC Engineer (MT).pdf'),
('Race Burmese', NULL, '09252524568', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Thet Wai (accountant , sales & marketing)MT.pdf'),
('Ung Oo Hlaing', 'saungoohlaing7@gmail.com', '0943177862', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Saung Oo Hlaing - Sales Admin (MT).pdf'),
('Ei Ei Aung Drafter', 'eieiaung.ag2019@gmail.com', NULL, 'Engineering', 'photoshop', 'active', 'CV Lead Tracker', 'CV: Ei_ Ei_ Aung - Drafter (MT).pdf'),
('Win Pa Pa Aung', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Win Pa Pa Aung - HR Assistant (MT).pdf'),
('Yan Shin Aung Lps', 'yanshinaungatom3344@gmail.com', '09794979192', 'Sales & Marketing', 'git', 'active', 'CV Lead Tracker', 'CV: Yan Shin Aung - LPS (MT).pdf'),
('Aye Thiri Thu', 'ayethirithu0804@gmail.com', '09771706731', 'Operations', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Aye Thiri Thu - English Translator (MT).pdf'),
('Phyoe Thet Aung Product', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Phyoe Thet Aung - Product Marketing Manager (MT).pdf'),
('Chan Myae Zaw Driver', NULL, '09981112843', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Chan Myae Zaw - Driver (MT).pdf'),
('Yan Paing Oo Noc', 'yanpaingo828@gmail.com', '09975054601', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Yan Paing Oo - NOC (MT).pdf'),
('Mya Min Soe Cashier', 'myaminsoe0@gmail.com', '09426019113', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Mya Min Soe - Cashier (Thanlyin)MT.pdf'),
('Myintzu Merchandiser', 'stz1811958799@gmail.com', '09780681946', 'HR & Admin', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: MyintZu - Merchandiser (MT).pdf'),
('Khaing Wah Wah', 'khaingwarwar3546@gmail.com', '09761541415', 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Khaing Wah Wah - Sales Admin (MT)1.pdf'),
('Yangon, Myanmar.', 'mielay1991@gmail.com', '09777333825', 'Management', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Myo Yee Yee Tun - Site E (MT.pdf'),
('Htet Myat Naing', 'htetmyatnai@gmail.comC', '09965447583', 'Management', 'leadership, communication, project management, analytical', 'active', 'CV Lead Tracker', 'CV: Htet Myat Naing (IT application).pdf'),
('Nay Lin Oak Media', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Nay Lin Oak - Media Production (MT).pdf'),
('Aung Myat Min Marketing', 'aungmin3131996@gmail.com', '09785215319', 'Sales & Marketing', 'git', 'active', 'CV Lead Tracker', 'CV: Aung Myat Min - Marketing Executive (MT).pdf'),
('Educationhein Htet Soe', 'heinhtet.ss734@gmail.com', '959777341026', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Hein Htet Soe - IT Technician (MT).pdf'),
('Myo Min Thu Hr', 'myominthu208@gmail.com', '09759385677', 'HR & Admin', 'express, leadership, problem solving', 'active', 'CV Lead Tracker', 'CV: Myo Min Thu - HR & Admin Manager (MT).pdf'),
('Zin Wai Htet Hr', 'zinwai379@gmail.com', '09452744344', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Zin Wai Htet - HR Assistant (MT).pdf'),
('Chit Suu Htay', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Chit Suu Htay - Executive Assistant (MT).pdf'),
('Pyae Sone Aye', 'pyaesoneaye660@gmail.com', '09798000513', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Pyae Sone Aye - Sales Operation Supervisor (MT).pdf'),
('Ei Pan Phyu', 'mmtph@gmail.com', '09422718055', 'HR & Admin', 'leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Ei Pan Phyu - Suitable Sales (MT).pdf'),
('Yhk Documentation', 'yehtetkyaw611999@gmail.com', '9793365384', 'Operations', 'excel', 'active', 'CV Lead Tracker', 'CV: YHK - Export,Import Documentation (MT).pdf'),
('Noo Payroll', 'nnoozinkyawwinn@gmail.com', '09984217308', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Noo_s+ - payroll assistant (MT).pdf'),
('Thet Hnin Zin Office', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Thet Hnin Zin - Office Staff (MT).pdf'),
('Regional Manager', 'myogyi235@gmail.com', NULL, 'Sales & Marketing', 'leadership', 'active', 'CV Lead Tracker', 'CV: Myo Thu - Portfolio Financial Manager (MT) (1).pdf'),
('Curriculum Vitae', 'myo.mar27@gmail.com', NULL, 'Engineering', 'communication', 'active', 'CV Lead Tracker', 'CV: Mr.Nyi Phone myat - Maintainacne Engineer (MT).pdf'),
('La Min Ngwe', 'lmnngwe@gmail.com', '09420089131', 'Engineering', 'project management', 'active', 'CV Lead Tracker', 'CV: La Min Ngwe - Site Engineer (MT).pdf'),
('San Min Oo', NULL, '09967894443', 'Engineering', 'leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: San-Min-Oo-Site-Engineer (MT).pdf'),
('Race - Myanmar', NULL, '09779072008', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Hlaing Phyo Wai - Driver (MT) merge.pdf'),
('Ynp Les Supervisor', 'yannyeinphyo1996@gmail.com', '09765210621', 'Management', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: YNP Sales Supervisor (MT).pdf'),
('Hnin Wai Aung Portfolio', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Hnin Wai Aung - Portfolio Manager (MT).pdf'),
('Min Chit Thu Qa', 'mthu22938@gmail.com', '959764470302', 'General/Other', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: CV - Min Chit Thu-QA (MT).pdf'),
('Hnin Oo Wai Cashier', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Hnin Oo Wai - Cashier (MT).pdf'),
('Lin Let Thaw Tar', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Lin Let Thaw Tar_-Sales Admin (MT).pdf'),
('Aye Thiri Aung', 'maysittthwin9@gmail.com', '959898326392', 'Sales & Marketing', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: Aye Thiri Aung - Senior Financial Advisor (MT).pdf'),
('Phyo Hay Man Cho', 'Phyocho1986@gmail.com', '09254451809', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Phyo Hay Man Cho - Sales Admin (MT).pdf'),
('Hnin Wutyi Hr Intern', 'hninwittyiwin1994@gmail.com', '09799318638', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Hnin Wutyi - HR Intern (MT).pdf'),
('Nanda Hr', 'fsmnanda73@gmail.com', '09250545386', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Nanda HR Manager (MT).pdf'),
('Su Theingi Naing', 'sutheinginaing1122@gmail.com', '09797717442', 'HR & Admin', 'java, communication', 'active', 'CV Lead Tracker', 'CV: Su_Theingi_Naing- Software Analyst (MT).pdf'),
('Khin Aye Chan Wai', 'khinayechanwai15@gmail.com', NULL, 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Khin Aye Chan Wai - Executive Assistant (MT).pdf'),
('Mr. Nyan Min Htet', 'nyanminhtet.nmh@outlook.com', '09421054091', 'HR & Admin', 'aws, excel', 'active', 'CV Lead Tracker', 'CV: Nyan Min Htet - HR, Admin (MT).pdf'),
('Thiri+htet+ko+sales Manager (mt)', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Thiri+Htet+Ko+Sales Manager (MT).pdf'),
('Pseecurrsitoy Nal Data', 'aungmyatthu.hse@gmail.com', NULL, 'Management', 'aws, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Aung Myat Thu - HSE Officer (MT).pdf'),
('Mr Si Thu Soe', 'sithusoe952546@gmail.com', NULL, 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Si Thu Soe - M & E (MT).pdf'),
('Arkar Kyaw Media Production', 'arkarkyawak54@gmail.com', NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Arkar Kyaw - Media Production (MT).pdf'),
('Thiha Aung', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Thiha Aung - Sales Promoter (MT).pdf'),
('Lwin Hr', 'lwinlwinhtike67@gmail.com', '09885478720', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Lwin CV HR Executive - MT.pdf'),
('Kaung Zaw Graphic Designer', NULL, NULL, 'Design', NULL, 'active', 'CV Lead Tracker', 'CV: Kaung Zaw - Graphic Designer (MT).pdf'),
('Okkalapa Tsp., Yangon.', 'phyuphyukhai92@gmail.com', NULL, 'Engineering', 'java, react, angular, mysql, sql, docker, excel, communication', 'active', 'CV Lead Tracker', 'CV: Ma Phyu Phyu Khai - IT Techanican (MT).pdf'),
('Hnin Marlar Aung', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Hnin Marlar Aung - Senior Executive Pathein.pdf'),
('Hnin Hnin Yu Wai', 'hninhninyuwai37@gmail.com', '09961451274', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Hnin Hnin Yu Wai - HR Executive (MT).pdf'),
('Aung Naing Tun Graphic', NULL, NULL, 'Design', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Naing Tun - Graphic Designer (MT).pdf'),
('Ma Lwin Lwin Khaing', 'nanglwinlwin69@gmail.com', '9756592309', 'General/Other', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Lwin Lwin Khaing - IT Officer (MT).pdf'),
('Hnin Aye Zin', 'hninayezin.ms@gmail.com', '9421064392', 'Management', 'excel, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Hnin Aye Zin - Customer Care Manager (MT).pdf'),
('Su Lei Nandar', 'sallysulei91@gmail.com', '09765430653', 'Management', 'communication, project management, problem solving', 'active', 'CV Lead Tracker', 'CV: Su Lei Nandar - Head of Marketing (MT).pdf'),
('Nway Ingyin Hlaing', 'nwayingyin94@gmail.com', '9458111765', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Nway Ingyin Hlaing - HR Execuitve (MT).pdf'),
('Htet Shoon Lae S', 'htetshonnlaie2252@gmail.comPhone', '09777573363', 'HR & Admin', 'excel, communication, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: Htet Shoon Lae_s- English Translator (MT).pdf'),
('Aung Khant Minn Payroll', 'aungkhantminn2004@gmail.com', '09420274520', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Aung Khant Minn - Payroll Executive (MT).pdf'),
('Thwin Zaw Noc', NULL, '09760950080', 'Engineering', 'problem solving', 'active', 'CV Lead Tracker', 'CV: Thwin Zaw - NOC (MT).pdf'),
('Than Naing Oo', NULL, '959957952281', 'Management', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Than Naing Oo - Sales & Marketing Executive (MT).pdf'),
('Thwe Thwe Aye Cashier', 'thwethweaye965@gmail.com', NULL, 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Thwe Thwe Aye - Cashier (NPT)MT.pdf'),
('Mo Mo Ko Merchandiser', 'Addressmomopyaewon7@gmail.com', NULL, 'Engineering', 'express, excel', 'active', 'CV Lead Tracker', 'CV: Mo Mo Ko - Merchandiser (MT).pdf'),
('Thida Swe', 'thidarswe83@gmail.com', '09976895547', 'Management', 'python, java, javascript, react, vue, aws, git, excel', 'active', 'CV Lead Tracker', 'CV: Thida Swe - Website & Odoo (MT) (1).pdf'),
('Yin Thu', 'yinthu.1001@gmail.com', '09697117899', 'Management', 'communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Yin Thu - Lead System Engineer (MT).pdf'),
('Race - Myanma R', NULL, '09791490922', 'Sales & Marketing', 'communication', 'active', 'CV Lead Tracker', 'CV: Hnin Thet Hlyar Oo - Office Staff (MLM)MT.pdf'),
('Min Thu Tin', NULL, '09970963406', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Min Thu Tin - Sales Engineer (MT).pdf'),
('Htoo Naing Kyaw Customer', NULL, NULL, 'Customer Service', NULL, 'active', 'CV Lead Tracker', 'CV: Htoo Naing Kyaw - Customer Service (MT).pdf'),
('Zin Mar Wai', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Zin Mar Wai - Sales (MDY) MT 1.pdf'),
('Akks Maintainance Techanican', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Akks - Maintainance Techanican (MT).pdf'),
('Daw Pyae Phyo', 'shinthant29012@gmail.com', '09450029012', 'HR & Admin', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Pyae Phyo - HR & Admin Executive(MT).pdf'),
('Contact Me', 'hsumyatthar96@gmail.com', '09751601996', 'Management', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Hsu Myat Thar - Non Buying (MT).pdf'),
('Htoon Htoon W', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Htoon Htoon Saw - Sales (MDY)MT.pdf'),
('Education Background', 'waiyanminoo889@gmail.com', NULL, 'Customer Service', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Wai Yan Min OO - QA (Hmwbi)MT.pdf'),
('Thidar Aung', NULL, '09268686157', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Thidar Aung - Sales & Cashier (MT).pdf'),
('Kay Zar Maw Bank', 'thantzin.tun@ananda.com.mm', '959799990926', 'General/Other', 'communication', 'active', 'CV Lead Tracker', 'CV: Kay Zar Maw - Bank Advisor (MDY).pdf'),
('Hnin Pwint Oo', NULL, '09423009106', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Hnin_Pwint_Oo - Sales Manager (MT).pdf'),
('Khin Thet Oo', 'Khinthetoo871@gmail.com', '09262486917', 'Management', 'excel, photoshop', 'active', 'CV Lead Tracker', 'CV: Khin Thet Oo  - HR Executive Update (MT).pdf'),
('May May Than', 'maymaythan2021@gmail.com', '959250529167', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: May May Than (CV Form) - LinkedIn (MT).pdf'),
('Shein Htet Zaw Hr', NULL, '09783378315', 'HR & Admin', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: Shein Htet Zaw - HR Executive (MT).pdf'),
('Mya Yamin Htun', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Mya-Yamin-Htun-Sales (MT).pdf'),
('Yu Yu Aung', NULL, '09456220370', 'Sales & Marketing', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Yu Yu Aung - Customer Service (MT).pdf'),
('Myat Phone Thit', 'mr.myatphone.mm@gmail.com', '9978120174', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Myat Phone Thit - Site Engineer (MT).pdf'),
('Tun Yin Win', 'tunyinwin89@gmail.com', '959256192293', 'Management', 'git, excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Tun Yin Win - Sales & Marketing Manager (Electronic)MT.pdf'),
('Than Tole Maung Cashier', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Than Tole Maung - Cashier (NPT)MT.pdf'),
('Tay Zar Min Marketing', 'kokhant00201500@gmail.com', '0943184752', 'Sales & Marketing', 'git', 'active', 'CV Lead Tracker', 'CV: Tay Zar Min - Marketing Manager (MT).pdf'),
('Min Myanmar It Support', 'minmyanmar2010@gmail.com', NULL, 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Min Myanmar - IT Support (MT).pdf'),
('Wunna Aung Data Entry', 'wunna3129@gmail.com', '09981610027', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Wunna Aung - Data Entry (MT).pdf'),
('Si/high Class Computer', NULL, NULL, 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Ei Mon Win - Call Center (MT).pdf'),
('Zweminhtet Agency Relationship', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: ZweMinHtet - Agency Relationship Manager (MT).pdf'),
('Eaint Kyiphyu', NULL, NULL, 'Sales & Marketing', 'git, photoshop, illustrator, communication', 'active', 'CV Lead Tracker', 'CV: Eaint Kyi Phyu - Graphic Designer (MT).pdf'),
('Khaing Khaing Zin Hr', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Khaing Khaing Zin - HR & Admin (MT).pdf'),
('Ei Thet Mon Con', 'eithetmon.mm@gmail.com', '959450089913', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Ei Thet Mon - Con Accountant (MT).pdf'),
('Tyi Kyi Noc Engineer', NULL, '09783548002', 'Engineering', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Tyi Kyi - NOC Engineer (MT).pdf'),
('Aung Pyae Thu Marketing', 'aungpyaethu.zero.one@gmail.com', '9251111342', 'Sales & Marketing', 'communication', 'active', 'CV Lead Tracker', 'CV: Aung Pyae Thu - Marketing Executive (MT).pdf'),
('Wint Wah Oo Export', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Wint Wah Oo - Export & Import Coordinator (MT).pdf'),
('Curriculum Vitae', 'yatil6550@gmail.com', '09421122602', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Tin Zar Aung  - Admin & HR (MT).pdf'),
('Yond Me Me Soe', 'yondmemesoe1995@gmail.com', '09450037799', 'Management', 'git, excel, communication', 'active', 'CV Lead Tracker', 'CV: Yond Me Me Soe - Sales Operation Supervisor(MT).pdf'),
('Su Myat Nandar Naing', 'sumyatnandarnaing@gmail.com', '95942221476', 'Engineering', 'photoshop, illustrator, communication', 'active', 'CV Lead Tracker', 'CV: SU MYAT NANDAR NAING -Interior Designer -(M)T.pdf'),
('Aye Zin', 'ayezinmarkyaw66@gmail.comEnglish', '09453875267', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Aye Zar Mar -HR & Admin Assistant (MT).pdf'),
('Soe Thiha Oo Qa', 'soethiha4793@gmail.com', NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Soe Thiha Oo - QA Manager.pdf'),
('Myo Theingi Kyaw Relationship', 'gigi571998@gmail.comContactMyo', '+959459172006', 'Management', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Myo Theingi Kyaw - Relationship Manager (MT).pdf'),
('Su Su San', 'sususan12281989@gmail.com', NULL, 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Su+Su+San+Key Account Executive (MT).pdf'),
('Myo Ko Ko Oo', 'okokooo2050@gmail.com', '09751510406', 'Management', 'leadership', 'active', 'CV Lead Tracker', 'CV: Myo Ko Ko Oo - Medical sales (MT).pdf'),
('Hla Theingi Aung', NULL, '09451971914', 'Management', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Hla Theingi Aung - Customer Service Executive (MT).pdf'),
('Chu Chu Thwal Hr', NULL, '959982251110', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Chu Chu Thwal - HR Assistant (MT).pdf'),
('U Than Myint Naing', 'htetthinzarlynn22@gmail.com', '09790281451', 'HR & Admin', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Htet Thinzar Lynn - Recruitment Coordinator (MT).pdf'),
('Aye Aye Thwe Cashier', NULL, '09971070641', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Aye Aye Thwe - Cashier (MT).pdf'),
('May Zin Paing', 'Mayzinpaing3099@gmail.com', '09951105799', 'Management', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: May Zin Paing - Sales Executive (MT).pdf'),
('Professional Experience', 'thanttoeaung94@gmail.com', NULL, 'Management', 'excel, powerpoint, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Thant Toe Aung - Network Engineer (MT).pdf'),
('Chityaungchi_ Sales (mdy)mt', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: ChitYaungChi_ Sales (MDY)MT.pdf'),
('Kyaw Min Oo', '8@gmail.com', '09975449372', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Kyaw Min Oo - Procurement and Shipping manager (MT).pdf'),
('Curriculum Vita E', NULL, '09794303673', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Hein Htet Oo - Data Entry (MT).pdf'),
('Nora Angel', NULL, '09420234947', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Nora Angel (Sales Manager) MT.pdf'),
('Khinse Swe Latt', NULL, NULL, 'Management', 'excel, leadership, communication, project management, problem solving', 'active', 'CV Lead Tracker', 'CV: Khinse Swe Latt - Finance Manager (MT).pdf'),
('Shwe Hr', 'shwethinyanantthein@gmail.com', '09977807884', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Shwe - HR Executive (MT).pdf'),
('Yamin Hlaing', 'yaminhlaingymh95@gmail.com', '09458868980', 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Yamin Hlaing - Admin & HR (MT).pdf'),
('Lwin Mar Myint', 'maylamin2@gmail.com', '09750966455', 'Sales & Marketing', 'git, photoshop, illustrator, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Lwin Mar Myint - Plaza Leasing (MT).pdf'),
('Yu Nandar Htun Cashier', 'yunandarhtun.02@gmail.com', '959458041122', 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Yu Nandar Htun - Cashier TGI.pdf'),
('Contacteducationabout Me', 'swezinphyomin1@gmail.com', '9780223172', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Swe Zin Phyo Min - Customer Service (MT- MNwe).pdf'),
('Thinzar Win Korean Translator', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Thinzar Win - Korean Translator (MT).pdf'),
('Julylapyaewon Cashier', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: JULYLAPYAEWON - Cashier (MT).pdf'),
('Botatung Tsp, Yangon', 'eihninphyu.theresa@gmail.com', '09442591117', 'Management', 'excel, powerpoint, leadership, communication, analytical', 'active', 'CV Lead Tracker', 'CV: EiHninPhyu - Sales & Marketing Manager (MT).pdf'),
('Hnin Wutt Yi Aye', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Hnin Wutt Yi Aye - HR  Assistant (MT).pdf'),
('Banyar Aung Corporate Les', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Banyar Aung _ Corporate Sales (MT).pdf'),
('Hnin Ndar Hlaing', 'g23@gmail.com', '959799929983', 'Engineering', 'excel, powerpoint, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Hnin Sandar Hlaing (BIM Modeller)MT.pdf'),
('Tin Yu Wai', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Tin Yu Wai - Internal Auditor (MT)1.pdf'),
('Poe Noe Noe Naing', NULL, '09263359877', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Poe Noe Noe Naing - Senior Financial A (MT).pdf'),
('Htet Shwe Yi Win', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Htet Shwe Yi WIn - Cusotmer Service (MT).pdf'),
('May Zin Oo', 'oomayzin77@gmail.com', '09753742878', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: May Zin Oo - Junior Recruiter (MT).pdf'),
('Work Experience', 'theintshweyee444@gmail.com', '09775263725', 'Sales & Marketing', 'git, excel, powerpoint, project management, problem solving', 'active', 'CV Lead Tracker', 'CV: Theint Shwe Yee -Corporate Sales Executive (MT).pdf'),
('Nyan Lynn Htun Hr', 'nyanlynntun2018@gmail.com', '09250578433', 'Management', 'aws', 'active', 'CV Lead Tracker', 'CV: Nyan Lynn Htun - HR Manager (MT).pdf'),
('Soe Wutyi Aung', 'soewutyiaung95@gmail.com', '09796060046', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Soe Wutyi Aung - HR Assistant (Dagon Seikkan)MT.pdf'),
('Hein Min English Translator', 'khoran.handsome@gmail.com', '09254056524', 'Sales & Marketing', 'git, excel, communication', 'active', 'CV Lead Tracker', 'CV: Hein_Min_English_Translator (MT).pdf'),
('Aung Pyae Phyo', 'ap7.aungpyaephyo@gmail.com', '09792463316', 'Engineering', 'git, excel, powerpoint, photoshop, illustrator, communication', 'active', 'CV Lead Tracker', 'CV: Aung Pyae Phyo - Executive Position (KBZ Life Insurance).pdf'),
('Kay Zin Thaw', 'thaw4195@gmail.com', '09959380072', 'Management', 'excel, powerpoint, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Kay Zin Thaw - Senior Sales Manager (Banca)MT.pdf'),
('May Pann Khaing Cashier', NULL, '09953733165', 'General/Other', 'communication', 'active', 'CV Lead Tracker', 'CV: May-Pann-Khaing - Cashier (MT).pdf'),
('Soe Paing Digital Marketing', NULL, NULL, 'Sales & Marketing', 'git', 'active', 'CV Lead Tracker', 'CV: Soe Paing-Digital Marketing Executive (MT).pdf'),
('Yan Lin Aung Meida', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Yan Lin Aung - Meida Production (MT).pdf'),
('Capital Diamond Star Group.', NULL, '09940794543', 'Engineering', 'express', 'active', 'CV Lead Tracker', 'CV: Myo Ko Ko - M & E Supervisor (MT).pdf'),
('Phoo Pwint Kabyar Receptionist', 'phoop2435@gmail.com', '09671861942', 'Operations', NULL, 'active', 'CV Lead Tracker', 'CV: Phoo Pwint Kabyar_Receptionist (MT).pdf'),
('Htet Wai Linn Data', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Htet Wai Linn - Data Collector  (HTY)MT.pdf'),
('Personal Information', 'khunhtunwai92@gmail.com', '959699148877', 'Engineering', 'python', 'active', 'CV Lead Tracker', 'CV: Khun Htun Wai - NOC Engineer (MT).pdf'),
('Hnin Kywat Khaing Medical', NULL, '959796259953', 'Management', 'git, project management', 'active', 'CV Lead Tracker', 'CV: Hnin Kywat Khaing - Medical Rep(MT).pdf'),
('Myat Noe Chal', NULL, '09976773783', 'Engineering', 'excel, project management', 'active', 'CV Lead Tracker', 'CV: Myat Noe Chal - Junior Engineer (MT).pdf'),
('Nyein Chan Aung', 'awnghtwanlunn@gmail.com', '09442778012', 'HR & Admin', 'excel, powerpoint, leadership', 'active', 'CV Lead Tracker', 'CV: Nyeing_Chan_Aung_- Pay roll assistant (MT).pdf'),
('Hr Manager', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: HR Manager.pdf'),
('Wai Wai Hlaing', NULL, '09973661270', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Wai Wai Hlaing - Sales (TGI) MT.pdf'),
('Thazin Aung Hr', 'thazina222@gmail.com', NULL, 'HR & Admin', 'excel, leadership, communication, project management', 'active', 'CV Lead Tracker', 'CV: Thazin_Aung - HR Assistant (MT).pdf'),
('Su Po Po Aung', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Su Po Po Aung - Cusotmer Service (MT).pdf'),
('Su Thiri', 'suthiriswe72@gmail.com', '09674164405', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Su Thiri - Junior Auditor (MT).pdf'),
('Nwet Nwet Win Hr', NULL, '09409108946', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Nwet Nwet Win - HR Manager (MT).pdf'),
('Professional Summary', 'winminnanswe@gmail.com', NULL, 'Engineering', 'mysql, sql, excel, photoshop, communication, project management, analytical', 'active', 'CV Lead Tracker', 'CV: Win Min Htike - Lead System Engineer (MT).pdf'),
('Arkar Lin', 'akl.arkarlinn@gmail.com', '9967883362', 'Management', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Arkar Lin - Sales Team Lead (MT).pdf'),
('Htet Shine Corporate Les', 'htetshine5394@gmail.com', NULL, 'Sales & Marketing', 'git, communication', 'active', 'CV Lead Tracker', 'CV: Htet Shine-Corporate Sales Executive (MT).pdf'),
('May Thazin Graphic Designer', NULL, NULL, 'Design', NULL, 'active', 'CV Lead Tracker', 'CV: May Thazin - Graphic Designer (MDY)MT.pdf'),
('Su Thet Naing Cashier', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Su Thet Naing - Cashier (MT).pdf'),
('Nuam Sian Huai Recruitment', 'yp@gmail.com', '09769302543', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Nuam Sian Huai - Recruitment Executive (MT).pdf'),
('Electrical Power', 'kyawmyohan250@gmail.com', '959954653315', 'Management', 'aws', 'active', 'CV Lead Tracker', 'CV: Kyaw Myo Han - IT Support (MT).pdf'),
('Hnin Lai Naing Hr', 'hninlainaing30@email.com', '09977855131', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Hnin Lai Naing - HR Assistant (MT).pdf'),
('Ma Aye Pyae Sone', 'ayejuly928@gmail.com', '09972555966', 'Customer Service', 'excel', 'active', 'CV Lead Tracker', 'CV: Aye Pyae Sone - Customer Service (MT).pdf'),
('Hein Sett', 'heinsett002@gmail.com', '09755429663', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Hein Sett - Sales (MDY)MT.pdf'),
('Aye Mya Naing Secretary', 'ms.ayemyanaing@gmail.com', NULL, 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Aye Mya Naing - Secretary (MT).pdf');