-- ============================================
-- CV Lead Tracker - Batch 2 of 5
-- Leads 501 to 1000
-- ============================================

INSERT INTO leads (name, email, phone, current_position, skills, status, source, notes) VALUES
('Wutyi Htwe', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Wutyi Htwe - Manager FA (MT).pdf'),
('Azyo Noc', NULL, NULL, 'Engineering', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: AZYO -NOC Engineer(MT).pdf'),
('Aplying Position', 'whiterose.lm15@gmail.com', '09451727115', 'HR & Admin', 'excel, leadership, communication, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: lwin lwin mar - Admin & HR Manager (MT).pdf'),
('Shine One Naung Warehouse', NULL, NULL, 'Management', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Shine One Naung - Warehouse Manager (MT).pdf'),
('Current Information', 'aungaungla.1990@gmail.com', '0996976776', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Shu Aung - Modern Trade Sales (MT).pdf'),
('Tyi Kyi Noc', NULL, '09783548002', 'Engineering', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Tyi Kyi - NOC (MT).pdf'),
('Translator Linkedin', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Pau+It+Khang - Translator (MT) LInkedIn.pdf'),
('Hlaing Thazin Oo Hr', 'hthazin292@gmail.com', '09458324878', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Hlaing Thazin Oo - HR Assistant (MT_ - Copy.pdf'),
('Digital Marketer', 'ajkyawhan@gmail.com', '09400153859', 'Sales & Marketing', 'git, communication', 'active', 'CV Lead Tracker', 'CV: Digital Marketer (MT).pdf'),
('Tin Htwe Aung Custom', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Tin Htwe Aung - Custom Clearance Agent (MT).pdf'),
('It Assistant', NULL, NULL, 'Engineering', 'leadership, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Htet Wai Yan Oo - NOC (MT).pdf'),
('Personal Details', 'ayeayekhine.1993@gmail.com', '09977635766', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Curriculum Vitae ( Aye Aye Khaing )- Sales Admi (MT).pdf'),
('Race - Myanmar', 'wintzarchinaing72@gmail.com', '09943497979', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Wint Zar Chi Naing - Life Planning Supervisor (MT).pdf'),
('U Tun Aung', 'yephyohan@gmail.com', NULL, 'Engineering', 'communication', 'active', 'CV Lead Tracker', 'CV: Ye Phyo Han - IT Assistant (MT) (1).pdf'),
('Phyo Moh Moh Shain', 'pmmshain27@gmail.com', '95941004718', 'Management', 'git, communication', 'active', 'CV Lead Tracker', 'CV: Phyo Moh Moh Shain - Senior Marchandising (MT).pdf'),
('Ar Kar Phyo Drafter', 'williamarkarphyo@gmail.com', '9250795153', 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Ar Kar Phyo - Drafter (MT).pdf'),
('May Thandar Htwe Hr', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: May Thandar Htwe - HR Executive (MT).pdf'),
('Khaing Zar Thwe Qa', 'khinezarthwe895@gmail.com', '09250070038', 'HR & Admin', 'analytical', 'active', 'CV Lead Tracker', 'CV: Khaing Zar Thwe - QA (MT).pdf'),
('Arkar Lin', 'akl.arkarlinn@gmail.com', '9967883362', 'Management', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Arkar Lin - Sales Team Lead (YGN) MT.pdf'),
('Sein Lae Nway Enghlish', 'seinnnway19td@gmail.com', '09960333898', 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Sein Lae Nway - Enghlish Translator (MT).pdf'),
('Export Import Operation', 'tinhtunlinn4@gmail.com', '09250028682', 'Operations', NULL, 'active', 'CV Lead Tracker', 'CV: Export , Import Operation (MT).pdf'),
('Htet Aung Hlaing Digital', NULL, NULL, 'Sales & Marketing', 'git', 'active', 'CV Lead Tracker', 'CV: Htet Aung Hlaing - Digital Marketing (MT).pdf'),
('Zin Aye Thant', 'ethant438@gmail.com', '09771852424', 'HR & Admin', 'communication', 'active', 'CV Lead Tracker', 'CV: Zin Aye Thant - Sales Admin (MT).pdf'),
('Personal Informaɵon', 'nwayaung5562@gmail.com', '959750985970', 'General/Other', 'powerpoint', 'active', 'CV Lead Tracker', 'CV: Nway Nway Aung - Koran Translator (MDY)MT.pdf'),
('Nationality ‐ Rakhine', NULL, NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: May Nwe Nwe Htun - Site Engineer (MT).pdf'),
('Win Htike It Supervisor', 'winhtike169064@gmail.com', '09254218307', 'Engineering', 'excel, communication, project management', 'active', 'CV Lead Tracker', 'CV: Win Htike - IT Supervisor (MT).pdf'),
('Shoon Yupar Aung Visual', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Shoon Yupar Aung - Visual Mechandising (MT).pdf'),
('Yan Naung Soe Warehouse', 'yanyenaing910@gmail.com', NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Yan Naung Soe-Warehouse Manager (MT).pdf'),
('Thiha Kyaw Site Engineer', 'thihakyawcpburma@gmail.com', '09777071133', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Thiha Kyaw - Site Engineer (MT).pdf'),
('Thinzar Lwin Korea Tranlator', NULL, NULL, 'Education', NULL, 'active', 'CV Lead Tracker', 'CV: Thinzar Lwin - Korea Transalator (MT).pdf'),
('Career Objective', 'yanlynn1015@gmail.comHighly', NULL, 'Management', 'git, excel, leadership, communication, project management, problem solving', 'active', 'CV Lead Tracker', 'CV: Yan-Lynn-Oo-Trade Marketing M (MT).pdf'),
('Phyoe Thinzar Oo', NULL, NULL, 'HR & Admin', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: PHYOE THINZAR OO - HR & Admin (MDY)MT.pdf'),
('Su Thet Naing', 'suthetnaing@gmail.com', NULL, 'HR & Admin', 'communication', 'active', 'CV Lead Tracker', 'CV: Su Thet Naing - Executive Assistant (MT).pdf'),
('Dear Sir Or Madam,', NULL, '09251037970', 'Management', 'aws, excel, leadership', 'active', 'CV Lead Tracker', 'CV: Su Thandar Myo - Admin & HR Executive (MT).pdf'),
('Sithu Win Maw Portfolio', 'sithuwinmaw834@gmail.com', '09756160603', 'Management', 'communication, analytical', 'active', 'CV Lead Tracker', 'CV: Sithu Win Maw - Portfolio Manager (MT).pdf'),
('Phyo Arkar Kyaw Electricain', 'phyoakarkyaw1996@gmail.com', '09750140004', 'Engineering', 'excel, problem solving', 'active', 'CV Lead Tracker', 'CV: Phyo Arkar Kyaw - Electricain (MT).pdf'),
('Myo Thiri Hlaing', 'myothirihlaing0123@gmail.com', '09255490413', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Myo Thiri Hlaing -E & I (NPT) (MT).pdf'),
('Su Su Theint Bd', 'susutheint.7@gmail.com', NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Su Su Theint - BD Manager (MT).pdf'),
('Htike Htike Aung Drafter', 'htikeaung.honli@gmail.com', '959760512564', 'Engineering', 'git, excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Htike Htike Aung _Drafter (MT).pdf'),
('Hah It Support', NULL, NULL, 'Engineering', 'python, java, javascript, docker, excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: HAH_IT Support - MT.pdf'),
('Aye Chan Mon', 'ayechanmonlk@gmail.com', '09795402706', 'HR & Admin', 'communication', 'active', 'CV Lead Tracker', 'CV: AYE CHAN MON - HR & Admin (MT).pdf'),
('Ayethetoo Telecom Engineer', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: AyeThetOo- Telecom Engineer (MT).pdf'),
('Curriculum Vitae', 'hlahlaoo0379@gmail.com', '09256450906', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Hla Hla Oo - Site Engineer (MT).pdf'),
('Kyawt K Khaing Win', 'kyawtkkhaing13@gmail.com', NULL, 'Management', 'git, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Kyawt Kay Khaing _Head of Marketing (MT).pdf'),
('Min Thant Corporate Les', 'minminthantfor123@gmail.com', NULL, 'Management', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: Min Thant - Corporate Sales (Pathein)MT.pdf'),
('Naw June Moe Ra', NULL, '09425014879', 'Management', 'excel, leadership, problem solving', 'active', 'CV Lead Tracker', 'CV: Naw June Moe Ra -Corporate Sales Manager (MT).pdf'),
('Personal Details', 'suhlaing1131993@gmail.com', '09768612317', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Zin May Lwin - Data Entry (MT).pdf'),
('Kaung Myat Moe Noc', NULL, NULL, 'Engineering', 'express, git, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Kaung Myat Moe - NOC (MT).pdf'),
('Hlaing Zar Mon Qaqc', NULL, '09265757509', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Hlaing Zar Mon- QAQC (MT).pdf'),
('Nyein Thandar Kyaw Hr', 'nyeinthandarkyaw974@gmail.com', NULL, 'HR & Admin', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Nyein Thandar Kyaw - HR Assistant (MT).pdf'),
('Thaw Thaw Data Collector', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Thaw Thaw  - Data Collector (SPT)MT (1).pdf'),
('Aungkyawmon Ios Developer', NULL, NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: AungKyawMon-iOS Developer (MT).pdf'),
('My Personal Details', 'znwnhtet@gmail.com', '09798205661', 'Sales & Marketing', 'excel, leadership, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: _Zin_Win_Htet - Key Accouont Executive (MT).pdf'),
('Khaing Toe Aung', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Sa Khaing Toe Aung - Sales & Cashier (MT).pdf'),
('Ei Thara Phu', 'aphu7@gmail.com', '9764354803', 'HR & Admin', 'git', 'active', 'CV Lead Tracker', 'CV: Ei Thara Phu - Sales Admin (MT).pdf'),
('Moe Win', 'moewin2631993@gmail.com', '09964638530', 'Engineering', 'communication', 'active', 'CV Lead Tracker', 'CV: Moe Win - Senior M & E (MT).pdf'),
('Yan Naing Oo Drafter', 'yannaingoo.eng@gmail.com', '09420773432', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Yan Naing Oo - Drafter (MT).pdf'),
('Su Kalyar Thin', 'sukalyarthin2020@gmail.co', '09980073257', 'Sales & Marketing', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Su Kalyar Thin - Key Account Senior Staff (Sales Admin)MT.pdf'),
('Nilar W In', 'nilarwin148070@gmail.com', NULL, 'HR & Admin', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Nilar Win- Social Media Coordinator (MT).pdf'),
('Linn Maung Hse Officer', 'maunglinn89@gmail.com', '959261275006', 'Management', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: Linn Maung  - HSE Officer (MT).pdf'),
('Kzh Project', '0943158946loveabsentfield@icloud.com', NULL, 'Management', 'leadership, project management', 'active', 'CV Lead Tracker', 'CV: KZH - Project Manager (NPT) MT.pdf'),
('Mya Mya Oo Cashier', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Mya Mya Oo - Cashier (MT).pdf'),
('Htoo Aung Lin', 'no-09250365508mail-htooaunglin2342002@gmail.com', NULL, 'Engineering', 'java, javascript, react', 'active', 'CV Lead Tracker', 'CV: Htoo Aung Lin - Full Stack Developer (MT).pdf'),
('Naw T Cashier', NULL, '09776599778', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Naw Sat - Cashier (MT).pdf'),
('Detail Of Personal', NULL, '959986648009', 'Engineering', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Zaw Min That - SIte Engineer (MT).pdf'),
('Mg N Chinese Translator', NULL, '09957353610', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Mg San - Chinese Translator (MT).pdf'),
('B.sc(geology) Sittway Universtiy', 'zinkoko373@gmail.com', '09780889001', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Zin Ko Ko - Coprorate Relationship Manager (MT).pdf'),
('Khin Myo Win Qa', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Khin Myo Win - QA (MT).pdf'),
('Chit Wine Digital Marketing', 'chitwine2012@gmail.comChit', '09942529787', 'Sales & Marketing', 'git, excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Chit Wine - Digital Marketing Manager (MT).pdf'),
('Kyaw Arkar Phyo', NULL, NULL, 'Engineering', 'aws, azure, excel, communication', 'active', 'CV Lead Tracker', 'CV: Kyaw Arkar Phyo - Senior System Engineer.pdf'),
('Seng Du Hr', 'apyone0507@gmail.com', '09680575712', 'Management', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Seng Du - HR Assistant (MT).pdf'),
('Khin Ndar Win', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Khin Sandar Win - Executive (Pathein).pdf'),
('Curriculum Vitae', 'hanthu.forestry@gmail.com', '959884441356', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Han Thu Htet - Translator (MT) LinkedIn.pdf'),
('Han Zaw Htay', NULL, '09404670759', 'Management', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Han Zaw Htay (Inventory Controller)MT.pdf'),
('Yoon Nadi Hlaing Customer', NULL, NULL, 'Customer Service', NULL, 'active', 'CV Lead Tracker', 'CV: Yoon Nadi Hlaing - Customer Service (MT).pdf'),
('Hla Myat Noe Hr', 'atmoe37@gmail.com', '09881974794', 'General/Other', 'communication', 'active', 'CV Lead Tracker', 'CV: Hla Myat Noe - HR Assistant (Fresher)MT.pdf'),
('Seinn Lae Lae Kyaw', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Seinn Lae Lae Kyaw -HR Executive (MDY)MT.pdf'),
('Zin Thaw Tar Htet', 'chuu272859@gmail.com', '959767308028', 'Management', 'leadership', 'active', 'CV Lead Tracker', 'CV: Zin Thaw Tar Htet  - Sales & Marketing (MT).pdf'),
('Shoon Lae Chinese Translator', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Shoon Lae - Chinese Translator (MT).pdf'),
('Thet Phyo Hnin', 'hnin.ww2522@gmail.com', '09260994063', 'Customer Service', NULL, 'active', 'CV Lead Tracker', 'CV: Thet-Phyo-Hinin - CS (Non Buting) MT.pdf'),
('Name Mashweyeewinhtet', 'shweyeewinhtet223@gmail.com', '09751464709', 'Management', 'aws, excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Shwe Yee Win Htet - Procurement Exe (MT).pdf'),
('Lwin Moe', 'lwinmoeit1997@gmail.com', '9259961009', 'Engineering', 'mysql, sql, excel, communication', 'active', 'CV Lead Tracker', 'CV: Lwin Moe - Senior IT Techanician (MT).pdf'),
('Zar Ni Customer Service', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Zar Ni - Customer Service (MT).pdf'),
('Chan Nyein Soe Graphic', NULL, NULL, 'Design', NULL, 'active', 'CV Lead Tracker', 'CV: Chan Nyein Soe - Graphic Designer (MT).pdf'),
('Ye Wai Phyo Qa', 'yewaiphyo117475@gmail.comDate', '09793830849', 'Sales & Marketing', 'excel, problem solving', 'active', 'CV Lead Tracker', 'CV: Ye Wai Phyo - QA (Thekayta)MT.pdf'),
('Maymyintthu Data Analyst', 'maymyintthu1313@gmail.com', '9250851727', 'Engineering', 'sql, excel', 'active', 'CV Lead Tracker', 'CV: MayMyintThu - Data Analyst (MT).pdf'),
('Thuzar Nyein Hr', NULL, '09429772715', 'HR & Admin', 'excel, powerpoint, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Thuzar Nyein - HR Executive (MT).pdf'),
('May Zin Myo', 'Yangonmayzinmyo5920@gmail.comStrong', '09966835452', 'Sales & Marketing', 'git, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: May Zin Myo - Social Media Coordinator (MT).pdf'),
('Hnin Pwint Fincance', 'hpa.js.2021@gmail.com', NULL, 'Finance & Accounting', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Hnin Pwint - Fincance Manager (MT).pdf'),
('Chan Myint Wai', NULL, '09670220845', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Chan Myint Wai - Sales & Cashier (MT).pdf'),
('May Pel Hr Execuitve', 'Township.phyusabelmay@gmail.comContactMay', NULL, 'Management', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: May Sapel - HR Execuitve (MT).pdf'),
('Kyaw Kyaw Lin', 'tharhtweeluu@gmail.com', '09453550078', 'Management', 'git, communication', 'active', 'CV Lead Tracker', 'CV: Kyaw Kyaw Lin - Sales (MT).pdf'),
('Ar Kar Phyo Portfolio', NULL, '09250795153', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Mr. Ar Kar Phyo -PORTFOLIO.pdf'),
('Myo Min Min', 'myominmin88@gmail.com', '959691186045', 'Management', 'leadership, problem solving', 'active', 'CV Lead Tracker', 'CV: Myo Min Min - Sales Manager (Agency)MT.pdf'),
('Hay Man Page Admin', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Hay Man - Page Admin (MT).pdf'),
('Theint Thida Soe', NULL, '09964211724', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Theint Thida Soe - Sales & Marketing (MT).pdf'),
('Htet Aung', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Htet Aung Lin(10).pdf'),
('Mottama Holdings Ltd', 'atnoewai999@gmail.com', '09794104354', 'General/Other', 'mysql, sql', 'active', 'CV Lead Tracker', 'CV: Htet Myat Noe Wai - Website & Odoo Admin (MT).pdf'),
('Finance Manager', 'eieiphyo227@gmail.com', '09443066412', 'Management', 'aws, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Ei Ei Phyo-Finacial Controller (MT).pdf'),
('Thandar Oo Customer Service', 'thandarthandar643@gmail.com', '09758366244', 'HR & Admin', 'express, excel', 'active', 'CV Lead Tracker', 'CV: Thandar Oo - Customer Service (MT).pdf'),
('Personal Particulars', 'nandarlinyumaw19@gmail.com', '09782271402', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Nandar Lin Yu Maw - HR Executive (MT).pdf'),
('Work Experience', 'lamin2001@gmail.com', '09772339363', 'General/Other', 'communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Kaung Sett Naing - Data Collector (MT).pdf'),
('Showroom Sales Staff', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Chit Myat Oo - Showroom Sales Staff (MT).pdf'),
('Shwe Ya Min', NULL, '09750468954', 'Sales & Marketing', 'git', 'active', 'CV Lead Tracker', 'CV: Shwe Ya Min - Sales (MDY) MT.pdf'),
('Phyoe Ei Maung', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Phyoe Ei Maung - Senior Financial Advisor (TGI)MT.pdf'),
('Sai Aung Hlaing', 'saiaunghlaing669@gmail.co', '959954008436', 'HR & Admin', 'git, excel, problem solving', 'active', 'CV Lead Tracker', 'CV: Sai Aung Hlaing - Suitable Sales (MT).pdf'),
('Khin Swe Zi Customer', NULL, NULL, 'Customer Service', NULL, 'active', 'CV Lead Tracker', 'CV: Khin Swe Zi - Customer Service Executive (MT).pdf'),
('Pyae Sone Aung', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Pyae Sone Aung - Senior FA (MDY)MT (1).pdf'),
('Khin Phyo Sint Collection', 'yxin8922@gmail.com', NULL, 'Management', 'leadership', 'active', 'CV Lead Tracker', 'CV: Khin Phyo Sint - Collection Manager (MT).pdf'),
('Linn Linn Htet Qa', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Linn Linn Htet - QA.pdf'),
('Win Thiri Ko Ko', 'winthirikoko@gmail.com', NULL, 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Win Thiri Ko Ko - Sales Admin (MT).pdf'),
('Ye Win It Support', 'ywn1781994@gmail.com', '09420047009', 'Sales & Marketing', 'git, communication', 'active', 'CV Lead Tracker', 'CV: Ye Win - IT Support (MT).pdf'),
('Shein Htut Maung It', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Shein Htut Maung - IT Assistant (MT).pdf'),
('Nwe Nwe Cashier', NULL, '09769735510', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Nwe NWe - Cashier (MT).pdf'),
('Aye Min Paing Data', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Aye Min Paing - Data Collector (Mingalardon)MT.pdf'),
('Nyein Chan Min Noc', NULL, '09970465003', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Nyein Chan Min_NOC (MT).pdf'),
('Yin Mu Aung', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Yin Mu Aung - Sales (TGI)MT.pdf'),
('Curriculum Vitae', NULL, '09740936634', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Ei Thazin Phyo-Marketing officer (MT).pdf'),
('Tin Myo Win', 'tinm44110@gmail.com', '959965017396', 'Engineering', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Tin Myo Win CV - Production Engineer (MT).pdf'),
('Westyangon University', 'waiwaimon772@gmail.com', '09958102264', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Wai Wai Mon - English Translator (MT).pdf'),
('Soe Wana Noc Engineer', 'soewana9k@gmail.com', '959970480859', 'Engineering', 'communication', 'active', 'CV Lead Tracker', 'CV: Soe Wana - NOC Engineer (MT).pdf'),
('Chit Phuu Wai Procurement', '38@gmail.com', '9789215229', 'Operations', 'excel', 'active', 'CV Lead Tracker', 'CV: Chit Phuu Wai - Procurement Executive (MT).pdf'),
('Kyaw Myint Thu Hr', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Kyaw Myint Thu - HR Assistant (MT).pdf'),
('Mr Htike Aung Lin', 'htikeaunglinn1998@gmail.com', NULL, 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Htike Aung Lin - Ass QA (MT).pdf'),
('Eaint Pyae Pyae Kyaw', 'eaintpyae44@gmail.com', '09444211164', 'Sales & Marketing', 'git, communication', 'active', 'CV Lead Tracker', 'CV: Eaint Pyae Pyae Kyaw - Content Writer (MT).pdf'),
('Tt Aung Operation', NULL, '09958363830', 'Sales & Marketing', 'aws, excel, leadership, analytical', 'active', 'CV Lead Tracker', 'CV: Mr. Satt Aung - Operation Manager (TGI)MT.pdf'),
('Kaung Htet Kyaw', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Kaung Htet Kyaw - Sales & Markeitng (MT).pdf'),
('Yu English Translator', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Yu - English Translator (MT).pdf'),
('Hr And Admin', 'htetwai231196@gmail.com', '09978302696', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: HTET+WAI+AUNG - HR and Admin Assistant (MT).pdf'),
('Yan Naung Soe', 'waiyansoe-innlay2022@gmail.com', '09679498512', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Yan Naung Soe - Sales (no exp)MT.pdf'),
('Su Kay Khine Oo', 'sukkhineoo@gmail.com', '09420046741', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Su Kay Khine Oo- HR Manager (MT).pdf'),
('My Portfolio', 'theintthirisoe3110@gmail.com', '959772139932', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Theint Thiri Soe - Media Buyer & Content (MT).pdf'),
('Shine Min Aung Hr', 'www.shineminaung144@gmail.com', '09697281161', 'HR & Admin', 'express, excel, powerpoint, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Shine Min Aung - HR Executive (MT).pdf'),
('Nyein Aye Htun', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Nyein Aye Htun - Manager FA (MT).pdf'),
('Haindrahtoo Database Admin', 'haindrahtoo1@gmail.com', '09457494960', 'Management', 'git, excel, leadership, communication, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: Haindrahtoo - Database Admin (MT).pdf'),
('Aung Zaw Myint Waarhouse', 'kyawminoo@premiumgroup.com.mm', '09950395775', 'Management', 'excel, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Aung Zaw Myint - Waarhouse Supervisor(MT).pdf'),
('Si Thu Driver', 'Sithutsm@gmail.com', '09783738644', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Si Thu - Driver (MT).pdf'),
('Thin Thin Soe Hr', 'hniangthin01@gmail.com', '09789648723', 'Management', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Thin Thin Soe - HR (MT).pdf'),
('Soe Lwin Lwin Invenotry', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Soe Lwin Lwin - Invenotry controller.pdf'),
('Yar Ku English Translator', 'yarku610@gmail.comContactI', NULL, 'Management', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Yar Ku - English Translator (MT).pdf'),
('Race - Myanma R', NULL, '09250004143', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Hnin Moe Aye - Corporate Relationship Manager (MT).pdf'),
('Su Phyo Paing Noc', NULL, '09898792871', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Su Phyo Paing - NOC (MT).pdf'),
('Yamin Htet Kyaw Hr', 'ymin53132@gmial.com', NULL, 'HR & Admin', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Yamin Htet Kyaw - HR Assistant (HTY)MT.pdf'),
('Chan Nyein Soe Portfolio', 'Channyeinsoe0202@gmail.com', '09768750440', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Chan Nyein Soe Portfolio (MT).pdf'),
('Chit Nine Aung', NULL, '959751183833', 'Sales & Marketing', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Chit Nine Aung - Sales Operator (MT).pdf'),
('Zayar Aung Data Collector', NULL, '09699430033', 'General/Other', 'communication', 'active', 'CV Lead Tracker', 'CV: Zayar Aung - Data Collector (Pathein)MT.pdf'),
('En Gyin Thant Hr', 'engyinthant638@gmail.com', NULL, 'HR & Admin', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: En Gyin Thant - HR Assistant (MT).pdf'),
('Yair Wint Zaw Data', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Yair Wint Zaw - Data Entry (MT).pdf'),
('Htut Myat Noe Oo', 'noeoo@gmail.com', '09775907700', 'HR & Admin', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Htut Myat Noe Oo-Payroll Assistant (MT).pdf'),
('Khin Swe Myint', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Khin Swe Myint (Cashier,TGI) MT.pdf'),
('Ye Lwin Aung Driver', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Ye Lwin Aung - Driver (MT).pdf'),
('Aung Myo Khant', 'aungmyokant98@gmail.com', '959771647451', 'Management', 'excel, powerpoint, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Aung Myo Khant  - Sales (TGI) MT (1).pdf'),
('Myo Thu Zar', '1500.pure.love@gmail.com', '09420782254', 'HR & Admin', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Myo Thu Zar - Sales Manager (MT).pdf'),
('Khin Thet Soe', 'sarathomas492@gmail.com', NULL, 'HR & Admin', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Khin Thet Soe -Executive Assistant (MT).pdf'),
('Kay Kay', 'kayzarmaw54@gmail.com', '959798855043', 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Kay Zar Maw - Bank Advisor (MT).pdf'),
('Arkar Soe Naing Noc', 'arkarsoenaing5122024@gmail.com', '09886818868', 'Management', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: Arkar Soe Naing - NOC (MT).pdf'),
('Su Mon Aung', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Su Mon Aung - Sales Admin (MT).pdf'),
('Ei Ei Thein Hr', 'mawsitone647@gmail.comPERSONAL', '09446209452', 'HR & Admin', 'aws, excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Ei Ei Thein - HR Assistant (MT).pdf'),
('Aye Myat Mon Hr', 'ayem16928@gmail.com', '959951104088', 'Management', 'excel, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Aye Myat Mon - HR Manager (MT).pdf'),
('Nay Lin Aung Noc', 'naylin_aung@outlook.com', '09761081235', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Nay Lin Aung - NOC (MT).pdf'),
('About Myself', 'motethone2009@gmail.com', '09979320148', 'Sales & Marketing', 'communication', 'active', 'CV Lead Tracker', 'CV: Final+Asssistant Sales Manager (MT).pdf'),
('Hsu Yee Nandar Cashier', 'hsuyeenandar23@gmail.com', '09253932471', 'Customer Service', 'excel, problem solving', 'active', 'CV Lead Tracker', 'CV: Hsu Yee Nandar - Cashier (TGI).pdf'),
('Star City Thanlyin', 'suyeetoe@gmail.com', NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Su Yee Toe - Financial Controller (MT).pdf'),
('Aung Thu Noc', 'aungthu2025730@gmail.com', '09778340016', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Thu - NOC (MT).pdf'),
('Yamone Kyaw', 'yamonekyaw7713@gmail.com', '09265870956', 'Finance & Accounting', 'excel, powerpoint, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Yamone Kyaw - Finance Assistant (MT).pdf'),
('Kyaw Zin Khant', 'kyaw.z.khnt@gmail.com', '9958588443', 'Engineering', 'excel, leadership, communication, project management', 'active', 'CV Lead Tracker', 'CV: Kyaw Zin Khant - Senior Network Engineer (MT).pdf'),
('Linn Phone', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Linn Phone - Sales Operator (MT).pdf'),
('Ei Mon Shwe Hr', 'eimonshwe.eversmile@gmail.com', '09427178637', 'HR & Admin', 'excel, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Ei Mon Shwe - HR Executive  (MDY)(MT).pdf'),
('Tamwe, Yangon', 'minthanhtite44@gmail.com', '09785924880', 'Engineering', 'java, javascript, mysql, sql, excel, problem solving', 'active', 'CV Lead Tracker', 'CV: Min Than Htike - Data Entry (MT).pdf'),
('Theint Shwe Zin Noc', 'theintshwezin861999@gmail.com', '09962606757', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Theint Shwe Zin -NOC (MT).pdf'),
('Int Int Nyo Customer', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Saint Saint Nyo - Customer Service (MT).pdf'),
('Aung Myin Claim Specialist', 'aungmyin.itjlpt@gmail.com', '09421024532', 'Customer Service', 'git, excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Aung Myin - Claim Specialist (MT).pdf'),
('Shoon La Pyae Hr', 'shoonlapyae23@gmail.com', '959949045201', 'HR & Admin', 'aws, communication', 'active', 'CV Lead Tracker', 'CV: Shoon La Pyae - HR  Executive (MT).pdf'),
('Yadanar Tun Cashier', 'adanarh180@gmail.com', '09454219452', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Yadanar Tun - Cashier (Bago)MT.pdf'),
('Harry Hr', NULL, NULL, 'General/Other', 'excel', 'active', 'CV Lead Tracker', 'CV: Harry - HR Manager (MT).pdf'),
('Tsp, Yangon.', 'unitunzawwintun@gmail.comDAISY', '09751920891', 'Management', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: Zaw Win Htun-Production Engineer (MT).pdf'),
('Han Nway Oo Hr', 'avalynnoo30@gmail.com', NULL, 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Han Nway Oo - HR Assistant (MT).pdf'),
('Bo Thet Htun Noc', NULL, '09787681549', 'Engineering', 'communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Bo Thet Htun - NOC Engineer (MT).pdf'),
('Kaung Htet Lin Qa', 'kaunghtetlinngyi@gmail.com', NULL, 'Management', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Kaung Htet Lin - QA.pdf'),
('Saw Saw Htun', 'sawsawtun74@gmail.com', '09788112008', 'Customer Service', 'aws, communication', 'active', 'CV Lead Tracker', 'CV: Saw Saw Htun - Data Entry (MT).pdf'),
('Htun Lin Aung Hr', 'uria4157@gmail.com', '09679777382', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Htun Lin Aung - HR Assistant (MT).pdf'),
('Personal Data', NULL, '959977235629', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: May Myat Noe Zaw (Operation Officer).pdf'),
('Thinzar Myo Htet', 'Kukuu4511@gmail.com', NULL, 'Management', 'excel, leadership, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Thinzar Myo Htet - Hanni Cho Referral (MT).pdf'),
('National Ity : Myanmar', NULL, '09963069791', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Tin Ko Ko Oo - Driver (MT).pdf'),
('U Wai Yan Lin', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: U Wai_Yan_Lin_Factory Manager (MT).pdf'),
('Honest And Hardworking', 'htoimai714@gmail.comSKILLS', '09981796149', 'Management', 'excel, leadership, problem solving', 'active', 'CV Lead Tracker', 'CV: Sau Htoi Mai (Sales Manager)TGI (MT).pdf'),
('Mya Kaung', NULL, '09942288693', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Mya Kaung - Sales Rep (Door to door) MT.pdf'),
('Hnin Hnin Khaing Procurement', 'hh.khaing771212@gmail.com', '959782572564', 'Management', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: Hnin Hnin Khaing - Procurement Executive (MT).pdf'),
('Curriculum Vitae', 'aungheinhtetaung697@gmail.com', '09671064787', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Hein Htet Aung - NOC Engineer (MT).pdf'),
('Cho Cho Lwin Hr', 'chocholwin212121@gmail.comEmail', NULL, 'HR & Admin', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Cho Cho Lwin - HR Assistant (MT).pdf'),
('Law Major', 'akhaingmin534@gmail.com', '09987487447', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Khaing Min - Tour Leader (MT).pdf'),
('U Soe Thiha', 'htetaunglinn204@gmail.com', '09984640165', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Htet Aung Lin - Data Collector (HTY)MT.pdf'),
('Su Myat Noe Payroll', 'sumyatnoe.su2003@gmail.com', '09980053238', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Su Myat Noe - Payroll Assistant (MT).pdf'),
('Interpersonal Skill', 'waihinksoo@gmail.com', '959250007070', 'Management', 'aws, excel, leadership', 'active', 'CV Lead Tracker', 'CV: Wai Hin Kyaw Swar Oo - HSE Officer (MT).pdf'),
('Aung Ko Htet', 'minphonemyathtet@gmail.com', NULL, 'Management', 'excel, photoshop, leadership', 'active', 'CV Lead Tracker', 'CV: Aung Ko Htet - Sales Manager (MDY)MT.pdf'),
('I Lin Awn Noc', 'xsinoon@gmail.com', '09428671256', 'Engineering', 'powerpoint', 'active', 'CV Lead Tracker', 'CV: Sai Lin Awn - NOC (MT).pdf'),
('Min Ko Thu', 'minkothu2010@gmail.com', '959799232809', 'Engineering', 'mysql, postgresql, sql, docker, kubernetes, analytical', 'active', 'CV Lead Tracker', 'CV: Min-Ko-Thu-Syetem Engineer (MT).pdf'),
('Hung Sett Paing Lwin', 'zhtetpai@gmail.com', '959977295296', 'Engineering', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Hsaung Sett Paing Lwin - Network Engineer (MT).pdf'),
('Personal Particular', 'marmarsanlwin11@gmail.com', '09253184462', 'Engineering', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Mar Mar San Lwin - Electrical Engineer (MT).pdf'),
('Nay Aunglinn', 'nayaglinn.2018@gmail.com', '95945123629', 'HR & Admin', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Nay Aung Lin - Supply Chain Executive (MT).pdf'),
('May Thu Kyaw', '60@gmail.com', '09950418944', 'HR & Admin', 'aws, excel', 'active', 'CV Lead Tracker', 'CV: Ms. May Thu Kyaw - HR Executive (MT).pdf'),
('Ms. Ein Kying Khine', 'einkyingkhine085@gmail.com', NULL, 'HR & Admin', 'aws, excel', 'active', 'CV Lead Tracker', 'CV: Ein Kying Khine - HR Exeutive (MT).pdf'),
('Liointerior Designer', 'htetaunghlaing1620@gmail.com', '09442076070', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Htet Aung Hlaing - Interior Designer (MT).pdf'),
('U Htoi Mai', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Sau Htoi Mai - Sales Manager (TGI)MT.pdf'),
('Race - Myanmar', NULL, '09799233009', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Kaung Zin Hein - NOC Engineer (MT).pdf'),
('Thazin Win', NULL, '09781501455', 'Sales & Marketing', 'git, excel, problem solving', 'active', 'CV Lead Tracker', 'CV: Thazin Win - Sales & Marketing (MT).pdf'),
('Thukha Mingalar Clinic', 'shoonlei61@gmail.com', '09795354942', 'Healthcare', 'communication', 'active', 'CV Lead Tracker', 'CV: Receptionist - MT.pdf'),
('Htet Linn Marketing', 'htetlinn195@gmail.com', '09982568935', 'Management', 'leadership, communication, project management', 'active', 'CV Lead Tracker', 'CV: Htet Linn - Marketing Manager (MT).pdf'),
('Enterprise Advanced', 'aungwaiphyo.1789@gmail.com', '09794794252', 'Engineering', 'git', 'active', 'CV Lead Tracker', 'CV: Aung_Wai_Phyo - Sr Netwrok Engineer (MT).pdf'),
('Aung Pyae Phyo', 'mgaungpyaephyolay56@gmail.com', '09777559440', 'Management', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: Aung Pyae Phyo - Sales Manager (Banca)MDY MT.pdf'),
('Mya Yee', 'pyoneyakeko@gmail.com', '09422592644', 'Management', 'project management', 'active', 'CV Lead Tracker', 'CV: Mya Yee Nandar(life planner).pdf'),
('Associate Government Technical', 'aungyekyaw.engr22@gmail.com', '959260339418', 'Management', 'excel, photoshop', 'active', 'CV Lead Tracker', 'CV: Aung Ye Kyaw - Visual Merchandising Executive (MT).pdf'),
('Thiha Oo', 'thihaoo38760@gmail.com', '09799635685', 'Engineering', 'sql, leadership, communication, project management, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: Thiha Oo - Senior Network Engineer (MT).pdf'),
('Yu Nandar Suitable Les', NULL, '09698703637', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Yu Nandar  - Suitable Sales (MT).pdf'),
('Pyae Pho Kyaw Ae', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Pyae Pho Kyaw - AE (NPT) MT.pdf'),
('Htet Htet Hr Intern', NULL, '09440681029', 'HR & Admin', 'communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Htet Htet - HR Intern (MT).pdf'),
('Chan Nyein Soe', 'mr.channyeinsoe@outlook.com', NULL, 'Engineering', 'azure, leadership', 'active', 'CV Lead Tracker', 'CV: Chan Nyein Soe - Senior System (MT).pdf'),
('Aung Htet Thu Customer', NULL, NULL, 'Customer Service', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Htet Thu - Customer Service (MT).pdf'),
('Htoo Htet Aung', NULL, NULL, 'Sales & Marketing', 'git, problem solving', 'active', 'CV Lead Tracker', 'CV: Htoo Htet Aung - Manager Financial Advisor (MT).pdf'),
('Name - Ingyin May', 'mileysmith199899@gmail.com', '09422272410', 'Sales & Marketing', 'git', 'active', 'CV Lead Tracker', 'CV: Ingyin May  (Sales and Marketing ) - MT.pdf'),
('Myo Ko Ko Naing', NULL, NULL, 'Customer Service', NULL, 'active', 'CV Lead Tracker', 'CV: Myo Ko Ko Naing - IT Support (MT).pdf'),
('Thet Htoo Zin Marketing', 'thethtoo1282@gmail.com', '959793051811', 'Sales & Marketing', 'git, excel, communication, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: Thet Htoo Zin - Marketing (MT).pdf'),
('Sein Moh Moh Thwin', NULL, '9966898815', 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Sein Moh Moh Thwin - Internal Audit (MT).pdf'),
('Race - Myanmar', NULL, '09677926482', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Ei Ei San - Life Planning Offier (MT).pdf'),
('Curriculum Vitae', NULL, NULL, 'Management', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Tin Moh Moh Aung - QA (MT).pdf'),
('Wai Linn Hlaing', 'wailinnhlaing.ict@gmail.com', NULL, 'Management', 'agile, scrum, excel, leadership, communication, project management, analytical', 'active', 'CV Lead Tracker', 'CV: Wai Linn Hlaing - IT Team Leader (MT).pdf'),
('Tin Pa Pa Myo', 'papamyo0107@gmail.com', '09974513924', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Tin Pa Pa Myo - Payroll Assistant (MT).pdf'),
('Aye Thiri Thu', 'ayethirithu0804@gmail.com', '09771706731', 'Operations', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Aye Thiri Thu - Englihs T (MT).pdf'),
('Chan Merchandising Supervisor', 'ayechan1428@gmail.com', '09891250919', 'Management', 'leadership', 'active', 'CV Lead Tracker', 'CV: Chan - Merchandising Supervisor (MT).pdf'),
('Aye Hsu Pan Casheir', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Aye Hsu Pan - Casheir (MT).pdf'),
('Chan Nyein Aye', '12@gmail.com', '09255484217', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Chan Nyein Aye - Manager Financial A (MT) (1).pdf'),
('Zaw Ye Wint Aung', NULL, '09958492017', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Zaw Ye Wint Aung - Senior System Engineer (MT).pdf'),
('Thu Thu Htet Cashier', 'thuthuhtet959@gmail.com', '09667678735', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Thu Thu Htet - Cashier (MT).pdf'),
('Personal Detail', NULL, NULL, 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: NNNS_Sales & Marketing Manager (MT).pdf'),
('N N Wai Procurement', 'waiwai176.aae@gmail.com', '959448008089', 'Engineering', 'excel, powerpoint, photoshop', 'active', 'CV Lead Tracker', 'CV: San San Wai - Procurement Executive (MT).pdf'),
('Htet Paing Soe Corporate', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Htet Paing Soe - Corporate Relationship Manager (Pathein)MT.pdf'),
('Personal Info', 'nyolaynyolay1@gmail.com', '09423677413', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Nyo Lay - A Branch M (Pyay)MT.pdf'),
('Myo Ko It Support', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Myo Ko- IT Support (MT).pdf'),
('Aung Khant Min', NULL, '09973828527', 'HR & Admin', 'problem solving', 'active', 'CV Lead Tracker', 'CV: Aung Khant Min - Sales (MT).pdf'),
('Thiri Customer Service', 'myatthirizaw2002@gmail.com', '09980853562', 'HR & Admin', 'communication', 'active', 'CV Lead Tracker', 'CV: Thiri - Customer Service (MT).pdf'),
('Thuzar Win Office Le', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Thuzar Win - Office Sale (MT).pdf'),
('Thuya Aung Customer Service', 'thuyaaung2288@gmail.com', '959975806793', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Thuya Aung - Customer Service (MT).pdf'),
('Aye Mon Oo Drafter', 'ayemonoo2411@gmail.com', '959765160021', 'Engineering', 'communication', 'active', 'CV Lead Tracker', 'CV: Aye Mon Oo Drafter (MT).pdf'),
('Zin Thaw Thar Htet', 'chuu272859@gmail.com', '959767308028', 'Management', 'leadership', 'active', 'CV Lead Tracker', 'CV: Zin Thaw Thar Htet - Manager Financial Advisor (MT).pdf'),
('Date Of Birth :29.6.2000', 'mohmohthethnin101@gmail.com', '959459364188', 'Sales & Marketing', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Moh Moh Thet Hnin - English Translator (MT).pdf'),
('Yeemontheint Hr Admin', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: YeeMonTheint - HR & Admin Manager (MT).pdf'),
('Working Experience', 'ngweni686@gmail.com', '09958360993', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Nwe Ni - HR & Admin Executive (MT).pdf'),
('Pan Ei Phyu', NULL, '09777336294', 'Sales & Marketing', 'communication', 'active', 'CV Lead Tracker', 'CV: Pan Ei Phyu - Sales & Cashier (MT).pdf'),
('Tint F B', 'kovacevic@alhamramarina.com', '09253359491', 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Tint - F & B Manager (MT).pdf'),
('Chit Thae Maung', 'chitthaemaung.mg@gmail.com', '09789274016', 'HR & Admin', 'git, excel', 'active', 'CV Lead Tracker', 'CV: ChitThaeMaung_HR&AdminAssistant_CV.pdf'),
('May Myat Thaw', 'maymyatthaw8893@gmail.com', '09758327690', 'Management', 'excel, powerpoint, communication, analytical', 'active', 'CV Lead Tracker', 'CV: May Myat Thaw - Sales Admi (MT).pdf'),
('Hlaing Thuzar Win', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Hlaing Thuzar Win - Marketing Supervisor (MT).pdf'),
('Cho Zin Shoonlae', NULL, NULL, 'Customer Service', 'excel', 'active', 'CV Lead Tracker', 'CV: Cho Zin Shoonlae - Sales (MT).pdf'),
('Mr. Thein Htike Soe', NULL, NULL, 'Management', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Thein htike soe  - Mechanical Engineer (MT).pdf'),
('Hsu Nandar Customer Service', 'hsu.ndht@gmail.com', '9420143768', 'Management', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: Hsu Nandar - Customer Service Executive (MT).pdf'),
('Yadanar Khine Remote Cs', 'yadanarkhine2121@gmail.com', '0804517638', 'HR & Admin', 'git, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Yadanar Khine - Remote CS (MT).pdf'),
('Ma Khin Thida Naing', 'khinthidanaing234998@gmail.com', NULL, 'Engineering', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Ma Khin Thida Naing - Pathein (MT).pdf'),
('Zar Zar Thein', 'zarzarthin282@gmail.com', '09778405884', 'Sales & Marketing', 'express, excel', 'active', 'CV Lead Tracker', 'CV: Zar Zar Thein - Sales Admin (MT).pdf'),
('Khin N Nwe Payroll', 'ksnwe2009@gmail.com', NULL, 'HR & Admin', 'excel, powerpoint, photoshop', 'active', 'CV Lead Tracker', 'CV: Khin San Nwe - Payroll Assistant (MT).pdf'),
('Wai Yan Lynn Noc', NULL, NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Wai Yan Lynn - NOC Engineer (MT).pdf'),
('Curriculum Vitae', 'alinn.co78@gmail.com', '09960000321', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: 2023-04-22_Thandar Linn_BranchCashier@TGI.pdf'),
('Jue Cherry Hr', 'juecherrysan25@gmail.com', '09967465235', 'HR & Admin', 'excel, problem solving', 'active', 'CV Lead Tracker', 'CV: Jue Cherry - HR Executive (MT).pdf'),
('Htike Aung Lin In', 'htikeaunglinn99@gmail.com', '09252737672', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Htike Aung Lin - In-store Quality Assurance.pdf'),
('Computer Skillslanguage', NULL, NULL, 'HR & Admin', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Mya Thawda Maung - HR & Admin Assistant (MT).pdf'),
('Hnin Eain Hlwar Content', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Hnin Eain Hlwar - Content Writer (MT).pdf'),
('May Than Nu Hr', 'nnu6871@gmail.com', '09763736025', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: May Than Nu - HR Assistant (NPT) MT.pdf'),
('Aung Pyae Pyo', 'aungphyok836@gmail.com', '09768766865', 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Aung Pyae Pyo - Sales Supervisor (MT).pdf'),
('Kyaw Thu Aung', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Kyaw Thu Aung - Sales & Marketing (MT).pdf'),
('Ms. Khin Thuzar Lwin', NULL, '09756969421', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Khin Thuzar Lwin - B2B Saless Manager (MT).pdf'),
('Phyo Paing Than', NULL, NULL, 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Phyo Paing Than - Sales Manager (TGI) MT.pdf'),
('Chit Pyone Zin Payroll', NULL, '09971748440', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: CHIT PYONE ZIN - Payroll Assistant (MT).pdf'),
('Phh', NULL, NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: PHH - Senior Engineer (MT).pdf'),
('Zin Oo Maung Graphic', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Zin Oo Maung - Graphic Designer (MT).pdf'),
('La Min English Translator', 'lamineainbgl28@gmail.com', '09699455438', 'Management', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: La Min - English Translator (MT).pdf'),
('Kyaw Soe Aung Driver', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Kyaw Soe Aung - Driver (MT).pdf'),
('Eaint Bo Bo Tun', NULL, '9455771463', 'Management', 'excel, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Ma Eaint BoBo Tun - Commercial Executive (MT).pdf'),
('South Dagon Township, Yangon', 'eimonhtay93@gmail.com', NULL, 'Engineering', 'python, mysql, sql, excel, analytical', 'active', 'CV Lead Tracker', 'CV: Ei Mon Htay - Data Analyst (MT).pdf'),
('May Myat Soe', 'myatmyatsoe5665@gmail.com', '09978048127', 'Management', 'leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: May Myat Soe - SA (MDY)MT.pdf'),
('Work Experience', 'shweyi.poe91@gmail.com', NULL, 'Sales & Marketing', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: Shwe Yi Poe - Suitabel Sales  (MT) (1).pdf'),
('Theingi Htun', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Theingi Htun - SA  - MDY (MT).pdf'),
('Min Khant Kyaw Banca', 'mkhantkyaw16@gmail.com', '09770707709', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Min Khant Kyaw - Banca (MT).pdf'),
('Han Thway Aung Head', 'nanthidarpyone@sssretail.com', NULL, 'Sales & Marketing', 'express, git, excel, powerpoint, photoshop, illustrator', 'active', 'CV Lead Tracker', 'CV: Han Thway Aung - Head of Sales (MT).pdf'),
('Ye Thiha Aung Data', 'Yangonmarc.yethiha998@gmail.com', '9978682056', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Ye Thiha Aung - Data Executive (MT).pdf'),
('Ingyin Mon Graphic Designer', NULL, NULL, 'Design', NULL, 'active', 'CV Lead Tracker', 'CV: Ingyin Mon - Graphic Designer (MT).pdf'),
('Arkar Win Htain Graphic', NULL, NULL, 'Design', NULL, 'active', 'CV Lead Tracker', 'CV: Arkar Win Htain - Graphic Designer (MT).pdf'),
('Thae Su Aung', 'thaesuaung662839@gmail.com', NULL, 'Engineering', 'git, communication', 'active', 'CV Lead Tracker', 'CV: Thae Su Aung - English Translator (MT).pdf'),
('Zin Pwint Oo Portfolio', NULL, NULL, 'General/Other', 'express, photoshop', 'active', 'CV Lead Tracker', 'CV: Zin Pwint Oo_Portfolio (MT).pdf'),
('Shan Dar Li', NULL, '09757887922', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Shan Dar Li - Customer Service (MT).pdf'),
('Mangongone Tsp.yangon', NULL, '09422021970', 'Management', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Chan Myae Aung - Regional M (MT).pdf'),
('Thidar Hr', NULL, '959789343110', 'HR & Admin', 'aws, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Thidar - HR Manager (MT).pdf'),
('Shwe Yamhone Call Center', 'yamhonephoo999810@gmail.com', '09953406610', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Shwe Yamhone - Call Center (MT).pdf'),
('Cho Cho Lwin Portfolio', 'chocho.grace04531@gmail.com', '09260777707', 'Sales & Marketing', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Cho Cho Lwin CV - Portfolio Manager (MT).pdf'),
('Ndar Win Receptionist', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Sandar Win - Receptionist (MT).pdf'),
('Swe Swe Win', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Swe Swe Win - Sales Admin (MT).pdf'),
('Personal Particulars', 'thweteikhin1993@gmail.com', '09253389347', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Thwet Ei Khin - Corporate Relationship Manager (MT).pdf'),
('Contact Address', 'kyawwinntintmsi@gmail.com', NULL, 'HR & Admin', 'git, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Kyaw Winn Tint - Freelance Vice President (MT).pdf'),
('Apr 2025 (ygn)', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Hnin Hnin Yu - Portfolio Manager (MT) (2).pdf'),
('Ma Su Yee Win', 'suyeewin197@gmail.com', '959660957227', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Su Yee Win - English T (MT).pdf'),
('Hein Min Oo Portfolio', 'sawheinminoo@gmail.com', '09666888969', 'Management', 'communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Hein Min Oo - Portfolio Financial Manager (MT) (1).pdf'),
('Hnin Htet Htet Aung', NULL, '09763423943', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Hnin Htet Htet Aung - Sales (Taungoo)MT.pdf'),
('Kyaw Thuya Htay', NULL, '09788131696', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Kyaw Thuya Htay - Sales & Marketing (MT).pdf'),
('W Wunna Qa', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Saw Wunna - QA (MT).pdf'),
('Thant Zin Tun Data', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Thant Zin Tun - Data Entry (MT).pdf'),
('Wei We I Moe', 'poee932002@gmail.com', '09779164446', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Wei Wei Moe - Customer Service (MT).pdf'),
('Race - Myanmar', NULL, '09661825559', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Khin Sandar Aung - Customer Service (MT).pdf'),
('Htet Aung Life', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Htet Aung Lin(10) Life planner (MT).pdf'),
('Career Objective', 'kyawzin.mdy1831996@gmail.com', '09967311990', 'Engineering', 'excel, photoshop, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Kyaw Zin Win - NOC Engineer (MT).pdf'),
('Irene Htoo Hr Assint', 'htooirene@gmail.com', NULL, 'HR & Admin', 'excel, powerpoint, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Irene Htoo - HR Assisant (MT).pdf'),
('Myo Wai Yan', 'Myowaiyan524@gmail.com', '959969255855', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Myo Wai Yan - HSE Officer (MT).pdf'),
('Bahan Township Yangon', NULL, '097713769569', 'Sales & Marketing', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Yu Wa Win Ko - Data Entry (MT).pdf'),
('Jimmy Myint Aung Hr', 'myintaung@gmail.com', NULL, 'Management', 'aws, excel, leadership, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Mr. Jimmy Myint Aung HR Manager.pdf'),
('Pyi Htet Paing', 'pyihtetpaingbb@gmail.com', '09773523351', 'Sales & Marketing', 'leadership', 'active', 'CV Lead Tracker', 'CV: Pyi Htet Paing - B2B Executive (MT).pdf'),
('Aung Thu Htun Engineer', NULL, '09250430060', 'Management', 'excel, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Aung Thu Htun - Engineer (Fiber) MT.pdf'),
('Odoo Developer', 'minhtetnaing117@outlook.com', '959790270945', 'Engineering', 'python, java, javascript, react, mysql, postgresql, sql, git, communication, project management', 'active', 'CV Lead Tracker', 'CV: Min Htet Naing - Website & Odoo Administrator (MT).pdf'),
('Production Engineer', 'maymi1011@gmail.com', '959781305484', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: May Mi Htet Aung - English Translator (MT).pdf'),
('Myat Pwint Cho', 'myatpwint059@gmail.com', '9426037346', 'Finance & Accounting', 'git, excel, problem solving', 'active', 'CV Lead Tracker', 'CV: Myat Pwint Cho - JA (no exp)Bago MT.pdf'),
('Right Shine Noc', 'shineright46@gamail.com', '09981362837', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Right Shine - NOC (MT).pdf'),
('Htun Myint Aung', 'htunmyintaung171995@gmail.com', '09668909912', 'Management', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Htun Myint Aung -NOC Engineer (MT).pdf'),
('Ye Pyae Phyo Noc', 'yehpyaephyo@gmail.comCONTACT', '09691393921', 'Engineering', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: Ye Pyae Phyo - NOC (MT).pdf'),
('May Myat Thaw', 'maymyatthaw8893@gmail.com', '09758327690', 'Management', 'excel, powerpoint, communication, analytical', 'active', 'CV Lead Tracker', 'CV: May Myat Thaw - Sales Operation Supervisor (MT).pdf'),
('Personal Info', 'myintmyatsoe919@gmail.com', NULL, 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Min Myat Soe - Corporate Relationship Manager (MT).pdf'),
('Ei Phyu Phyu Khaing', 'eiphyuphyu229900@gmail.com', NULL, 'Management', 'aws, git', 'active', 'CV Lead Tracker', 'CV: Ei Phyu Phyu Khaing - Trade Manager, Sales Supervisor (MT).pdf'),
('Aye Nyein Thu', 'ayenyeinthu0099@gmail.com', '09677680729', 'Management', 'git, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Aye Nyein Thu - Sales & Marketing (MT).pdf'),
('Aung Paing Oo', 'aungpaingoo12499@gmail.com', '09423683193', 'Engineering', 'python, mongodb, mysql, postgresql, sql, aws, docker, kubernetes, git, communication', 'active', 'CV Lead Tracker', 'CV: Aung_Paing_Oo - Deovps Engineer (MT).pdf'),
('Pa Pa Wady Cashier', 'papawadi751@gmail.com', NULL, 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Pa Pa Wady - Cashier (TGI).pdf'),
('Wah Wah Htwe', 'yinsnaing99@gmail.com', '09660989464', 'Education', 'excel', 'active', 'CV Lead Tracker', 'CV: Wah Wah Htwe - Junior Executive (MLM).pdf'),
('Yoon Eden Htoo', 'yoonedenhtoo27@gmail.com', NULL, 'Operations', 'aws, excel, communication, project management, problem solving', 'active', 'CV Lead Tracker', 'CV: Yoon Eden Htoo - Executive Asssitant (MT).pdf'),
('N Lin Aung Noc', 'sanlinaungucstgo@gmail.com', '09663892498', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: San Lin Aung - NOC (MT).pdf'),
('Thandar Myo Hr', 'yoemyo838@gmail.com', '09693430461', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Thandar Myo - HR Assistant (MT).pdf'),
('Htet Oo Khin Operation', 'Mehtetookhin1997@gmail.com', '09251447352', 'Management', 'git, excel, communication', 'active', 'CV Lead Tracker', 'CV: Htet Oo Khin - Operation Executive (MT).pdf'),
('Mya Yadanar Oo', 'myayadanar191@gmail.com', '959451613191', 'HR & Admin', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Mya Yadanar Oo - Customer service manager (MT).pdf'),
('Thin Htet Zar', '3@gmail.com', '09776160922', 'Management', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Thin_Htet Zar - B2B Sales Manager (MT).pdf'),
('Race - Myanmar', NULL, '09674622186', 'Customer Service', NULL, 'active', 'CV Lead Tracker', 'CV: Nant Htet Hsu Mon - English Translator (MT).pdf'),
('Nandar Myat Maung Hr', 'ataung93@gmail.com', NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Nandar Myat Maung - HR Assistant (NPT) MT.pdf'),
('System Engineer', 'moemyintmaungz@gmail.com', '09972005941', 'Management', 'sql', 'active', 'CV Lead Tracker', 'CV: Moe Myint Maung - IT Administrator (MT).pdf'),
('N N Aye', 'Avrilsan877@gmail.com', NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: CV San San Aye-Finance Manager (MT).pdf'),
('Educationsaw Win Latt', 'winlat238@gmail.com', '09975809426', 'Sales & Marketing', 'git, communication', 'active', 'CV Lead Tracker', 'CV: Saw Win Lat - Digital Marketing Asssitant (MT).pdf'),
('Paing Soe Oo', 'paingsoeoo.coc123@gmail.com', '09696660550', 'Management', 'excel, leadership, communication, project management', 'active', 'CV Lead Tracker', 'CV: Paing Soe Oo - Corporate RM (MT).pdf'),
('Race - Kareen', 'sawbawelukwe@gmail.com', '09954568764', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Saw Bawe Lukwe - Territiory Sales R (MT).pdf'),
('Khin Thuzar Lwin Secretary', 'khinthuzarlwin7@gmail.com', '09798893630', 'HR & Admin', 'communication', 'active', 'CV Lead Tracker', 'CV: Khin Thuzar Lwin -Secretary (MT).pdf'),
('Nay Yee Hlaing', 'nayyeefay@gmail.com', NULL, 'Management', 'excel, powerpoint, leadership', 'active', 'CV Lead Tracker', 'CV: Nay Yee Hlaing - Corporate Relationship Manager (MT).pdf'),
('Phyoe Thinzar Oo', NULL, NULL, 'HR & Admin', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Phyoe Thinzar Oo - HR & Admin (MDY).pdf'),
('Aung Phyo Kyaw', 'aungphyok836@gmail.com', '09768766865', 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Aung Phyo Kyaw - Manager Financial Advisor (MT).pdf'),
('W Ye Tun Procurement', NULL, '9404594649', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Saw Ye Tun-Procurement Executive(MT).pdf'),
('I Win Aung Portfolio', 'saiwinaungmm@gmail.com', '09777739971', 'Management', 'excel, leadership, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Sai Win Aung - Portfolio Manager.pdf'),
('Procurement M', 'nawchitpann@gmail.com', NULL, 'Operations', 'excel, powerpoint, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: NAW+CHIT+PAN+CHO - Procurement M (MT).pdf'),
('N.r.c No. - 12/aasana(n)250709', 'khinyadanarwin351@gmail.com', '09265838328', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Khin Yadanar Win - Page Admin (MT).pdf'),
('Htain Lin Oo', 'htainlin1998@gmail.com', NULL, 'Sales & Marketing', 'react, excel, communication', 'active', 'CV Lead Tracker', 'CV: HTAIN LIN OO - Sales Executive (MT).pdf'),
('Hnin Ei Khaing Procurement', 'hnineikhaing0999@gmail.com', '09966019148', 'Sales & Marketing', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Hnin Ei Khaing - Procurement Executive (MT).pdf'),
('Than Than Sel', 'thanthansel@gmail.com', '09969622629', 'Management', 'git, excel, photoshop, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Than Than Sel_Sales Operation Supervisor (Senior Sales Admin)MT.pdf'),
('Kyaw Zin Latt(mr)', 'kyawzinlatt.kzl286@gmail.com', NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Kyaw Zin Latt - M & E Engineer (MT).pdf'),
('Yar Zar Myo Htet', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Yar Zar Myo Htet - Sales Leader (MT).pdf'),
('Hsu Hsu Nadi Payroll', '99@gmail.com', '959420206757', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Hsu Hsu Nadi - Payroll Assistant (MT).pdf'),
('Kay Zin Han Qa', 'kayzin96@gmail.com', '09797390440', 'Management', 'excel, powerpoint, leadership', 'active', 'CV Lead Tracker', 'CV: Kay Zin Han - QA Manager (MT).pdf'),
('May Oo Hlaing', 'theone.one25@gmail.com', '+959400041752', 'Sales & Marketing', 'communication, problem solving', 'active', 'CV Lead Tracker', 'CV: May Oo Hlaing - Corporate Sales Executive (MT).pdf'),
('Jue Jue Nwe', 'juejue2511995@gmail.com', '09977160166', 'Management', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Jue Jue Nwe - Finance Assistant (MT).pdf'),
('Personal Details', 'khinmyomyokhine662018@gmail.com', NULL, 'HR & Admin', 'aws, excel', 'active', 'CV Lead Tracker', 'CV: Khin Myo Myo Khaing - HR Assistant (HTY)MT.pdf'),
('Content Writing', NULL, NULL, 'Sales & Marketing', 'git, leadership', 'active', 'CV Lead Tracker', 'CV: Ei Mon Kyaw - Digital Marketing Executive (MT).pdf'),
('Sanchaung Township, Yangon.', 'eithinzarbo31@gmail.com', '959788138937', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Ei Thinzar Bo - HR Execuitve (MT).pdf'),
('S Pay Roll', 'layaungshinthant.freelancer@gmail.com', '09688973552', 'Management', 'git, excel, communication', 'active', 'CV Lead Tracker', 'CV: La+Yaung_s - Pay roll assistant (MT).pdf'),
('Zaw Myo Htet Hr', 'zaw6709838@gmail.com', '09989998262', 'HR & Admin', 'communication', 'active', 'CV Lead Tracker', 'CV: Zaw Myo Htet - HR Assistant (MT).pdf'),
('Ksm Network Engineer', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: ksm - Network Engineer (MT).pdf'),
('Zuzuhlaing Cashier', 'zuzuhlaing62@gmail.com', NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: zuzuhlaing - Cashier NPT (MT).pdf'),
('Name -ma April Htun', NULL, '09665819019', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: April Htun - Showroom Sales Staff (MT).pdf'),
('Nyein Thinzar Trade Data', NULL, '09951108932', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Nyein Thinzar - Trade Data.pdf'),
('Father Name', NULL, '09954038880', 'Engineering', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: Zin Phyo Oo - IT Admin (MT).pdf'),
('Nrc No. : 12/lamana(n)161668', 'htetnandar942@gmail.com', '09756004823', 'General/Other', 'photoshop', 'active', 'CV Lead Tracker', 'CV: Htet Nadandar Kyaw - Data Entry (MT).pdf'),
('Zaw Myo Khaing', 'zawzaw200.mm@gmail.com', '09403560551', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Zaw Myo Khaing - Junior HR Associate (MT).pdf'),
('Ko Kyaw', 'winkyawthu1991@gmail.com', '09440553343', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: ko kyaw - Sales & Marketing (MT).pdf'),
('Ei Pyae Phyo', NULL, NULL, 'Management', 'sql, excel, communication', 'active', 'CV Lead Tracker', 'CV: Ei Pyae Phyo - Finance Manager (Insurance)MT.pdf'),
('May Myat Noe', 'maymyattnoe6@gmail.com', '09969672478', 'HR & Admin', 'aws, communication', 'active', 'CV Lead Tracker', 'CV: May Myat Noe - Sales Manager (MDY)MT.pdf'),
('Ye Ye Pyone', NULL, '09969773706', 'HR & Admin', 'excel, powerpoint, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Ms.Naw Ye Ye Pyone - Executive Pathein.pdf'),
('Paing Paing Lin', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Paing Paing Lin (Life Palnner).pdf'),
('Phyoe Myat No No', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Phyoe Myat No No - Junior Engineer (MT).pdf'),
('Shwe Sin Win Ei', 'shwesinwinei173@gmail.com', '6580748902', 'Customer Service', 'communication', 'active', 'CV Lead Tracker', 'CV: Shwe Sin Win Ei - Executive Assistant (MT).pdf'),
('Tin Aung Myint', NULL, NULL, 'Engineering', 'excel, powerpoint, communication, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: Tin Aung Myint - Site Engineer (MT).pdf'),
('Shoon Lei May Data', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Shoon Lei May - Data Entry (MT).pdf'),
('Yu Nandar Htun Cashier', 'yunandarhtun.02@gmail.com', '959458041122', 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Yu Nandar Htun- Cashier (TGI).pdf'),
('Su Yin Aye', NULL, '9772000282', 'Sales & Marketing', 'git, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Su Yin Aye - Sales Manager (MT).pdf'),
('Carrer Experience', 'sumyatkhinkhin87@gmail.com', '09797592340', 'Management', 'communication, analytical', 'active', 'CV Lead Tracker', 'CV: SU MYAT KHIN KHIN - QA (MT).pdf'),
('Zin Zin Oo', 'zinzinoo86@gmail.com', '09959564495', 'Sales & Marketing', 'git, excel', 'active', 'CV Lead Tracker', 'CV: Zin Zin Oo - Sales Admin (MT).pdf'),
('Personal Information', 'kndz.kndz.kndz@gmail.com', '09978800488', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: KNDZ - Inventory Controller.pdf'),
('Pann Nu Wai Hr', 'pannuwai971537@gmail.com', NULL, 'HR & Admin', 'aws, excel, communication', 'active', 'CV Lead Tracker', 'CV: Pann Nu Wai - HR Manager (MT).pdf'),
('Ei Thinzar Phyo Hr', '0@gmail.com', '09768984884', 'HR & Admin', 'communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Ei Thinzar Phyo - HR Executive (MT).pdf'),
('Aung Kyaw Lin Hr', 'aungkya12240@gmail.com', '09777154533', 'Management', 'git, excel, leadership', 'active', 'CV Lead Tracker', 'CV: Aung Kyaw Lin - HR Manager (MT).pdf'),
('Yin Hnin Wai Procurement', 'yhwai1992@gmail.com', '09787707868', 'Management', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Yin Hnin Wai - Procurement Executive (MT).pdf'),
('Hnin Moe Swe Marketing', 'khinmoe3653@gmail.com', '09961263653', 'Sales & Marketing', 'communication', 'active', 'CV Lead Tracker', 'CV: Hnin Moe Swe - Marketing Executive (Makro).pdf'),
('Assistant Sales Manager', NULL, '09966109057', 'Sales & Marketing', 'excel, problem solving', 'active', 'CV Lead Tracker', 'CV: Thet Myat Noe - Corporate Sales (MT) (1).pdf'),
('Lwin Thuzar Win Corporate', 'lwinthuzarwinkha@gmail.com', '09443246640', 'Sales & Marketing', 'leadership, communication, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: Lwin Thuzar Win - Corporate RM (MT).pdf'),
('Aye Chan Maw', 'shweeainlinn080@gmail.com', '09766679342', 'Customer Service', 'excel', 'active', 'CV Lead Tracker', 'CV: Aye Chan Maw - Sales Admin (MT).pdf'),
('Personal Particulars', 'ttso777@gmail.com', '959420102356', 'Management', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Thaw Tar Soe Oo - Portfolio Manager (MT).pdf'),
('Win Pa Pa Qa', NULL, NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Win Pa Pa - QA (MT).pdf'),
('Kyaw Min Swe', 'Kyawminswe936@gmail.com', '09940740618', 'Management', 'git, excel, project management, problem solving', 'active', 'CV Lead Tracker', 'CV: Kyaw Min Swe - Sales & M Manager (MT).pdf'),
('Yu Nandar Aung Hr', 'aungyunandar026@gmail.com', '09254481712', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Yu Nandar Aung - HR Executive (MT).pdf'),
('Thomas Digital M', 'bawiliansang93@gmail.com', '95943223443', 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Thomas - Digital M (MT).pdf'),
('Hnin Myat Wai Hr', 'hninmratwai@gmail.com', '09896267731', 'General/Other', 'java, javascript, express, mysql, sql, communication', 'active', 'CV Lead Tracker', 'CV: Hnin Myat Wai - HR Intern (MT).pdf'),
('Race - Myanmar', NULL, '09766765070', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Thu Min - Modern Trade Sales (MT).pdf'),
('Mya Bel Oo', 'myasabaloo.mm@gmail.com', NULL, 'Operations', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Mya Sabel Oo - Sales Admin (MT)1.pdf'),
('Chaw Nandar Min', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Chaw Nandar Min - Sales (Bago)MT (1).pdf'),
('N Thidar Aye Logistic', 'santhidaay@gmail.com', '0943033368', 'Management', 'aws, excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: San Thidar Aye- Logistic Manager (MT).pdf'),
('Myo Myint Myint Nyein', 'amelianyein1998@gmail.com', '09750204725', 'Management', 'excel, leadership, communication, project management, problem solving', 'active', 'CV Lead Tracker', 'CV: Myo Myint Myint Nyein - Sales Executive (MT).pdf'),
('Win Kyaw Kyaw Htun', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Win Kyaw Kyaw Htun - Inventory Controller.pdf'),
('Educa Tion', 'eithinzar.mdy16@gmail.com', NULL, 'Management', 'git, excel, leadership, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Ei Thinzar Myint Htet - Plaza Leasing & Media Executive (MT).pdf'),
('Htet Thiri Lwin Procurement', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Htet Thiri Lwin- Procurement Executive (MT).pdf'),
('Khin Su Su Hlaing', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Khin Su Su Hlaing - QA (MT).pdf'),
('Aye Thet Phoo Cashier', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Aye Thet Phoo - Cashier (MT).pdf'),
('Su Su Han Payroll', 'han.hanlay.su@gmail.com', '09420304297', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Su Su Han -Payroll Executive (MT).pdf'),
('Khin May Htet Aung', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Khin May Htet Aung - Junior HR Associate (MT).pdf'),
('Aung Phyo Thet', 'aunglay1995@gmail.com', '09795876496', 'Sales & Marketing', 'communication', 'active', 'CV Lead Tracker', 'CV: Aung Phyo Thet- Sales & Marketing (MT).pdf'),
('Myat Myint Moh Hann', 'Skillsmyatmyintmohannm@gmail.com', NULL, 'Management', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Myat Myint Moh Hann - Data Entry (MT).pdf'),
('Aye Thuzar Operation Supervisor', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Aye Thuzar - Operation Supervisor (MT).pdf'),
('Lae Lae Phyo', 'waic14961@gmail.com', '09751082368', 'HR & Admin', 'excel, powerpoint, photoshop, communication', 'active', 'CV Lead Tracker', 'CV: Lae Lae Phyo - Junior Site Egnieer (MT(.pdf'),
('Arkar Min Khant Credit', 'arkarminkhant181@gmail.com', '09677935521', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: CV - Arkar Min Khant - Credit officer.pdf'),
('Bank Advisor', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Hsu Waddy Naing - Bank Advisor (TGI)MT (1).pdf'),
('Pan Ei Phyu', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Pan Ei Phyu - Sales & Marketing (MT).pdf'),
('Thet Myo Wai', 'tmw7.net@gmail.comCONTACT', '09401639362', 'Healthcare', 'excel, leadership, communication, project management', 'active', 'CV Lead Tracker', 'CV: Thet Myo Wai - Sales (MT).pdf'),
('No.2 Main Road,bandula', 'pyaesonekhine13602@gmail.com', '959428165687', 'Management', 'communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Pyae Sone Khine - Corporate Sales Executive (MT).pdf'),
('Thet Yu Yu Tun', 'thetyulay@gmail.com', NULL, 'HR & Admin', 'communication', 'active', 'CV Lead Tracker', 'CV: Thet Yu Yu Tun - Customer Service Executive (MT).pdf'),
('Thu Ko Latt Telecom', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Thu ko latt - Telecom Maintain Eng (MT).pdf'),
('Myo Zaw Oo', 'ngamyo.mz@gmail.com', '959256380232', 'Management', 'mysql, sql, aws, azure, communication', 'active', 'CV Lead Tracker', 'CV: Myo Zaw Oo_Senior System Engineer (MT).pdf'),
('Hsu Htoo Nadi Portfolio', 'hsuhtoo.mm@gmail.com', '09423847783', 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Hsu Htoo Nadi - Portfolio Manager (MT).pdf'),
('Phyo Aung Network', 'phyoahng619634@gmail.com', '09790782027', 'Engineering', 'mysql, sql, excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Phyo Aung - Network (MT).pdf'),
('Tun Zaya Cashier', 'a.ptn@gmail.com', '09977214143', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Tun Zaya - Cashier (Pathein)MT.pdf'),
('Wai Wai Warehouse Supervisor', 'wai457950@gmail.com', '09894750118', 'Management', 'excel, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: Wai Wai - Warehouse Supervisor (MT).pdf'),
('Kan Sez Aung Hr', NULL, NULL, 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Kan Sez Aung - HR Manager (MT).pdf'),
('Htun Htun', NULL, NULL, 'Engineering', 'communication, project management, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: Htun Htun Cv .pdf'),
('W Thein Win Tun', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Saw Thein Win Tun _ UI_UX - MT.pdf'),
('Lin Mg', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Lin Mg - Sales & Marketing (MT).pdf'),
('Soe Moet Moet Win', 'novemberone95@gmail.com', NULL, 'Management', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Soe-Moet-Moet-Win.pdf'),
('Ko Htein Lin Tauk', 'hteinlintauk.civil.eng@gmail.com', '09441388948', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Htain Lin Tauk - Site Engineer (MT).pdf'),
('Thonn Recruitment', 'thonnshwes@gmail.com', '09677026303', 'HR & Admin', 'communication', 'active', 'CV Lead Tracker', 'CV: Thonn - Recruitment (MT).pdf'),
('Kyawt K Khaing Win', 'kyawtkkhaing13@gmail.com', NULL, 'Management', 'git, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Kyawt Kay Khaing - Head of Marketing Manager (MT).pdf'),
('Kyi May Aung Merchandising', 'Kyimayaung291166@gmail.com', '09964815824', 'Management', 'excel, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Kyi May Aung - Merchandising Executive (MT).pdf'),
('Shwe Poe Htel Lpo', 'shwepoehtel5120@gmail.com', '09977424193', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Shwe Poe Htel - LPO (Taungoo)MT.pdf'),
('Yu Yu Phyo', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Yu Yu Phyo - Sales Admin (MT).pdf'),
('Khin Phone Pyae Kyaw', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Khin Phone Pyae Kyaw - English Translator (MT).pdf'),
('Kyaw Zin Thant', NULL, '09774926521', 'Engineering', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Kyaw Zin Thant - Inventory Controller.pdf'),
('Zin Zin Zaw Thant', 'jiwoo2281@gmail.com', '9443705771', 'Healthcare', 'communication', 'active', 'CV Lead Tracker', 'CV: Zin Zin Zaw Thant - Sales & Cashier (MT).pdf'),
('University Thanlyin Technological University', NULL, NULL, 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: SAW KWAL SAY - Electrical Engineer (MT).pdf'),
('About Me', NULL, NULL, 'HR & Admin', 'project management', 'active', 'CV Lead Tracker', 'CV: Aung Bhone Nyo - Content Writer (TGI)MT.pdf'),
('Race - Myanmar (intha)', NULL, '0967927171', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Kabyar Pyae Moe - Non Buying (MT).pdf'),
('Htoo Pyae Shan Cashier', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Htoo Pyae Shan - Cashier (MT).pdf'),
('Pa Pa Cashier', 'papawadi751@gmail.com', NULL, 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Pa Pa Cashier.pdf'),
('Dagon University', 'naung2.tnw@gmail.com', NULL, 'Engineering', 'excel, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Tun Naing Win -Pre Sechool (MT).pdf'),
('Dr. Wai Yan Htun', 'anhtun9999@gmail.com', '9795625332', 'Management', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: Dr Wai Yan Htun - Deputy Banca Head (MT).pdf'),
('Zaw Htet Aung Recruiter', 'zawhtutaung785@gmail.com', '09425800974', 'HR & Admin', 'communication', 'active', 'CV Lead Tracker', 'CV: Zaw Htet Aung - Recruiter (MT).pdf'),
('Swe Swe Aung', 'swesweaung172@gmail.com', '09790361090', 'Management', 'aws, git, communication, project management', 'active', 'CV Lead Tracker', 'CV: Swe Swe Aung - Recruitment Specialist (MT).pdf'),
('Hnin Pwint Phyu', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Hnin Pwint Phyu - Portfolio Financial Manager (MT).pdf'),
('Professional Experience', 'eieimoemyint.acc2468@gmail.com', '9260779613', 'Management', 'git, excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Ei_Ei Moe Myint - Logistic Supervisor (MT).pdf'),
('Mar Mar Khaing Qa', 'marmarkhaing194@gmail.com', '09256262307', 'Engineering', 'communication', 'active', 'CV Lead Tracker', 'CV: Mar Mar Khaing - QA (MT).pdf'),
('N.r.c : 14/phapana(n)155410', 'kyawzawkhant29@gmail.com', '9250590887', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Kyaw Zaw Khant - Maintaiance Engineer (MT).pdf'),
('Aye Aye Nwe Hr', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Aye Aye Nwe - HR Executive (MT).pdf'),
('Phyo Khant Aung Noc', 'phyokhanta966@gmail.com', '09756973631', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Phyo Khant Aung - NOC Engineer (MT) (1).pdf'),
('Khine Thitr Zaw Cashier', 'khaingthitsarzaw38@gmail.com', '09792506141', 'HR & Admin', 'communication', 'active', 'CV Lead Tracker', 'CV: Khine Thitsar Zaw -Cashier (MT).pdf'),
('Bhonemyatkaung', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: BhoneMyatKaung _CV _Master - construction purchaser.pdf'),
('Aung Thu Hr', 'stnmzaw@gmail.com', '09772277117', 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Aung Thu - HR Manager (MT).pdf'),
('Hnin Thidar Hlaing Hr', 'hninpwint2322021@gmail.com', '09767191223', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Hnin Thidar Hlaing - HR Assistant (MT).pdf'),
('Ye Naung Htwe', 'yenaunghtwe@outlook.com', '9421048968', 'Engineering', 'leadership, communication, project management, problem solving', 'active', 'CV Lead Tracker', 'CV: Ye Naung Htwe - Senior NOC Engineer (MT).pdf'),
('Religion Buddhist', 'yatil6550@gmail.com', '09256389198', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Tin Zar Aung _ HR Admin (MDY)MT.pdf'),
('Curriculum Vitae', NULL, '09959966674', 'General/Other', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Phyo Pa Pa San- Data entry (MT).pdf'),
('Hsu Luck Pyae', NULL, '959783312890', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Hsu Luck Pyae - Manager Financial Advisor (MT).pdf'),
('Nyo Lin Aung Data', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Nyo Lin Aung - Data Collector (Team Leader )MT.pdf'),
('Nwe Nwe Win', NULL, '09791040642', 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Nwe Nwe Win- Customer Service (MT).pdf'),
('Zin Mar Lwin', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Zin Mar Lwin - Manager FA (MT).pdf'),
('Oakker Noc', NULL, NULL, 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Oakker  - NOC (MT).pdf'),
('Nyein Myo Htwe', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Nyein Myo Htwe - Senior Financial A (MT).pdf'),
('Min Thant Hr', 'Yangonminthantaung785690@gmail.comP', '+959777161462', 'HR & Admin', 'aws, communication', 'active', 'CV Lead Tracker', 'CV: Min Thant - HR Assistant (MT).pdf'),
('Su Su Han Hr', 'han.hanlay.su@gmail.com', '09420304297', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Su Su Han - HR Executive (MT).pdf'),
('Moe Moe Than Cashier', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Moe Moe Than - Cashier (NPT)MT.pdf'),
('Hanny Cho Noc', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Hanny Cho - NOC (MT).pdf'),
('Snow Win Non Buying', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Snow Win - Non Buying (MT).pdf'),
('Aung Ye Naing', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Aung-Ye-Naing-CV.pdf'),
('Tlcc Computer Center', 'shweyaminaye2411@gmail.comMa', '09960775112', 'Customer Service', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Ma Shwe Yamin - Call center (MT).pdf'),
('Phyu Phyu Win Engineer', 'phyuphyubgn95@gmail.com', '959401797225', 'Engineering', 'excel, photoshop, communication', 'active', 'CV Lead Tracker', 'CV: Phyu Phyu Win- Engineer (MT).pdf'),
('Content Information', 'thankyaw00766@gmail.com', '09448451907', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Khun Than Kyaw Lin - Data Collector (Hlaing)MT.pdf'),
('Personal Information Profile', 'maytzin27@gmail.com', '959883555915', 'HR & Admin', 'excel, photoshop, illustrator', 'active', 'CV Lead Tracker', 'CV: May Tha Zin Aung - HR Assistant (Mayangone)MT.pdf'),
('Thinnayat Digital Marketing', 'anantwithtyn@gmail.com', '09425079653', 'Management', 'git, communication', 'active', 'CV Lead Tracker', 'CV: Thinnayat - Digital Marketing (MT).pdf'),
('Race - Myanma R', NULL, '09775116988', 'Management', 'leadership', 'active', 'CV Lead Tracker', 'CV: Cho Cho Lwin - Corporate RM (MT).pdf'),
('Poe Poe Thaw', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Poe Poe Thaw - Sales Admin (MT).pdf'),
('Pazundaung Township. Yangon', 'htetwinlwin@gmail.com', '959696793489', 'Engineering', 'communication, project management', 'active', 'CV Lead Tracker', 'CV: Htet Win Lwin - System Engineer (MT).pdf'),
('Youth International College.', 'heinlintun1999@gmail.com', '09779941458', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Hein Lynn Htun - NOC Engineer (MT).pdf'),
('Phyu Thwe Hnin Marketing', 'phyuthwehnin16@gmail.com', '9795878252', 'Sales & Marketing', 'git, excel, communication', 'active', 'CV Lead Tracker', 'CV: Phyu Thwe Hnin - Marketing Manager (MT).pdf'),
('Street, Sanchaung Township, Yangon', 'Eimyatthu1815@gmail.com', '09971373773', 'Management', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Ms. Ei Myat Thu -Corporeate RM (MT).pdf'),
('Thae Thae Khaing Lpm', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Thae Thae Khaing - LPM (MT).pdf'),
('Nway Nway Lwin Qc', 'nwaynwaylwin259@gmail.com', '09788119960', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Nway Nway Lwin - QC (MT).pdf'),
('Htun Htun Aung Ass', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Htun Htun Aung - Ass Warehouse Manager (MT).pdf'),
('Single Male', 'mr.shinekoko422@gmail.com', '959666946850', 'Management', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: Shine Ko Ko - NOC Engineer (MT).pdf'),
('Aung N Tun', 'astz.heartface@gmail.com', NULL, 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Aung San Tun - Sales Manager.pdf'),
('Htet Wai Yan Territory', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Htet Wai Yan - Territory Sales (MT).pdf'),
('St,1qt,namsang,south Shan', 'zinkokooo347@gmail.com', '+959979410317', 'Management', 'leadership', 'active', 'CV Lead Tracker', 'CV: Zin Ko Ko Oo - Area Manager (Banca - TGI)MT.pdf'),
('Thet Su Aung', NULL, '09797043527', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Thet Su Aung - Manager FA (MT).pdf'),
('Shin Thant Tun', 'shinthanttun85@gmail.com', '+959258534688', 'Engineering', 'git, excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Shin Thant Tun (CV) - MT.pdf'),
('Ndi Aung Vice President', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Sandi Aung - Vice President (MT).pdf'),
('Thawkhantaungqa Hanni Cho Referral', 'thawkhantaung.tk@gmail.com', '9799366421', 'Engineering', 'problem solving', 'active', 'CV Lead Tracker', 'CV: ThawKhantAungResume- QA (MT) Hanni Cho referral.pdf'),
('Nwe Ni Win Data', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Nwe Ni Win - Data Collector (Hlaing)MT.pdf'),
('Nyi Nyi Paing Media', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Nyi Nyi Paing - Media Production Specilaist (MT).pdf'),
('Ei Ei Phyo Maung', 'eieiphyomaung9@gmail.com', '09965642471', 'Management', 'excel, powerpoint, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Ei Ei Phyo Maung _- HR Executive (D).pdf'),
('Zin Lai Tun Customer', NULL, NULL, 'Customer Service', NULL, 'active', 'CV Lead Tracker', 'CV: Zin Lai Tun - Customer Service (MT).pdf'),
('Career Objectives', 'kaythinann1990@gmail.com', NULL, 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Kay Thi Nann - Deputy Head of Banca (MT).pdf'),
('Thu Ya Swe', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Thu Ya Swe (Life Planner).pdf');