-- ============================================
-- CV Lead Tracker - Batch 3 of 5
-- Leads 1001 to 1500
-- ============================================

INSERT INTO leads (name, email, phone, current_position, skills, status, source, notes) VALUES
('Pann Myat Thwe', 'panmyatthu8@gmail.com', NULL, 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Pann Myat Thwe - Customer Service (MT).pdf'),
('Wai Yan Htet', 'waig94280@gmail.com', NULL, 'Management', 'leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Wai Yan Htet - Manager FA (MT).pdf'),
('Working Experience', 'hninwaiwaihninwaiwai1@gmail.com', '09898081355', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Hnin Wai Wai (Non Buying Customer Service).pdf'),
('Min Zaw Telecom Maintaincance', NULL, NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Min Zaw - Telecom Maintaincance Engineer (MT).pdf'),
('Wai Yan Kyaw', 'waiyankyaw856@gmail.com', NULL, 'HR & Admin', 'excel, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Wai Yan Kyaw-CV-Hr Assistant (MT).pdf'),
('Hnin Wai Hlaing Hr', 'hninwaihlaing008@gmail.com', '09968162497', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Hnin Wai Hlaing - HR Manager (MT).pdf'),
('Ndar Aung Ca', 'llamin727@gmail.comEmail', NULL, 'Management', 'excel, powerpoint, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Sandar Aung - CA (MDY)MT.pdf'),
('Arkar Min Maung', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Arkar Min Maung - Senior FA (MT).pdf'),
('Myint Zaw', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Myint Zaw - Senior Financial A (MT).pdf'),
('Min Khant Thaw Maintainance', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Min Khant Thaw - Maintainance Techanician(MT).pdf'),
('Hein Htet Aung', NULL, NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Hein Htet Aung 1- NOC Engineer (MT).pdf'),
('Myo Hlaing Win', 'yumpycoe38@gmail.com', '09793310557', 'Management', 'leadership, communication, project management', 'active', 'CV Lead Tracker', 'CV: Myo Hlaing Win - Senior Network Engineer (MT).pdf'),
('Yu Htet Htet Soe', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Yu Htet Htet Soe - Office Cashier (MT).pdf'),
('Ex Perience', 'Yangonzwelk96805@gmail.comCO', '09963767533', 'Engineering', 'photoshop', 'active', 'CV Lead Tracker', 'CV: Zwel Wanna Kyaw - Media Production Specialist (MT).pdf'),
('Nway Ei Ei Tun', 'nwayeieitun25@gmail.com', '09975473064', 'Engineering', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Nway Ei Ei Tun - Senior Network Engineer (MT).pdf'),
('Nilar Win', 'nilarwin3@gmail.com', '959799652577', 'HR & Admin', 'communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Nilar Win - Executive Assistant (MT).pdf'),
('Nwe Nwe Htun Hr', NULL, '09788205707', 'Management', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: Nwe Nwe Htun - HR Executive (MT).pdf'),
('I Nay Lin', 'sainaylin522@gmail.com', '09963700003', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Sai Nay Lin - Sales Manager (MT).pdf'),
('Zu Zuu Zan Lps', NULL, '09696932182', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Zu Zuu Zan - LPS (MT).pdf'),
('Tun Tun Naing Qa', NULL, NULL, 'Engineering', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Tun Tun Naing - QA (MT).pdf'),
('Pann Phyu', NULL, '0969037174', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Pann Phyu - JA (NPT) MT.pdf'),
('Than Sin Myat', 'may20.myat@gmail.com', NULL, 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Than Sin Myat  - Sales Admin (MT).pdf'),
('Tun Myint Oo', 'tunmyintoo.jame@gmail.com', '9757972813', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Tun Myint Oo - Sales (MT).pdf'),
('Pan Ei Phyu Hr', 'babyeait2015@gmail.com', '09988581596', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Pan Ei Phyu - HR Executive (MT).pdf'),
('Nyi Nyi Lwin It', 'n2lwin88@gmail.com', '09767149907', 'Engineering', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Nyi Nyi Lwin - IT Assistant (MT).pdf'),
('Khine Thin Zar Phyo', NULL, '09771825484', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Khine Thin Zar Phyo - Cashier (Pathein) MT.pdf'),
('N Htar Yadanar Cashier', NULL, '09453441281', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: San Htar Yadanar - Cashier (MT).pdf'),
('Thet Htar Seer', 'thethtarseesar11@gmail.com', '9759878578', 'HR & Admin', 'java, excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Thet Htar Seesar (Resume) - Executive Assistant (MT).pdf'),
('Hnin Ma Rlar', 'hninmarlarkhine123@gmail.com', '09261969919', 'Management', 'agile, scrum, excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Hnin Malar Khine - HR Intern (MT).pdf'),
('Kyaw Moe Hein Portfolio', 'ukyawmoehein@gmail.com', NULL, 'Management', 'excel, powerpoint, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Kyaw Moe Hein - Portfolio Manager (MT).pdf'),
('Ei Thae Zin Hr', 'eithae1688@gmail.com', '09795947014', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Ei Thae Zin - HR Assistant (MT).pdf'),
('Ma Aye Myint Wai', 'ayemyintwai995@gmail.com', NULL, 'Management', 'git, excel, communication', 'active', 'CV Lead Tracker', 'CV: Ma Aye Myint Wai - QA (MT).pdf'),
('Thazin Phyu Qa', 'Thazinphyumay13@gmail.com', '09421754006', 'Engineering', 'excel, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Thazin Phyu-QA (MT).pdf'),
('Eaindra Soe Hr', 'soeeaindra148@gmail.com', '09984635598', 'HR & Admin', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Eaindra Soe - HR Assistant (MT).pdf'),
('Ma Thiri Myat Mon', 'thirimyatmon1@gmail.com', '09774361822', 'HR & Admin', 'communication', 'active', 'CV Lead Tracker', 'CV: Thiri Myat Mon - HR General Manager (MT).pdf'),
('Theint Thinzar Win Noc', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Theint Thinzar Win - NOC (MT).pdf'),
('Hsu Latt Toe', 'HsuLattToealpha.hsulatt@gmail.com', NULL, 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Hsu Latt Toe - Sales Manager (Agency)MT.pdf'),
('Thaw Thaw Myo Cs', 'o7@gmail.com', '09679159952', 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Thaw Thaw Myo - CS (MT).pdf'),
('Thandar Aung Modern Trade', 'sulay23385@gmail.com', '09
753628232', 'Management', 'git, excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Thandar Aung - Modern Trade Sales Sup (MT).pdf'),
('War War Naing Data', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: War War Naing - Data Collector (HTY)MT.pdf'),
('Wine Wine Chit', NULL, '959975589705', 'Management', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Wine Wine Chit - Senior Sales Executive (MT).pdf'),
('Hsu Yati Hr Intern', NULL, '09766676543', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Hsu Yati - HR Intern (MT).pdf'),
('Thant Sin Oo', NULL, '09422644423', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Thant Sin Oo - Sales & Marketing (MT).pdf'),
('Ye Htet Aung', 'eliotgrey9@gmail.com', '09692247429', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Ye Htet Aung - Junior QC (MT).pdf'),
('Ba Myanmar', NULL, '09403760322', 'Finance & Accounting', 'communication', 'active', 'CV Lead Tracker', 'CV: Noe Noe Kyi Thar Nyein - Cashier (NPT)MT.pdf'),
('Yunn Eindra', 'ppoe9442@gmail.com', '+959667687234', 'Sales & Marketing', 'git', 'active', 'CV Lead Tracker', 'CV: Yunn Eindra - Junior Site E (MT).pdf'),
('Mya Moe T Lps', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Mya Moe Sat - LPS (MT).pdf'),
('Office Staff(mr)thae Thiri Lwin', 'thaethirilwin44@gmail.com', '09449923054', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Thae Thiri_- Export & Import Coordinator (MT).pdf'),
('Khin Mar Zin', 'marzin.win@gmail.com', '09795477476', 'Finance & Accounting', 'git, analytical', 'active', 'CV Lead Tracker', 'CV: Khin Mar Zin - Finance Manager (MT).pdf'),
('Khin Thet Oo Hr', 'Khinthetoo871@gmail.com', '09262486917', 'Management', 'excel, photoshop', 'active', 'CV Lead Tracker', 'CV: Khin Thet Oo  - HR Executive (MT).pdf'),
('Chit N Win', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Chit San Win - Sales Team Leader (Mayangone)MT.pdf'),
('Name :yamonehninwaisoe', 'juejue2511995@gmail.com', '09977160166', 'Management', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Yamone Hnin Wai Soe - Corporate Sales (MT).pdf'),
('Aye Mya Kyi Cash', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Aye Mya Kyi - Cash Collecter, Data entry.pdf'),
('Phyo Lynn Aung', 'Phyolinaung978@gmail.com', '09799099252', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Phyo_Lynn_Aung_Sales Manager (MT).pdf'),
('Wutt Yee Oo Customer', 'wuttyeeoo.ygn@gmail.com', '09254500532', 'HR & Admin', 'aws, excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Wutt Yee Oo - Customer Care Executive (MT).pdf'),
('Zaw Moe Lwin', 'zawmoelwin202067@gmail.com', '09428167670', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Zaw Moe Lwin - Sales Engineer (MT).pdf'),
('Job Applied For', 'aungchunniwin16@gmail.com', '09255282795', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Chun Ni Win - Intern (MT).pdf'),
('About Me', 'aungwintcherry@gmail.com', '09954787097', 'Engineering', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: Wint Cherry Aung - NOC Engineer (MT).pdf'),
('Pyae Phyo Lwin', NULL, '959774335159', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: PYAE PHYO LWIN - Sales & Marketing (MT).pdf'),
('Thet Paing Swe', 'thetpaingswe88@gmail.com', '09421014547', 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Thet Paing Swe - Sales Manager (MT).pdf'),
('Wah Wah Lynn', 'wahwahlynn444@gmail.com', '+959420130345', 'Sales & Marketing', 'git, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Wah Wah Lynn - Salels & Marketing (MT).pdf'),
('Top Design Computer Training', 'yeewaiyantun1910@gmail.com', '09650887406', 'Sales & Marketing', 'git, excel, powerpoint, photoshop, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Yee Wai Yan Tun- IT Assistant (MT).pdf'),
('Thu Htoo N Hr', 'thuhtoosan.du@gmail.com', '09780373248', 'Management', 'excel, powerpoint, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Thu Htoo San - HR Executive (MT).pdf'),
('Naung Htwe', 'naunghtwe.ne@gmail.com', '9444418728', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Naung Htwe - Senior Network Engineer (MT).pdf'),
('Yimon Thwin Grapchic Designer', NULL, NULL, 'Design', NULL, 'active', 'CV Lead Tracker', 'CV: Yimon Thwin - Grapchic Designer (MT).pdf'),
('Documentation Export Import', 'myomyintaung220996@gmail.com', '959740953771', 'Management', 'excel, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Documentation export & import (MT).pdf'),
('Htet Hlaine Wai', NULL, '09977169288', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Htet Hlaine Wai  - Sales (MDY) MT.pdf'),
('Hannah Customer Service', 'moe.hannah98@gmail.com', NULL, 'Finance & Accounting', 'communication', 'active', 'CV Lead Tracker', 'CV: Hannah - Customer Service (MT).pdf'),
('Hein Htet Zin Customer', NULL, NULL, 'Customer Service', NULL, 'active', 'CV Lead Tracker', 'CV: Hein Htet Zin - Customer Service (MT).pdf'),
('Su Su Kyaw', NULL, '09977730461', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Su Su Kyaw - Manager Financial Advisor (MT).pdf'),
('Pyae Phyo Aung', NULL, '95955960621', 'Management', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Pyae Phyo Aung - Sales & Marketing (MT).pdf'),
('Soe Moe Marchandising', 'nangkhansein.suzan@gmail.com', '959453041174', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Soe Moe - Marchandising Manager (MT).pdf'),
('Thazin Wai Customer Service', 'thazinwai277@gmail.com', '09425051656', 'Customer Service', 'excel', 'active', 'CV Lead Tracker', 'CV: Thazin Wai - Customer Service (MT).pdf'),
('Phyu Pyae Sone Hr', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Phyu Pyae Sone - HR Intern (MT).pdf'),
('Thiha Htun Noc Engineer', NULL, NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Thiha Htun - NOC Engineer (MT).pdf'),
('Su San Thin', NULL, '09677741538', 'HR & Admin', 'git, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Su San Thin - Digital Marketing (MT).pdf'),
('Ei Mon Customer Service', 'stellaivy1512@gmail.com', '09425991835', 'HR & Admin', 'communication', 'active', 'CV Lead Tracker', 'CV: Ei Mon - Customer Service (MT).pdf'),
('Yi Yi Win', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Yi Yi Win (Cashier).pdf'),
('Mya Thandar', 'myathandar512@gmail.com', '09799824179', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Mya Thandar - HR & Admin Executive (MT).pdf'),
('Thukhaaung Web Devleoper', 'Myanmarthukhaaung542981@gmail.com', '+959265710713', 'Engineering', 'git, excel, project management, problem solving', 'active', 'CV Lead Tracker', 'CV: ThukhaAung Web Devleoper (MT).pdf'),
('Myat Noe Khine', NULL, NULL, 'Engineering', 'python, java, javascript, mysql, sql, docker, communication', 'active', 'CV Lead Tracker', 'CV: Myat Noe Khine - Junior Fronted Developer (MT).pdf'),
('Aung Ye Kyaw Hse', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Ye Kyaw - HSE Officer (MT).pdf'),
('Lwan Poe Poe Swe', NULL, '09971210528', 'Healthcare', NULL, 'active', 'CV Lead Tracker', 'CV: Lwan Poe Poe Swe - Sales Team Lead (YGN) MT.pdf'),
('Le And Customer Service', NULL, '09758580894', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Sale and customer service (MT).pdf'),
('Shwin Pyone Wai Portfolio', 'pyoneshwin03@gmail.com', '09788119018', 'Management', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Shwin Pyone Wai - Portfolio  Manager (MT).pdf'),
('Ko Ko Aung', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Ko Ko Aung (Inventory Controller, MT).pdf'),
('Khin Su Mon Cashier', NULL, '09954074440', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Khin Su Mon - Cashier (NPT)MT.pdf'),
('Khaing Htun Hr', 'kkhainghr.1245@gmail.com', '959663686654', 'HR & Admin', 'excel, project management', 'active', 'CV Lead Tracker', 'CV: Ms.Khaing Khaing Htun - HR Manager (MT).pdf'),
('Shin Thant Htun', 'shinthanthtoo56@gmail.com', '9981399920', 'Management', 'java, javascript, mysql, sql, excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Shin Thant Htun - Sales (MDY) MT.pdf'),
('Honey Htun Corporate Les', 'honeyhtunpn@gmail.com', '+959956866112', 'Management', 'leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Honey Htun - Corporate Sales Executive (MT).pdf'),
('Zin Pwint Oo', NULL, '959425361710', 'Engineering', 'photoshop, communication', 'active', 'CV Lead Tracker', 'CV: Zun Pwint Oo - Interior Designer (MT).pdf'),
('Htut Lin Naing', NULL, '09753111828', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Htut Lin Naing - Inventory Controller.pdf'),
('New Hnin Wai', 'nwehninwai7@gmail.com', '0959938180', 'Management', 'express, excel, leadership', 'active', 'CV Lead Tracker', 'CV: Nwe Hnin Wai - Cost Analyst (MT).pdf'),
('May Myat Oo', 'oo.telenor@gmail.com', '09661832666', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: May Myat Oo- Senior Executive (Pathein).pdf'),
('Ma Thiri Oo Cashier', 'thirioo8834@gmail.com', '09453477060', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Ma Thiri Oo - Cashier (MT).pdf'),
('Personal Details', 'thet51730@gmail.com', '09789353671', 'Engineering', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Aye Aye Thet - Korean Translator (MT).pdf'),
('Dagon University, Yangon.', 'heintet@gmail.com', '959699372471', 'Sales & Marketing', 'git, photoshop', 'active', 'CV Lead Tracker', 'CV: Hein Htet Aung - Digital marketing (MT).pdf'),
('Mr. Kaung Set Htoo', 'kaungsethtoo00@gmail.com', '09952746538', 'Sales & Marketing', 'communication', 'active', 'CV Lead Tracker', 'CV: kaungsethtoo_.pdf'),
('Khaingzinthaw Cashier', 'khaingzint753@gmail.com', '09254717272', 'Sales & Marketing', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: KhaingZinThaw_Cashier (MT).pdf'),
('Myat Phone Thit', 'mr.myatphone.mm@gmail.com', '9978120174', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Myat Phone Thit  - Site Engineer (MT).pdf'),
('Tin Tun Naing', 'tintunnaing2024@gmail.com', '09250172310', 'Engineering', 'aws, azure, agile, scrum', 'active', 'CV Lead Tracker', 'CV: Tin-Tun-Naing-Senior System Engineer (MT).pdf'),
('Phyu Phyu Thant', NULL, NULL, 'Management', 'leadership', 'active', 'CV Lead Tracker', 'CV: Phyu Phyu Thant - Sales Manager (Agency)MT.pdf'),
('Hnin Wai Wai Lwin', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Hnin Wai Wai Lwin - HR Executive - HTY (MT).pdf'),
('Nott Myat Htun', NULL, '09691403690', 'Management', 'excel, powerpoint, problem solving', 'active', 'CV Lead Tracker', 'CV: Nott Myat Htun- Sales Team Leader (MT).pdf'),
('Shoon Lae Phyu Cashier', '5@gmail.com', '959890235209', 'Sales & Marketing', 'problem solving', 'active', 'CV Lead Tracker', 'CV: Shoon Lae Phyu - Cashier (MT).pdf'),
('Customer Serviceaung Phyo Paing', NULL, '09765602148', 'Sales & Marketing', 'communication', 'active', 'CV Lead Tracker', 'CV: Aung Phyo Paing-Head of Banca (MT).pdf'),
('Aung Ko Ko Myint', 'aungkokomyint30597@gmail.com', '9456123315', 'Management', 'leadership, communication, project management, analytical', 'active', 'CV Lead Tracker', 'CV: Aung Ko Ko Myint_s - Senior NOC Engineer (MT).pdf'),
('Moe Ndar Aye Hr', 'moesandar7991@gmail.com', '09974397553', 'HR & Admin', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Moe Sandar Aye - HR Executive (MT).pdf'),
('Eindra Khin', NULL, '09978509445', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Eindra Khin - Sales (MT).pdf'),
('Yaminn Nwe', 'yaminn497@gmail.com', '09953151065', 'Management', 'git, excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Yaminn Nwe - Sales (Lub) MT.pdf'),
('Ngwe Min Soe', NULL, NULL, 'Engineering', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Ngwe Min Soe - NOC Engineer (MT).pdf'),
('Thamine, Muditar Housing, Yangon', 'Johnbawi2018@gmail.com', '959257562633', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Khamh Bawi Lian CV - M & E (MT).pdf'),
('Thura Aung Corporate Les', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Thura Aung - Corporate Sales Executive (MT).pdf'),
('Moe Wathan Oo', 'moewathan1177@gmail.com', '09756254282', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Moe Wathan Oo - HT & Admin Ass (MT).pdf'),
('Myo Khaing Qc Inspector', 'myokhaing1994623@gmail.com', '09954583720', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Myo Khaing - QC Inspector (MT).pdf'),
('Personal Details', 'aungthihakyi23@gmail.com', '09255830790', 'Management', 'git, leadership', 'active', 'CV Lead Tracker', 'CV: Aung Thi Ha Kyi (J executive Mawlamyine).pdf'),
('Thawda Htun Data Analyst', 'thvcs03@gmail.com', '09253092311', 'Management', 'mysql, sql, excel', 'active', 'CV Lead Tracker', 'CV: Thawda Htun - Data Analyst (MT).pdf'),
('Pwint Swe', 'pwintooswe.pp@gmail.com', NULL, 'Management', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: PWINT SWE  - Executive Assistant (MT).pdf'),
('Zwal Media Production', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Zwal - Media Production (MT).pdf'),
('Aung N Oo Noc', 'ko7123405@gmail.com', NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Aung San Oo - NOC (Bago)MT.pdf'),
('Le And Customer Service', NULL, '09758580894', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Sale and customer service.pdf'),
('Customer Service Skilleducation', 'ccmoe971@gmai.com', '09440740675', 'Engineering', 'problem solving', 'active', 'CV Lead Tracker', 'CV: Si Si Moe - NOC Engineer (MT).pdf'),
('Zayar Min Logistic', 'tharzayar2018@gmail.com', '09788450036', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Zayar Min - Logistic Assistant Manager (MT).pdf'),
('Thet Pwint Phyu', NULL, NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Thet Pwint Phyu - Senior Network Engineer (MT).pdf'),
('Hnin Wut Yee', 'eesoe29@gmail.com', '959697158909', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Hnin Wut Yee - Internal Audit (MT).pdf'),
('May Thu Kyaw', NULL, '959772491476', 'Engineering', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: May Thu Kyaw - Customer Service (Thanlyin)MT.pdf'),
('Hnin Phyu Sin Thant', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Hnin Phyu Sin Thant - Social Media Coordinator (MT).pdf'),
('Zaw Win Shein', NULL, '09777724220', 'Engineering', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Zaw Win Shein -Junior Sales Engineer(MT).pdf'),
('Nang Kay Khaing Moe', 'nangkaykhaingmoeaung@gmail.com', '0943123437', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Nang Kay Khaing Moe Aung - JA (MDY)MT.pdf'),
('Min Thu It Support', NULL, '09971137511', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Min Thu - IT Support (MT).pdf'),
('Myo Han Procurement M', NULL, '09420011803', 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Myo Han - Procurement M (MT).pdf'),
('Thazin Soe Hr', 'thazinsoe870@gmail.com', '09969471493', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Thazin Soe - HR & Admin Manager (HTY)MT.pdf'),
('Work Experience', 'low@unesis.com.sg', NULL, 'Management', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Phyo Thi Khing - English Translator (MT).pdf'),
('Ohnmar Phyo Hr', 'phyo311299@gmail.com', '959684900861', 'Sales & Marketing', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Ohnmar Phyo - HR Assistant (MT).pdf'),
('Myo Min Thu', 'myomynnthu@gmail.com', NULL, 'Management', 'express, aws, azure, project management', 'active', 'CV Lead Tracker', 'CV: Myo Min Thu - Senior System Engineer (MT).pdf'),
('Ma Tawe Tar Lin', 'tawetar6800@gmail.com', '09673766800', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Thant Hlaing Oo - IT Staff (MT).pdf'),
('Zaw Min Oo', 'zawmin111obey@gmail.com', NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Zaw Min Oo - Assistant Engineer (MT).pdf'),
('Si Thu Hein', 'sithuhein.leo@gmail.com', '09422549500', 'Sales & Marketing', 'git, excel, powerpoint, photoshop', 'active', 'CV Lead Tracker', 'CV: Si Thu Hein - Sales Supervisor (MT).pdf'),
('Win Arkar Han Procurement', 'Myanmar.winarkarhan2012@gmail.comI', NULL, 'Management', 'aws, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Win Arkar Han - Procurement Manager (MT).pdf'),
('Thant Zin Phyo Noc', 'thantzinphyo784@gmail.com', NULL, 'Engineering', 'java, javascript, mysql, sql, excel, powerpoint, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Thant Zin Phyo -NOC (MT).pdf'),
('Myo Thandar Aung Cashier', 'myothandaraung1996@outlook.com', '09799416522', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Myo Thandar Aung - Cashier (NPT).pdf'),
('Aung Pyae Phyo', 'Gentlemanfirstaung@gmail.com', '09442390190', 'Management', 'leadership', 'active', 'CV Lead Tracker', 'CV: Aung Pyae Phyo - Sales & Marketing (MT).pdf'),
('Aung Paing Soe', 'aungpaingsoe.jw@gmail.com', NULL, 'Sales & Marketing', 'git, excel, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Aung Paing Soe - Training Specialist (MT).pdf'),
('Hnin Oo Wai', 'hninoowai2911@gmail.com', NULL, 'Management', 'git, excel', 'active', 'CV Lead Tracker', 'CV: Hnin Oo Wai - Executive Assistant (MT).pdf'),
('Thiri Training', 'thiri4663@gmail.com', '09797045044', 'Management', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Thiri - Training Manager (MT).pdf'),
('Professional Experience', 'lwin.mmr@gmail.com', '959777047554', 'Management', 'excel, project management', 'active', 'CV Lead Tracker', 'CV: Lwin Ko Thu - Telecom Installation Eng (MT).pdf'),
('Kaung Si Thu Hr', 'kaungsithu.burmese@gmail.com', '09974601416', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Kaung Si Thu - HR Assistant (MT).pdf'),
('Chit Lin Oo', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Chit Lin Oo - Sales Team Leader (Mayangone)MT.pdf'),
('Network Engineer /itsupportspecialist', 'sitthmuenaing1993@gmail.co', '09781726062', 'Customer Service', 'communication, analytical', 'active', 'CV Lead Tracker', 'CV: Sitt Hmue Naing (Network Engineer )MT.pdf'),
('Hnin Wut Ye', NULL, '09758257234', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Hnin Wut Ye - Sales & Marketing (MT).pdf'),
('Tps Warehouse', 'thatpaingsoe994@gmail.com', '09798672679', 'Operations', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: TPS - Warehouse Manager (MT).pdf'),
('Yoon Thinzar Oo Marketing', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Yoon Thinzar Oo -  Marketing Executive (MT).pdf'),
('Perso N Al Facts', 'myathannwe1999@gmail.com', '09778305542', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Mya than nwe - Site Engineer (MT).pdf'),
('Aung Ko Ko', 'aungkoko98.aug@gmail.com', '09753664980', 'Management', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Aung Ko Ko - Sales Executive (MT).pdf'),
('Nrc : 2/damasa(n)060841', 'kaunghtetnyar@gmail.com', '09407379297', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Mg Kaung Htet Zaw - Cashier, no exp TGI.pdf'),
('May Pyae Sone', 'Email-margredkyaing@gmail.com', '959446322228', 'Sales & Marketing', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: May Pyae Sone - Sales (TGI).pdf'),
('Nyan Lin Han Marketing', NULL, NULL, 'Sales & Marketing', 'communication', 'active', 'CV Lead Tracker', 'CV: Nyan Lin Han - Marketing Executive (MT).pdf'),
('Curriculum Viate', 'eimyatmon.mm2019@gmail.com', NULL, 'Engineering', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Ei Myat Mon - English Translator (MT) (1).pdf'),
('May Ein Gyin', 'mayeingyin2699@gmail.com', '09769079102', 'Management', 'excel, leadership, project management', 'active', 'CV Lead Tracker', 'CV: MEG - Junior Drafer (MT).pdf'),
('Race - Myanmar', NULL, '09255437373', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Khaing Toe - Driver (MT) merge.pdf'),
('Chit Min Thu', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Chit Min Thu - Sales (MT).pdf'),
('Htate Htarr Oo Casheir', 'rnelay2324@gmail.com', '09977262111', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Htate Htarr Oo - Casheir (NPT)MT.pdf'),
('Work Experience', 'phoetharr34@gmail.com', '09969683831', 'Operations', 'communication', 'active', 'CV Lead Tracker', 'CV: tso - Warehouse Supervisor (MT) TTN referral.pdf'),
('Ko Ko Kyaw Win', '979@gmail.com', '6586214500', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: KO KO Kyaw Win Naing.pdf'),
('Thu Zar Nwe Hr', 'thuzarnwe28@gmail.com', '09256106316', 'HR & Admin', 'communication', 'active', 'CV Lead Tracker', 'CV: Thu Zar Nwe - HR Manager (MT).pdf'),
('Swan Htet Thu', 'swanhtetthu179731@gmail.com', '09423887780', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Swan Htet Thu - Sales (MT).pdf'),
('Thae Htet Hsu', 'thae.thae.is.here@gmail.com', '09966809701', 'Sales & Marketing', 'communication', 'active', 'CV Lead Tracker', 'CV: Thae Htet Hsu - Digital Marketing (MT).pdf'),
('Cho Nyan Wai', 'chonyanwai@gmail.com', NULL, 'Management', 'aws, leadership', 'active', 'CV Lead Tracker', 'CV: Cho Nyan Wai  - Finance Manager (MT).pdf'),
('Maythadar English Translator', 'aung999@gmail.com', '9607617553', 'Management', 'git, communication', 'active', 'CV Lead Tracker', 'CV: MayThaDar - English Translator (MT).pdf'),
('Seint Seint Myat Thwe', 'seintseint0202121@gmail.com', NULL, 'Management', 'excel, leadership, problem solving', 'active', 'CV Lead Tracker', 'CV: Seint Seint Myat Thwe - Sales Manager (MT).pdf'),
('Thet Htar English Translator', 'thet2626@gmail.com', '09943745245', 'General/Other', 'communication', 'active', 'CV Lead Tracker', 'CV: Thet Htar - English Translator (MT).pdf'),
('Seint Seint Myat Thwe', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Seint Seint Myat Thwe - Sales Supevisor (MT).pdf'),
('Yamin W I N', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Yamin Win Lei Cho (Graphic D) MT.pdf'),
('Naing Waiyan', 'naiwaiyan6@gmail.com', '09943827270', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Naing Wai Yan - Network Engineer (MT).pdf'),
('Corporate Sales Executive', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Nwe Ni Myo Myint - Corporate Sales Executive (Pathein)MT.pdf'),
('Nyan Lin Htet Data', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Nyan Lin Htet - Data Entry (MT).pdf'),
('Shoon Yupar Aung Portfolio', NULL, NULL, 'Design', NULL, 'active', 'CV Lead Tracker', 'CV: Shoon Yupar Aung - PORTFOLIO 2025.pdf'),
('Technical Skills', NULL, NULL, 'Engineering', 'mysql, postgresql, sql, leadership', 'active', 'CV Lead Tracker', 'CV: KHAING THAZIN MIN- Lead System Engineer (MT).pdf'),
('Kaung Khant Min', 'kaungkhantmin762000@gmail.com', '09762476489', 'Engineering', 'leadership', 'active', 'CV Lead Tracker', 'CV: Kaung Khant Min - Junior Site (MT).pdf'),
('Min Htoo Aung Cashier', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Min Htoo Aung - Cashier (MT).pdf'),
('Key Ount Or', 'eithanarhtay@gmail.com', '09978971054', 'Sales & Marketing', 'excel, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: ei+ Key Account Manager or Executive (MT).pdf'),
('Ye Myat', 'yemyat8599@gmail.com', '959261906175', 'Sales & Marketing', 'python, sql, powerpoint, project management', 'active', 'CV Lead Tracker', 'CV: Ye Myat - Sales Manager (MT).pdf'),
('Htet Htet Zin', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Htet Htet Zin - Sales (Taungoo) MT.pdf'),
('Zin Mar Zu English', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Zin Mar Zu  - English Transalator (MT).pdf'),
('Htet Htun Naing Cb', NULL, '09766030436', 'General/Other', 'excel', 'active', 'CV Lead Tracker', 'CV: Htet Htun Naing cb (Autosaved).pdf'),
('Race - Myanmar', NULL, '09983227417', 'Customer Service', NULL, 'active', 'CV Lead Tracker', 'CV: Zin May Oo - Call Center (MT).pdf'),
('Work Experienceabout Me', 'thethtar3510@gmail.comEmail', NULL, 'Management', 'aws, excel, powerpoint, photoshop', 'active', 'CV Lead Tracker', 'CV: Thet Htar San - Customer Service (MT).pdf'),
('Nilar Win', 'Yangon.nilarwin1993aa@gmail.comContactNilar', '+959779387597', 'Sales & Marketing', 'git, communication', 'active', 'CV Lead Tracker', 'CV: Nilar Win - Manager Financial A (MT) (1).pdf'),
('Khin Zaw Win Qa', NULL, '09780686845', 'Customer Service', NULL, 'active', 'CV Lead Tracker', 'CV: Khin Zaw Win - QA (MT).pdf'),
('Phyu Phway Thant', 'phyuphway17797@gmail.com', '09773399832', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Phyu Phway Thant - Accountant (MT).pdf'),
('Working Experience Excel,email,payroll', NULL, '09772551659', 'HR & Admin', 'aws, excel, communication', 'active', 'CV Lead Tracker', 'CV: Win Win Thu - HR Exevutive (MT).pdf'),
('Problem Solving', 'Ayeyarwaddythinthinaung436@gmail.com', '09680616222', 'Management', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Thin Thin Aung - Corporate RM (MT) AYA.pdf'),
('Nway Zin Win', 'nwayzinwin181729@gmail.com', '959254229884', 'Management', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Nway Zin Win - Sales Engineer (MT).pdf'),
('Chit Hsu Htay', 'chitsuhtay13@gmail.com', '09979196200', 'HR & Admin', 'excel, powerpoint, photoshop, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Chit Hsu Htay - SA (MDY)MT.pdf'),
('Ko Win Naing Procurement', 'winnaing919789@gmail.com', '959792694244', 'Management', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Ko Win Naing - Procurement Executive (MT).pdf'),
('Chaw Su Khaing', NULL, '09762547474', 'Engineering', 'photoshop', 'active', 'CV Lead Tracker', 'CV: Chaw Su Khaing - Executive (Pathein).pdf'),
('Zin Zin Zaw Thant', 'jiwoo2281@gmail.com', '9443705771', 'Healthcare', 'communication', 'active', 'CV Lead Tracker', 'CV: Zin Zin Zaw Thant - Pharmacist (MT).pdf'),
('Ingyin Aye English T', 'eieichaw23720@gmail.com', '959420071181', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Ingyin Aye - English T (MT).pdf'),
('About Of Me', NULL, '09979264742', 'Design', 'git, photoshop, illustrator', 'active', 'CV Lead Tracker', 'CV: Zaw Htet Naung - Graphic Designer (MT).pdf'),
('Cho Khin Yamin', NULL, '0998277798', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Cho Khin Yamin - Sales (MT).pdf'),
('Su Mon Wholele', NULL, '959977951651', 'Management', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Su Mon - Wholesale Manager (MT).pdf'),
('Khin Ndar Htwe', 'khinsandar677@gmail.com', '09400454086', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Khin sandar htwe  - Finance Assistant (MT).pdf'),
('Ei Shwe Sin Myint', NULL, '09791916396', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Ei Shwe Sin Myint - Senior Executive (pathein).pdf'),
('Cho Cho Win', 'civilengr@gmail.com', '09400519252', 'Management', 'excel, powerpoint, problem solving', 'active', 'CV Lead Tracker', 'CV: CHO CHO WIN - Senior Site Engineer (MDY)MT.pdf'),
('Pay Roll', 'phoowaii96@gmail.com', '09258999870', 'Management', 'git, excel, communication', 'active', 'CV Lead Tracker', 'CV: Ms.+Phoo+Wai+Khaing_- Pay roll assistant (MT).pdf'),
('Ohnmar Htwe Qa', 'dawohnmarhtwe00@gmail.com', '09983301712', 'Management', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Ohnmar Htwe -  QA (MT).pdf'),
('Educational Qualification', 'oaksoe4696@gmail.com', '959958231929', 'Engineering', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Oak soe htet - Telecom Maintain Eng (MT).pdf'),
('Thu Htike Lps', 'thuhtike1998@gmail.com', '09788436793', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Thu Htike - LPS (MT).pdf'),
('Chit Su Paing', 'chitsupaing2814@gmail.com', '959776445618', 'Management', 'git', 'active', 'CV Lead Tracker', 'CV: Chit Su Paing - Sales & Marketing (MT).pdf'),
('Toe Toe Naing', NULL, NULL, 'Management', 'git, excel, powerpoint, leadership', 'active', 'CV Lead Tracker', 'CV: Toe Toe Naing - Sales Executive (MT).pdf'),
('Work Experience', 'azayarw95@gmail.com', NULL, 'Data & Analytics', 'aws', 'active', 'CV Lead Tracker', 'CV: Aung Zayar Wint - HSE Officer (MT).pdf'),
('Han Myo Zaw Customer', NULL, '959771622948', 'Management', 'git, communication', 'active', 'CV Lead Tracker', 'CV: Han Myo Zaw - Customer Service (MT).pdf'),
('Okkar Zaw Data Collector', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Okkar Zaw - Data Collector (Team Leader)MT.pdf'),
('Htet Myat Pachi', NULL, '09973461595', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Htet Myat Pachi - Sales (Taungoo)MT.pdf'),
('Personal Details', 'htetwainaing795@gmail.com', '959256900820', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Htet Wai Naing - Site Engineer (MT).pdf'),
('May Phyoe Han', 'mayphyoehan62@gmail.com', '09959925373', 'Sales & Marketing', 'git, communication', 'active', 'CV Lead Tracker', 'CV: May Phyoe Han - Sales & Marketing (MT).pdf'),
('Korea Translator/interpreter', 'khinyadanarsoe08@gmail.com', '09970065364', 'Education', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Khin Yadanar Soe - Korean Translator (MT)_removed.pdf'),
('Personal Details', NULL, '09685039928', 'Management', 'communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Htet Htet Phyo - Customer Service (MT).pdf'),
('Wthidamoe Hr', NULL, '09973071873', 'HR & Admin', 'git, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: SawThidaMoe - HR Manager (MT).pdf'),
('Shwe Zin Oo', 'shwezinoo.shweoo@gmail.com', '09963929497', 'Management', 'git, communication', 'active', 'CV Lead Tracker', 'CV: Shwe Zin Oo - Sales & Marketing Manager (MT).pdf'),
('Ma Thae Nu Wai', 'thaenuwai832002@gmail.com', '959751195049', 'Sales & Marketing', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Ma Thae Nu Wai - Sales Admin (MT).pdf'),
('Thaw Tar Win', 'thawtarwin6@gmail.com', NULL, 'General/Other', 'git, excel', 'active', 'CV Lead Tracker', 'CV: Thaw-Tar-Win-Data Entry (MT).pdf'),
('Nyein Si Thu Hr', 'nyeinsithu088@gmail.com', '09766780520', 'Engineering', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Nyein Si Thu - HR Intern (Insein) MT.pdf'),
('Race - Myanma R', 'yzin981@gmail.com', '09256964237', 'Customer Service', 'communication', 'active', 'CV Lead Tracker', 'CV: Yu Yu Zin - Office Staff (MLM)MT.pdf'),
('Kyaw Htay', 'kyawhtay.ss@gmail.com', '09691181000', 'Management', 'express', 'active', 'CV Lead Tracker', 'CV: Kyaw Htay - Senior Site Engineer (MT).pdf'),
('Kyaw Zin Hein', NULL, '09969659219', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Kyaw Zin Hein - Sales Supervisor (MT).pdf'),
('Wai Linn Htun Noc', 'wailinnhtun76@gmail.com', '09782886211', 'Engineering', 'aws, communication', 'active', 'CV Lead Tracker', 'CV: Wai Linn Htun - NOC (MT).pdf'),
('Strategy First University', NULL, '959455799355', 'HR & Admin', 'agile', 'active', 'CV Lead Tracker', 'CV: Htoo Aung Wint - HR Manager (Insurance )MT - Copy.pdf'),
('Marital Status : Single', NULL, '09440978138', 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Win Moh Moh Thaung - Cashier (TGI).pdf'),
('Myint Myint Thein', NULL, '09972768418', 'Management', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Myint Myint Thein - Finance Assistant (MT).pdf'),
('Shwe Yee Hr', 'shweyeephoo25@gmail.com', '09772655043', 'Sales & Marketing', 'git, excel, photoshop', 'active', 'CV Lead Tracker', 'CV: Shwe Yee - HR Assistant (MT).pdf'),
('Work Experience', 'Charm13381@gmail.comCONTACT', '959687637735', 'HR & Admin', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Aye Chan Moe - Korean Translator (MT).pdf'),
('Tatkon Township,', 'mayphuucho27@gmail.com', '9254028828', 'Management', 'excel, powerpoint, leadership, communication', 'active', 'CV Lead Tracker', 'CV: May Phuu Cho - Korean Translator (MT).pdf'),
('Aung Mon Htoo', NULL, '9786579370', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Mon Htoo - Sales Manager (MDY)MT.pdf'),
('Kyar Nyo Thwe', 'kyarnyothwe2130@gmail.com', '09420076162', 'Management', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: Kyar_Nyo Thwe- Korean Translator (MT).pdf'),
('Htet Myat Cheal Qa', 'htetmyatcheal91@gmail.com', '09794531084', 'Engineering', 'problem solving', 'active', 'CV Lead Tracker', 'CV: Htet Myat Cheal - QA (MT).pdf'),
('Thu Thinzar Sett Hr', 'thuthinzarsett1@gmail.comNo', '09448015674', 'HR & Admin', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Thu Thinzar Sett - HR Executive (D).pdf'),
('Min Ko Thu Linux', 'minkothu2010@gmail.com', '+959799232809', 'Engineering', 'docker, kubernetes, git, excel, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Min-Ko-Thu-Linux Engineer (MT).pdf'),
('Cho Thar Lwin', 'sh8568106@gmail.com', '9421125738', 'Management', 'excel, photoshop, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: CHO THAR LWIN - Executive Assistant (MT).pdf'),
('Ms. Khin Thet Htar', 'maria.khinthethtar@gmail.com', '09962392080', 'Sales & Marketing', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Khin Thet Htar - Freelance Assistant Vice President (MT).pdf'),
('Mrs. Phyo Sandar Oo', 'phyosandaroomm251996@gmail.com', '09770657025', 'HR & Admin', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Phyo Sandar Oo - HR Execuive (MT).pdf'),
('Eaint Thinzar Myo Myint', 'eaintthinzarmyomyint@gmail.com', '09750756516', 'Management', 'express, excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Eaint Thinzar Myo Myint - Sales (MDY) MT.pdf'),
('Curr Iculum Vitate', NULL, NULL, 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Htet Htet Aung - Site Engineer (MT).pdf'),
('Thandae Soe Financial Controller', NULL, '09400965150', 'Management', 'sql, excel', 'active', 'CV Lead Tracker', 'CV: Thandae Soe - Financial Controller (MT).pdf'),
('Win Thiri Kyaw Hr', 'kwinthiri47@gmail.com', '09793594928', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Win Thiri Kyaw - HR Executive (MT).pdf'),
('Personal Info', NULL, '959794932637', 'Sales & Marketing', 'git, leadership', 'active', 'CV Lead Tracker', 'CV: Mya Min Mo Mo - Vice President (MT).pdf'),
('Htet Aung Lin', NULL, '09664934355', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Htet Aung Lin - Sales & Marketing (MT).pdf'),
('W Nann', 'nans12955@gmail.com', '09974940611', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Saw Nann - Sales (MDY).pdf'),
('Han Lin Digital Marketing', 'hlh.hanlin@gmail.com', '9969684172', 'Sales & Marketing', 'git, communication', 'active', 'CV Lead Tracker', 'CV: Han Lin - Digital Marketing Manager (MT).pdf'),
('Hanni Lin Aung', NULL, NULL, 'General/Other', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Hanni-Lin-Aung-Sales & Marketing (MT).pdf'),
('Honey Thae Thae Cashier', 'honeythaethae02104@gmail.com', '09754337300', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Honey Thae Thae - Cashier (MT).pdf'),
('Personal Details', 'phonemyatko1@gmail.com', NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Phone Myat Ko - IT Administrator (MT).pdf'),
('Curriculum Vitae', NULL, '09952718336', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Mg Saw Yan Naung - Purchaser (MT).pdf'),
('Hnin Le Phyu Hr', 'hninlephyu111111@gmail.comHR', '959954882403', 'HR & Admin', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Hnin Le Phyu - HR Assistant (MT).pdf'),
('Shwe Yee Thein Htike', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Shwe Yee Thein Htike - Non Buying (MT) (1).pdf'),
('Win Bhone Myat', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Win Bhone Myat - Sales Opertor (MT).pdf'),
('Kyawsoe Head Of Marketing', 'dr.kyawsoewin@icloud.com', '959795013333', 'Sales & Marketing', 'aws, git, communication', 'active', 'CV Lead Tracker', 'CV: KyawSoe - Head of Marketing (MT).pdf'),
('Than Toe Aung', 'kothantoeaung7017@gmail.com', NULL, 'Management', 'excel, powerpoint, leadership, problem solving', 'active', 'CV Lead Tracker', 'CV: Than Toe Aung - Production Engineer (MT).pdf'),
('Phyu Chay Noc', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Phyu Chay - NOC (MT).pdf'),
('Oak Soe N Customer', 'oaksoe.s@gmail.com', '09973778889', 'General/Other', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Oak Soe San - Customer Service (MT).pdf'),
('Naing Ko Daily Wages', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Naing Ko - Daily Wages.pdf'),
('May Zin Oo', 'oomayzin77@gmail.com', '09753742878', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: May Zin Oo - Corporate Sales (MT).pdf'),
('Htin Shar Network Engineer', 'htinshar084649@gmial.com', '09767699460', 'Engineering', 'python, communication', 'active', 'CV Lead Tracker', 'CV: Htin Shar - Network Engineer (MT).pdf'),
('Ndar Aye', 'masandaraye79@gmail.com', '09785127323', 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Sandar Aye - Sales Admin (MT).pdf'),
('Mee Mee Cho Hr', NULL, '09682668014', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Mee Mee Cho - HR Assistant (MT).pdf'),
('Race - Myanma R', NULL, '09683009419', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Nan Dar Lin - Bank Advisor (Nyaung Tone)MT.pdf'),
('Kaung Hsu', 'kaunghsusan070797@gmail.com', '09797002964', 'Management', 'excel, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Kaung Hsu - Accountant (MLM)MT.pdf'),
('War War Lin Ass', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: War War Lin - Ass Operation Manager (MT).pdf'),
('Personal Details', 'cherrykoko414@gmail.com', NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Resume - Accountant (NPT).pdf'),
('Thar Min Yin Tun', 'nikki10242003@gmail.com', '09784106158', 'Customer Service', 'aws, git, excel, communication', 'active', 'CV Lead Tracker', 'CV: Thar Min Yin Tun - JA (NPT) MT.pdf'),
('Myat Myat Myo', 'myatmyo797877@gmail.com', '959797877944', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Myat Myat Myo - Acc (NPT) MT.pdf'),
('Ei Ei Nyein', 'ein272@gmail.com', '09798009115', 'Sales & Marketing', 'communication', 'active', 'CV Lead Tracker', 'CV: Ei Ei Nyein  Accountant (NPT)MT.pdf'),
('Zin Hnin Thu', 'zinhninthu534@gmail.com', '09979250736', 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Zin Hnin Thu- Accountant (NPT)MT.pdf'),
('Khin May Win', 'khinmaywin2018@gmail.com', '09258835607', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Khin May Win - SA (NPT) MT.pdf'),
('Khin Khin Khant', NULL, '09443390709', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Khin Khin Khant - Senior Accountant (NPT)MT.pdf'),
('Hnin Nda Nwe', 'hninsandinwe@gmail.com', NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Hnin Sanda Nwe - Senior A (MT).pdf'),
('May Me Me', 'maymemelinnhtetoo@icloud.com', '09797082804', 'Engineering', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: May Me Me - JA (NPT) MT.pdf'),
('Thiri Htet Ko', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Thiri Htet Ko - Assistant Sales Manager (MT).pdf'),
('Ei Ei Aung', 'eieiaung.lso2024@gmail.com', '09403706643', 'Management', 'excel, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Ei Ei Aung - Area Sales Manager (MT).pdf'),
('Khw Les', 'nyitharkyaw@gmail.com', '09883988408', 'Management', 'excel, leadership, communication, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: KHW - B2B Sales Executive (MT).pdf'),
('Zin Phyu Htet', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Zin Phyu Htet - Sales & Marketing Executive (MT).pdf'),
('Personal Data', 'htethtethtun201997@gmail.com', '09750217831', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Htet Htet Htun - B2B Sales (MT).pdf'),
('Khw Les', 'nyitharkyaw@gmail.com', '09883988408', 'Management', 'excel, leadership, communication, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: KHW - B2B Sales (MT).pdf'),
('Ei Mon Kyaw', NULL, '959420063851', 'Management', 'communication', 'active', 'CV Lead Tracker', 'CV: Ei Mon Kyaw - B2B Sales Supervisor (MT).pdf'),
('Htet Htet Les', 'bae8111997@gmail.co', '09757853183', 'Management', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Htet Htet - B2B Sales Executive (MT).pdf'),
('Win Zaw Htun', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Win Zaw Htun - Sales Supervisor (MT).pdf'),
('Curriculum Vitae', 'eithet166@gmail.com', '09892032423', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Aye Aye Maw - B2B Sales (MT).pdf'),
('Kaung Khant Zaw', 'khantk857@gmail.com', '959448033440', 'Management', 'excel, leadership, project management', 'active', 'CV Lead Tracker', 'CV: Kaung Khant Zaw - B2B & Retail (MT).pdf'),
('Min Hein Kyaw', 'ayesandarmyint@mmoasis.com', NULL, 'Sales & Marketing', 'communication, project management, analytical', 'active', 'CV Lead Tracker', 'CV: Min Hein Kyaw - Assistant Brand Manager (MT).pdf'),
('Work Experience', 'kyawzawlin100@gmail.com', NULL, 'Management', 'communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Kyaw Zaw Lin - Asssitant Sales Manager (MT).pdf'),
('Thet Soe Paing Oo', 'thetsoepaingoo@gmail.com', NULL, 'Sales & Marketing', 'git, communication', 'active', 'CV Lead Tracker', 'CV: Thet Soe Paing Oo - Assistant Brand Manager.pdf'),
('Thi Thi Than', 'thithilay388@gmail.com', NULL, 'Sales & Marketing', 'git, excel, photoshop, illustrator, leadership, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Thi Thi Than - Assistant Brand Manager (MT).pdf'),
('Thinzar Hlaing', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Thinzar Hlaing - Assistant Marketing Manager (MT).pdf'),
('Htet Htet Myo Aung', '625@gmail.com', '09942737594', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Htet Htet Myo Aung - Assistant B2B Sales Manager (MT).pdf'),
('Banyar Maung Business Analyst', 'banyarspy007@gmail.com', '09882277677', 'Management', 'communication, analytical', 'active', 'CV Lead Tracker', 'CV: Banyar Maung - Business Analyst (MT).pdf'),
('Aye Nandar Aung', 'ayenandaraaung@gmail.com', NULL, 'Management', 'aws, excel, analytical', 'active', 'CV Lead Tracker', 'CV: Aye Nandar Aung - Ass Finance Manager (MT).pdf'),
('Page Personal Information', NULL, '09974300629', 'Management', 'git, excel, communication', 'active', 'CV Lead Tracker', 'CV: Hnin Ei Htwe - Assistnat Showroom Sales Manager (MT).pdf'),
('Career Objective', 'nanhtikethu.58@gmail.com', '09784608034', 'Management', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: Nan Htike Thu - Showroom Sales Manager (MT).pdf'),
('Shar Thinzar Ko Ass', 'sharthinzarko.sgcsgc@gmail.co', '09969924524', 'Management', 'aws, excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Shar Thinzar Ko _ Ass Showroom Sales M (MT).pdf'),
('Htet Aung Ass Warehouse', 'htetplusphyu@outlook.com', '09670285647', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Htet_Aung - Ass Warehouse Manager (MT).pdf'),
('Race - Myanmar (intha)', NULL, '09979216572', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Myat Moh Thwal - Bank Advisor (TGI) MT.pdf'),
('Personal Details', 'eikyiphyu18@gmail.com', '09785620823', 'HR & Admin', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Ei Kyi Phyu - Bank Advisor (TGI)MT.pdf'),
('Tin Zar Win', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Tin Zar Win - No exp (TGI)MT.pdf'),
('Ms. Htet Htet Hlaing', NULL, NULL, 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Htet Htet Hlaing - Bank Advisor (TGI) MT.pdf'),
('Bank Advisor', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Hsu Waddy Naing - Bank Advisor (TGI)MT (1).pdf'),
('Single Female', 'thetthethninsu@gmail.com', '09771928550', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Thet Thet Hnin Su - Bank Advisor (TGI)MT (1).pdf'),
('Myo Ko Ko', 'jhonebae0064@gmail.com', '09789229721', 'Sales & Marketing', 'excel, communication, project management', 'active', 'CV Lead Tracker', 'CV: Myo Ko Ko - Accountant (MDY)MT.pdf'),
('Aye Myat Ko', 'kokoayemyat291@gmail.com', '09758953840', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Aye Myat Ko - Accountatn (MDY)MT.pdf'),
('Win Ndar Nwe Logistic', 'winsandar105@gmail.com', '09420759768', 'Operations', 'excel', 'active', 'CV Lead Tracker', 'CV: Win Sandar Nwe - Logistic (MT).pdf'),
('Contactngu War Haing', 'nguwarhlaing2281994@gmail.com', NULL, 'Management', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: NGU WAR HAING - B2B Slaes Manager (MDY)MT.pdf'),
('Problem Solvingpyae Phyo Aung', 'pyaephyoaung1917@gmail.com', NULL, 'Management', 'excel, problem solving', 'active', 'CV Lead Tracker', 'CV: Pyae Phyo Aung - B2B Sales Manager (MDY)MT.pdf'),
('Phyoe Thinzar Oo', 'phyoethinza565@gmail.com', NULL, 'HR & Admin', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: PHYOE THINZAR OO - B2B Sales Manager (MDY)MT.pdf'),
('Personal Details', 'khinthandarmyint1987@gmail.com', '09776823176', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Khin Thandar Myint - Corporate Relationship Manager (MDY)MT.pdf'),
('Zar Ni Thein', 'zarnithein.30@gamil.com', '09444026582', 'Management', 'excel, powerpoint, leadership, problem solving', 'active', 'CV Lead Tracker', 'CV: Zar Ni Thein - Senior Auditor (MT).pdf'),
('Mya Khaing Thu', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Mya Khaing Thu - Auditor (MT).pdf'),
('Tin Yu Swe', '3@gmail.com', '09256387701', 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Auditor (MT).pdf'),
('Wai Phyo', 'dswaiphyoe@gmail.com', '09971404808', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Wai Phyo - Senior Auditor (MT).pdf'),
('Phyoe Thinzar Aung', 'phyoethinzaraung047@gmail.com', '09788574190', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Phyoe Thinzar Aung - Junior Auditor (MT).pdf'),
('Phone Myat Paing', 'phonemyatpaing.info@gmail.com', '9962641480', 'Management', 'excel, problem solving', 'active', 'CV Lead Tracker', 'CV: Phone Myat Paing - Internal Auditor (MT).pdf'),
('Zwe Phyo Thway', 'zwephyothway28@gmail.com', '09771319801', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Zwe Phyo Thway (CV).pdf'),
('Phyu Phyu Khaing', 'phyuphyukoko16@gmail.com', '09798629394', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Phyu Phyu Khaing (assistant Manager).pdf'),
('Htoo Lwin Oo', 'oohtoolwin054@gmail.com', '09695230850', 'Engineering', 'git, communication', 'active', 'CV Lead Tracker', 'CV: Htoo Lwin Oo - Assistant Engineer (Telecom).pdf'),
('Race - Myanma R', NULL, '09756698457', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Zin Zin Phoo - Bank Advisor (Yat Sauk)MT.pdf'),
('Kyaw Sein Myint Admin', NULL, NULL, 'Management', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Kyaw Sein Myint - Admin Manager (MT).pdf'),
('Maung Min Admin', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Maung Min - Admin Manager (MT).pdf'),
('Personal Information', 'hninnuwah07@gmail.com', '09788292808', 'Management', 'excel, powerpoint, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Hnin Nu Wah(Head of Admin) - FMCG (MT).pdf'),
('Yan Pyay Min Admin', 'yanpyay21@gmail.com', '09964470370', 'Management', 'powerpoint, leadership', 'active', 'CV Lead Tracker', 'CV: Yan Pyay Min - Admin Manager (MT).pdf'),
('Thiri Khaing Les', NULL, '09256048145', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Thiri  Khaing - B2B Sales (MT).pdf'),
('Nilar Win Les', NULL, '09422365001', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Nilar Win - B2B Sales Manager (Insurance)MT.pdf'),
('Aye Min Soe', 'ayeminsoe.mm277@gmail.com', NULL, 'Management', 'leadership', 'active', 'CV Lead Tracker', 'CV: Aye Min Soe - B2B Sales Manager (MT).pdf'),
('Thet Thet Tun Hla', 'thet@gmail.com', '09970974856', 'Sales & Marketing', 'git, excel, powerpoint, leadership', 'active', 'CV Lead Tracker', 'CV: Thet Thet Tun Hla - CRM (MT).pdf'),
('Internal Education', NULL, '09669215208', 'Management', 'analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: Htet Wai Phyo - B2B Sales Manager (MT).pdf'),
('Gender : Male', NULL, '959456623444', 'Management', 'express, excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Tin Htet Kyaw - B2B Sales Manager (MT).pdf'),
('Han Ni Htet', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Han Ni Htet - B2B Sales Manager (MT).pdf'),
('Birth Date', '08@gmail.comEducational', '09974496000', 'Management', 'problem solving', 'active', 'CV Lead Tracker', 'CV: Nay Myo Zet - B2B Sales Manger (MT).pdf'),
('Personal Detail', NULL, NULL, 'Management', 'excel, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Kyaw Zin Thant - B2B Sales Manager (MT).pdf'),
('Corporate Relationship Manager', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Han Ni Htet - Corporate Relationship Manager (MT).pdf'),
('Win Theingi Shein', 'wintheingishein1989@gmail.com', '09444606601', 'Management', 'excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Win Theingi Shein - B2B Sales Manager (MT).pdf'),
('U Hsu Aung', 'kohsuaung85@gmail.com', '099945932242', 'Management', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: U Hsu Aung - B2B Sales M (MT).pdf'),
('Thura Myo', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Thura Myo - Assistant B2B Sales Manager (MT).pdf'),
('Kaung Swam Yee', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Kaung Swam Yee - Assistant Buyer (MT).pdf'),
('Thet Naing Aye Bar', NULL, '09963074935', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Thet Naing Aye - Bar Manager (MT).pdf'),
('Mya Hninn Design Portfolio', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Mya Hninn - Design Portfolio.pdf'),
('Myat Hninn N Architect', 'myahninnsan@gmail.com', NULL, 'General/Other', 'photoshop', 'active', 'CV Lead Tracker', 'CV: Myat Hninn San - Architect (MT).pdf'),
('Okkalapa Tsp', 'thantsintun261297@gmail.com', '09979657702', 'Management', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: Thant Sin Tun - Assistat Sales Manager (MT).pdf'),
('Name -ma Thazin Hlaing', 'thaz52703@gmail.com', '09758785218', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Thazin Hlaing - Bank Advisor (Tat Kone)MT.pdf'),
('Race - Myanmar', 'laelaemoe272@gmail.com', '09941070803', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Lae Lae Moe - Bank Advisor (Tat Kone)MT.pdf'),
('Nay Lin Aung', 'naywattikhin@gmail.com', '959760404615', 'Management', 'aws', 'active', 'CV Lead Tracker', 'CV: Nay Lin Aung - Assistant Operation Manager (MT).pdf'),
('Nawin, Pyay,', 'khaingnwethinn.it@gmail.com', '9952741730', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: KNT-Assistant Brach Manager (Pyay)MT.pdf'),
('Min Min Thet', 'minminthetnwd@gmail.com', NULL, 'Management', 'communication, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: Min Min Thet - Assistant Branch Manager (Pyay)MT.pdf'),
('Yu Par Myo Aung', 'yuparmyoaung07@gmail.com', '959420743889', 'Sales & Marketing', 'git, excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Yu Par Myo Aung - Assistant Markteting Manager (MT).pdf'),
('Personal Infornation', 'minzinthet.mzt@gmail.com', '09777005650', 'Management', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: Min Zin Thet - Area Sales  MDY(MT).pdf'),
('Tun Lin Oo', 'tinlinoopg@gmail.com', '09420775703', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Tun Lin Oo - B2B Sales Manager (NPT).pdf'),
('Thandar Aye Les', 'ms.thandaraye07@gmail.com', '09974193346', 'Management', 'git, excel, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Thandar Aye - B2B Sales Manager (NPT)MT.pdf'),
('Aung Kaung Kyaw', 'aungkkyaw1992@gmail.com', NULL, 'Sales & Marketing', 'git, communication', 'active', 'CV Lead Tracker', 'CV: Aung Kaung Kyaw - Corporate Relationship Manager (NPT).pdf'),
('Personal Data', 'kyipyar7383@gmail.com', NULL, 'Sales & Marketing', 'communication', 'active', 'CV Lead Tracker', 'CV: Kyi Pyar Aung - Agency Sales Manager( ygn & mdy)MT.pdf'),
('Personal Information', 'pannphoohlaing54@gmail.com', '9666663650', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Pann Phoo Hlaing - Corporate Sales Manager (NPT)MY.pdf'),
('Sales & Marketing Manager', 'wuttyee13199@gmail.comEmail', NULL, 'Sales & Marketing', 'git, excel, leadership', 'active', 'CV Lead Tracker', 'CV: Tin Wut Yee Ko - B2B Sales Manager (NPT)MT.pdf'),
('Ei Thuzar Admin', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Ei Thuzar - Admin (MT).pdf'),
('Yadanar Htwe Admin', 'yadanarchan12@gmail.com', '09971180733', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Yadanar Htwe - Admin (MT).pdf'),
('Thin Zar Phyu Admin', NULL, '09421979677', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Thin Zar Phyu - Admin Assistant (MT).pdf'),
('Shalom Lae Way Tun', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Shalom Lae Way Tun - Admin & Finance (MT).pdf'),
('Mi Mi Admin', 'mimi.sunmobile1999@gmail.com', '09269859206', 'HR & Admin', 'excel, photoshop', 'active', 'CV Lead Tracker', 'CV: Mi Mi - Admin Executive (MT).pdf'),
('Thaw Dar Oo Admin', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Thaw Dar Oo - Admin Staff (MT).pdf'),
('Tzh Admin', 'thetzawhtoon.mm@gmail.com', NULL, 'Management', 'aws', 'active', 'CV Lead Tracker', 'CV: TZH - Admin Assistant (MT).pdf'),
('Myat Htet Hein Admin', 'sayargyiinyiu.2233@gmail.com', '959425682454', 'Sales & Marketing', 'git, excel, powerpoint, photoshop, communication', 'active', 'CV Lead Tracker', 'CV: Myat Htet Hein - Admin (MT).pdf'),
('Nandar Aye Win Office', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Nandar Aye Win - Office Admin (MT).pdf'),
('Tun Win Kyaw', 'tunkyaw101203@gmail.com', '09798824683', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Admin (MT) (2).pdf'),
('Myat Min Admin Assitant', 'koh09696@gmail.com', '09698711586', 'Management', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Myat Min - Admin Assitant (MT).pdf'),
('Htzk Admin Supervisor', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: HTZK - Admin Supervisor (MT).pdf'),
('Current Information', 'mgyeko84@gmail.com', '09425311112', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Ye Zaw Aung - Admin Supervisor (MT).pdf'),
('Yan Naung Soe Admin', NULL, '09888019786', 'Engineering', 'photoshop, communication', 'active', 'CV Lead Tracker', 'CV: Yan Naung Soe - Admin (MT).pdf'),
('Nyan Lin Htat Admin', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Nyan Lin Htat - Admin Executive (MT).pdf'),
('Myat Hein Htain Admin', 'sayargyiinyiu.2233@gmail.com', '959425682454', 'Sales & Marketing', 'git, excel, powerpoint, photoshop, communication', 'active', 'CV Lead Tracker', 'CV: Myat Hein Htain - Admin (MT).pdf'),
('Ei Ndar Myo Admin', 'sandyei830@gmail.com', '959429923941', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Ei Sandar Myo - Admin Assistant (MT).pdf'),
('Hsu Wai Wai Htet', 'hsuw8798@gmail.com', '959893416369', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Hsu Wai Wai Htet - Admin Assistant (MT).pdf'),
('Hst S Admin', 'heinsithusithu175453@gmail.com', '09968399331', 'Management', 'excel, photoshop, leadership, communication', 'active', 'CV Lead Tracker', 'CV: HST_s - Admin Assistant (MT).pdf'),
('Kyaw Zin Thant Admin', 'kyawzinthant10394@gmail.com', '09406877366', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Kyaw Zin Thant - Admin Assistant (MT).pdf'),
('Wai Linn Phyoe Admin', 'wailinnphyoe@gmail.com', '09686007486', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Wai Linn Phyoe - Admin Manager (MT).pdf'),
('Zaw Ye Mg Admin', 'zwelayrapsinger1989@gmail.com', '09425481810', 'Management', 'java, excel', 'active', 'CV Lead Tracker', 'CV: Zaw Ye Mg - Admin Manager (MT).pdf'),
('Ye Min Thein Admin', NULL, NULL, 'HR & Admin', 'excel, photoshop, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Ye Min Thein - Admin Manager (MT).pdf'),
('Ei Myat Phyoe Maung', 'eimyatphyoemaung@gmail.com', '959773246951', 'Engineering', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Ei Myat Phyoe Maung - Admin Executive (MT).pdf'),
('Hnin Htet Khaing Admin', NULL, '09
423685809', 'HR & Admin', 'excel, photoshop', 'active', 'CV Lead Tracker', 'CV: Hnin Htet Khaing _ Admin Executive (MT).pdf'),
('Arkar Oo Admin Execuitve', 'EMAILarkaroospt@gmail.comPHONE', '+959771200235', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Arkar Oo - Admin Execuitve (MT).pdf'),
('Thin Thin Aung Admin', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Thin Thin Aung - Admin Executive (MT) East Dagon.pdf'),
('Admin Supervisor', 'epn.eieiphuengon@gmail.co', '959783072373', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Ei Phue Ngon  Admin Supervisor (MT).pdf'),
('Thiri Swe Zin', 'grace.thiri24@gmail.com', '09770573948', 'HR & Admin', 'sql, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Thiri Shwe Zin - Admin Supervisor (MT).pdf'),
('Personal Details', 'hshtet.1994@gmail.com', '09973052088', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Hsu Yee Htet - Admin Supervisor (MT).pdf'),
('Daw Soe Thandar Lin', 'soethandarlin11@gamil.com', '09420252738', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Soe Thandar Lin -Admin Supervisor (MT).pdf'),
('Mrs Thi Thi Tun', 'dawthithi082@gmail.com', '09424188645', 'Management', 'express, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Mrs_Thi Thi Tun - Admin Su (MT).pdf'),
('Pst Admin Supervisior', 'pyaesonethu750@gmail.com', '09421011265', 'HR & Admin', 'excel, photoshop, illustrator, communication, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: PST Admin Supervisior (MT).pdf'),
('Zin May Oo Admin', 'myotinzarshein27@gmail.com', '09963914391', 'Management', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Zin May Oo - Admin Executive (MT).pdf'),
('Yamin Thaung Admin Supervisor', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Yamin Thaung - Admin Supervisor (MT).pdf'),
('Marital Status: Single', 'thethtaraung2411@gmail.com', '959790554394', 'Sales & Marketing', 'react, agile, excel, analytical', 'active', 'CV Lead Tracker', 'CV: Thet Htar Aung 2023 for Makro - A Merchandising Manager (MT).pdf'),
('Kay Khaing Aung Audit', 'kkhineaung2022.mm@gmail.com', '09261537441', 'Finance & Accounting', 'sql', 'active', 'CV Lead Tracker', 'CV: Kay Khaing Aung - Audit Manager (MT).pdf'),
('Audit Manager', NULL, '09961584041', 'Management', 'excel, powerpoint, analytical', 'active', 'CV Lead Tracker', 'CV: Kyaw Htin Lin Zaw - Audit Manager (MT).pdf'),
('Kka Audit', 'kkhineaung2022.mm@gmail.com', '09261537441', 'Finance & Accounting', 'sql', 'active', 'CV Lead Tracker', 'CV: kka - Audit Manager (MT).pdf'),
('Thurein Htun', 'thureinhtun7820@gmail.com', '09794711210', 'Management', 'express, excel', 'active', 'CV Lead Tracker', 'CV: Thurein Htun - Internal Audit Manager (MT).pdf'),
('May Phue Boo', 'mayphuebo@gmail.com', '09956739747', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: May Phue Boo - Accountant (Bago)MT.pdf'),
('Htun Ndar Aung', 'sandarsandar723@gmail.com', '09774861781', 'Sales & Marketing', 'communication', 'active', 'CV Lead Tracker', 'CV: Htun Sandar Aung - Accountant (Bago)MT.pdf'),
('Race - Myanmar', NULL, '09420780014', 'Customer Service', NULL, 'active', 'CV Lead Tracker', 'CV: Saw Nan Wai - Bank Adviosr (NPT)MT.pdf'),
('Yoon Poe Eain Bank', 'yoonpoeeain1998@gmail.com', '9458108637', 'Management', 'excel, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Yoon Poe Eain - Bank Advisor (NPT) MT.pdf'),
('Myat Pal Bank Adviosr', NULL, '0966666866', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Myat Sapal - Bank Adviosr (NPT).pdf'),
('Race - Myanmar', NULL, '09969703023', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Khin Thiri Swe - Bank Advisor (NPT) MT.pdf'),
('Race - Myanma R', 'zuzunaing2019@gmail.com', '09259504497', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Zu Zu Niang - Bank Advisor (MT).pdf'),
('Race - Myanmar', NULL, '09967039310', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Zar Chi Win - Bank Advisor (MDY)MT.pdf'),
('Your Name', 'EIEIKHIN028687@GMAIL.COM', '09446807812', 'Healthcare', NULL, 'active', 'CV Lead Tracker', 'CV: Ei Ei Khin - Bank Advisor (MDY)MT.pdf'),
('Ei Mon Swe Bank', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Ei Mon Swe - Bank Advisor (MDY) (MT).pdf'),
('Race - Myanma R', '8@gmail.com', '09454771336', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Hnin Mon Aung - Bank Adviosr (MDY)MT.pdf'),
('Personal Details', 'yanyan24158@gmail.com', '09966031349', 'Engineering', 'problem solving', 'active', 'CV Lead Tracker', 'CV: Win Win Aye - Bank Advisor (MDY)MT.pdf'),
('Race - Myanma R', 'hsuhtetwai2000@gmail.com', '09444057107', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Hsu Htet Wai - Bank Advisor (MDY)MT.pdf'),
('Thuzar Htay Bank Advisor', 'thuzarhtay513@gmail.com', '09750206548', 'HR & Admin', 'express', 'active', 'CV Lead Tracker', 'CV: Thuzar Htay - Bank Advisor (MDY)MT.pdf'),
('Hein Htet Aung', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Hein Htet Aung - Bank Advisor (Pathein)MT.pdf'),
('Yamin Su Hlaing Bank', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Yamin Su Hlaing - Bank Advisor (MDY)MT.pdf'),
('Myo Thinzar Kyaw Bank', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Myo-Thinzar-Kyaw - Bank Advisor (MDY)MT.pdf'),
('Win Min Kyaw Bank', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Win Min Kyaw - Bank Advisor (MDY)MT.pdf'),
('Phyo Thandar Aung No', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Phyo Thandar Aung - no exo (MT).pdf'),
('Race - Myanma R', NULL, '09250004143', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Hnin Moe Aye - Area Manager (Banca-TGI)MT.pdf'),
('Yin Mu Aung Banca', NULL, '959250095604', 'Management', 'excel, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Yin Mu Aung- Banca (TGI)MT (1).pdf'),
('Hnin Htet Khaing Admin', NULL, '959425756146', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Hnin Htet Khaing - Admin (Taungoo)MT.pdf'),
('Su Wutt Yee', 'hsuwuttyee22@gmail.com', '09958398407', 'HR & Admin', 'aws, communication', 'active', 'CV Lead Tracker', 'CV: Su wutt yee - Ass HR Manager (MT).pdf'),
('Ma Kyi Nuee Lwin', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Ma Kyi Nuee Lwin - Ass HR Manager (MT).pdf'),
('Income Tax.', 'klayar7.mm@gmail.com', '09409673009', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Soe Myat Klayar_-Ass HR Manager (MT).pdf'),
('Personal Details', NULL, '09420971584', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Pwint Pa Pa Than - Ass HR Manager (MT).pdf'),
('Mr. Zin Min Soe', NULL, '09951070844', 'HR & Admin', 'communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Zin Min Soe - Ass HR & Admin Manager (MT).pdf'),
('Naing Lin Soe', 'nlay1093@gmai.com', '+959779950736', 'HR & Admin', 'java, git, excel, communication', 'active', 'CV Lead Tracker', 'CV: Naing Lin Soe - Assistant HR Manager (MT).pdf'),
('Wai Phyo Aung', 'Email-waiphyoaung9255@gmail.com', '09763492512', 'Management', 'git, communication, project management', 'active', 'CV Lead Tracker', 'CV: Wai Phyo Aung - Assistant HR & Admin Manager (MT).pdf'),
('Aye Myat Soe', 'ayemyatmyoaung@gmail.com', '09445563033', 'HR & Admin', 'aws, excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Aye Myat Soe - Ass HR Manager (MT).pdf'),
('Aye Myat Soe', 'ayemyatmyoaung@gmail.com', '09445563033', 'HR & Admin', 'aws, excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Aye Myat Soe - Ass HR Manager (MT).pdf'),
('Swwm Ass Hr', 'shwelay.sww@gmail.com', '09798278892', 'Management', 'aws, communication', 'active', 'CV Lead Tracker', 'CV: SWWM - Ass HR Manager (MT).pdf'),
('Ingyin Ass Hr', 'gyin2421@gmail.com', NULL, 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Ingyin - Ass HR Manager (MT).pdf'),
('Professional Experience', 'Kyawmyowin9089@gmail.com', '09979040986', 'Management', 'git, excel', 'active', 'CV Lead Tracker', 'CV: Kyaw Myo Win_Bank Advisor (MT).pdf'),
('Personal Information', 'zinyadanar81817@gmail.com', '09263081742', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Zin Yadanar Aung - Bank Advisor (MT).pdf'),
('Aye Thiri', 'maysittthwin9@gmail.com', '09898326392', 'Management', 'leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Aye Thiri Aung - Bank Advisor (MT).pdf'),
('Hsu Myat Phyu Banca', 'ellie23579@gmail.com', '09941695711', 'Sales & Marketing', 'git', 'active', 'CV Lead Tracker', 'CV: Hsu Myat Phyu - Banca (MT).pdf'),
('Bank Advisor', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Ei Yadanar Aung - Bank Advisor (MT).pdf'),
('Personal Information', 'phyupwint179@gmail.com', '959758389243', 'Sales & Marketing', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: Pwint Phyu Soe - Bank Advisor (MT)1.pdf'),
('Race - Myanma R', 'akarily.39@gmail.com', '09953479040', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Ei A Kari Htun - Bank Adviosr (MT).pdf'),
('May Thet Khaing Bank', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: May Thet Khaing - Bank Advisor (MT).pdf'),
('Race - Myanmar', 'plin97625@gmail.com', '0925757965', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Pa Pa Lin - Bank Adviosr (MT).pdf'),
('Kay Thi Than Naing', 'kaythizwe@gmail.com', '9989846015', 'Customer Service', NULL, 'active', 'CV Lead Tracker', 'CV: Kay Thi Than Naing - Bank Advisor (MT).pdf'),
('N Min Oo', NULL, '09454255211', 'General/Other', 'excel, communication, analytical, problem solving', 'active', 'CV Lead Tracker', 'CV: San Min Oo (Bancassurance)MT.pdf'),
('Than Naing Aung Bank', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Than Naing Aung - Bank Advisor (MT).pdf'),
('Career Objective', NULL, '09750776781', 'HR & Admin', 'excel, powerpoint, photoshop, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Myo Ko Ko - Bank Advisor (MT).pdf'),
('Htet Htet Oo Bank', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Htet Htet Oo - Bank Advisor (MT) (2).pdf'),
('Kyaw Naing Tun Bancassurance', 'maxsuly471@gmail.com', '09763228152', 'Management', 'analytical', 'active', 'CV Lead Tracker', 'CV: Kyaw Naing Tun - Bancassurance.pdf'),
('Zar Li Htet Bancassurace', 'zarli2744@gmail.com', '09894100643', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Zar Li Htet - Bancassurace.pdf'),
('Father’s Name', 'smilegirl152118@gmail.com', '09253253230', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Hay Man Min Swe - Banca (MT).pdf'),
('Race - Myanma R', NULL, '09780081341', 'Sales & Marketing', 'aws', 'active', 'CV Lead Tracker', 'CV: Hninn Wutt Yee - Bank Advisor (MT).pdf'),
('Nang Eaint Phoo Ngon', NULL, '09454735584', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Nang Eaint Phoo Ngon - Bank Advisor (TGI)MT.pdf'),
('Theint Theint Nway Aung', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Theint Theint Nway Aung - Bank Advisor (MT).pdf'),
('Personal Information', 'phyupwint179@gmail.com', '959758389243', 'Sales & Marketing', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: Pwint Phyu Soe - Bank Advisor (MT).pdf'),
('Handled Daily Sale Operation', 'tswe7246@gmail.comEmail', NULL, 'Engineering', 'communication', 'active', 'CV Lead Tracker', 'CV: Thwe Thwe Swe - Bank Advisor (MT).pdf'),
('Race - Myanmar', '51291@gmail.com', '09755953674', 'Customer Service', NULL, 'active', 'CV Lead Tracker', 'CV: Tin Nay Lar - Bank Advisor (MT).pdf'),
('Pwint Phyu Soe', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Pwint Phyu Soe (Bank Advisor _ YGN) Payslip.pdf'),
('Aye Thandar Tun', NULL, NULL, 'Management', 'excel, powerpoint, photoshop, communication', 'active', 'CV Lead Tracker', 'CV: Aye Thandar Tun - Bank Advisor (MT).pdf'),
('Race - Myanma R', 'slmm133996@gmail.com', '09755662253', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Shoon Lae Myint Mo - Bank Advisor (MT).pdf'),
('Khin Myo Hlaing Bank', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Khin Myo Hlaing - Bank Advisor (MT).pdf'),
('Khine Ndi Bank Advisor', 'sandikhine7@gmail.com', '09442621625', 'Customer Service', 'communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Khine Sandi - Bank Advisor (MT).pdf'),
('May Zin Phyoe', 'mayzinphyoe019@gmail.com', NULL, 'Management', 'leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: May Zin Phyoe - Bank Advisor (MT).pdf'),
('Aye Moh Moh San', 'ayemmsantwentyeight2003@gmail.com', '959763758519', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Aye Moh Moh San - Bank Advisor (MT).pdf'),
('Zin Yadanar Aung', 'zinyadanar81817@gmail.com', '09263081742', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Zin Yadanar Aung - Sales (MT).pdf'),
('Bank Advisor', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Ei Zarchi Phyo - Bank Advisor (MT).pdf'),
('Race - Myanmar', 'yuthandaraung96@gmail.com', '09766099000', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Myo Thandar Aung - Bank Advisor (MT).pdf'),
('Pro File', NULL, '959757007263', 'Sales & Marketing', 'git', 'active', 'CV Lead Tracker', 'CV: Saw Thiri Myo Aung - Bank Adviosr (MT).pdf'),
('Race - Myanma R', NULL, '09984402187', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Jue Jue San - Bank Advisor (MT).pdf'),
('Banyar Aung Bank Advisor', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Banyar Aung - Bank Advisor (MT).pdf'),
('Race - Myanmar', NULL, '0967992634', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Shoon Lae May - Bank Advisor (MT).pdf'),
('May Thin Kyu Bancassurance', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: May Thin Kyu - Bancassurance.pdf'),
('Work Experience', 'hminhtet591@gmail.com', '959977049032', 'Sales & Marketing', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Hein Min Htet - Bank Advisor (MT).pdf'),
('Kyaw Zorr Hein', 'khangnaung739@gmail.com', '09777087050', 'Customer Service', 'communication', 'active', 'CV Lead Tracker', 'CV: Kyaw Zorr Hein - Bank Advisor (MT).pdf'),
('Win Min Oo Bank', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Win Min Oo -Bank Advisor (MT).pdf'),
('Bank Advisor', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Yadanar Aung - Bank Advisor (MT) (1).pdf'),
('Aung Bo Bank Advisor', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Bo -Bank Advisor (MT).pdf'),
('Race - Myanma R', NULL, '09675245500', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Ko Thet - Bank Advisor (MT).pdf'),
('Ndar Myint Bank Advisor', 'myintsandar59@gmail.com', '09771834387', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Sandar Myint - Bank Advisor (MT).pdf'),
('Race - Myanma R', NULL, '09683549951', 'Customer Service', NULL, 'active', 'CV Lead Tracker', 'CV: Shwe Yi Phoo Pwint - Bank Advisor (MT).pdf'),
('Thin Thin Swe Bank', NULL, '09254540337', 'HR & Admin', 'aws, communication', 'active', 'CV Lead Tracker', 'CV: Thin Thin Swe  - Bank Advisor (MT).pdf'),
('Hein Min Htet Bancasurrance', NULL, NULL, 'HR & Admin', 'communication', 'active', 'CV Lead Tracker', 'CV: Hein Min Htet - Bancasurrance (MT).pdf'),
('Race - Myanmar', NULL, '09791817220', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Yin Yin Htay - Bank Adviosr (MT).pdf'),
('Soft Skills', 'pwintphyuaung19604@gmail.com', NULL, 'Customer Service', 'communication', 'active', 'CV Lead Tracker', 'CV: Pwint Phyu Aung - Bank Advisor (MT).pdf'),
('Race - Myanma R', NULL, '09780081341', 'Sales & Marketing', 'aws', 'active', 'CV Lead Tracker', 'CV: Hnin Wut Ye - Bank Advisor (MT).pdf'),
('Thin Nandar Soe', 'thinnandarsoetns@gmail.com', '959752315031', 'Customer Service', 'communication', 'active', 'CV Lead Tracker', 'CV: Thin Nandar Soe - Sales (MT).pdf'),
('Decision Making', 'oeaung12496@gmail.com', '09795326362', 'Sales & Marketing', 'analytical', 'active', 'CV Lead Tracker', 'CV: Than Toe Aung - Bank Advisor (YGN)MT.pdf'),
('Khin Yadanar Bank Advisor', NULL, '09429142884', 'Management', 'git, excel', 'active', 'CV Lead Tracker', 'CV: Khin Yadanar - Bank Advisor (MT).pdf'),
('Pro File', 'eaintphuepaing12@gmail.com', '09786591712', 'Management', 'leadership, communication, project management, analytical', 'active', 'CV Lead Tracker', 'CV: Eaint Phue Paing - Bank Advisor (MT).pdf'),
('Shwe Yee Phoo Pwint', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Shwe Yee Phoo Pwint - Bank Advisor (MT).pdf'),
('Nyein Nyein Htet Bank', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Nyein Nyein Htet - Bank Adviosr (MT).pdf'),
('Working Experiences', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Nyan Linn Phyoe - Bank Advisor (MT) (1).pdf'),
('Khin Nyein Nyein Swe', 'khinnyeinswe29@gmail.com', '959977902972', 'Engineering', 'sql, excel, powerpoint, leadership, communication, analytical', 'active', 'CV Lead Tracker', 'CV: Khin Nyein Nyein Swe - Bank Advisor (MT).pdf'),
('Cho Mar Aung', 'chozin2316@gmail.com', '959254043704', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Cho Mar Aung - Bank Advisor (MT).pdf'),
('Thin Thin Swe Bank', NULL, '09254540337', 'HR & Admin', 'aws, communication', 'active', 'CV Lead Tracker', 'CV: Thin Thin Swe - Bank Advisor (MT).pdf'),
('Marital Status - Married', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Theint Theint Nway Aung - Bank Advisor (YGN)MT.pdf'),
('Race - Myanma R', NULL, '09785288135', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Myo Thu Htun - Bank Adviosr (MT).pdf'),
('Date Of Birth: 19.5.2006', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Myat Bhone Htut - Bank Adviosr (MT).pdf'),
('Sale Executives', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Thet Nandar Soe - Bank Advisor (MT).pdf'),
('Su Su Mon Bank', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Su Su Mon - Bank Advisor (MT).pdf'),
('Contact Info', 'khinsandarmyintaye.kk@gmail.com', '09420703131', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Khin Sandar Myint Aye - Bank Advisor (MT).pdf'),
('Race - Myanma R', NULL, '09758563465', 'Customer Service', NULL, 'active', 'CV Lead Tracker', 'CV: Su Myat Htwe - Bank Advisor (MT).pdf'),
('Arkar Hein Htet Soe', 'arkarheinhtetsoe@gmail.com', '09421105471', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Arkar Hein Htet Soe - Life Insurance Consultant (MT).pdf');