-- ============================================
-- CV Lead Tracker - Batch 5 of 5
-- Leads 2001 to 2161
-- ============================================

INSERT INTO leads (name, email, phone, current_position, skills, status, source, notes) VALUES
('Mr Aung Phyo Zaw', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Mr-Aung-Phyo-Zaw-New-Resume (1).docx'),
('Khin Zaw Win Qa', NULL, '09780686845', 'Customer Service', NULL, 'active', 'CV Lead Tracker', 'CV: Khin Zaw Win - QA (MT).docx'),
('Aung Pyae Phyo', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Pyae Phyo - Sales & M Supervisor (MT).docx'),
('Lwin Myo Hein Noc', 'lwink9905@gmail.com', '959789962537', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Lwin Myo Hein - NOC (MT).docx'),
('Shwe Poe Htel', 'shwepoehtel5120@gmail.com', '09977424193', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Shwe Poe Htel - Sales (Taungoo) MT.docx'),
('Zaw Htun Hlaing', 'zawhtun.hlaing07@gmail.com', '959762232778', 'HR & Admin', 'aws, excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Zaw Htun Hlaing (HR Officer) - MT.docx'),
('Aein Kyi Phyu', 'cindy171199@gmail.com', '09409755579', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Aein Kyi Phyu - Senior Sales Admin (MT).docx'),
('Ei Shwe Sin Myint', NULL, '09791916396', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Ei Shwe Sin Myint - Executive (Pathein).docx'),
('Ei Moh Moh', NULL, '959794593980', 'Operations', 'excel', 'active', 'CV Lead Tracker', 'CV: Ei-Moh-Moh-San - Documentation Executive (MT).docx'),
('Dear Sir/madame,', 'itdragon1992@gmail.com', '09799861146', 'HR & Admin', 'project management', 'active', 'CV Lead Tracker', 'CV: Hein Lin Htun - HR & Admin (MT).docx'),
('Personal Information', NULL, NULL, 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Hnin Nandar Aye - HR Intern (MT).docx'),
('Lwinmar Nwe', 'marlwin731@gmail.com', '959761196726', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Lwinmar Nwe- Stock (MT).docx'),
('Aye Chan Myat Phyo', NULL, NULL, 'Sales & Marketing', 'express, leadership', 'active', 'CV Lead Tracker', 'CV: Aye Chan Myat Phyo - Trade Marketing Manager (MT).docx'),
('Aung Thet', NULL, '09771395907', 'Legal', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Thet (QA).docx'),
('Personal Information', NULL, NULL, 'General/Other', 'excel', 'active', 'CV Lead Tracker', 'CV: Htoo Pyae Pyae Tun Cashier 01 CV-350000.docx'),
('Kyaw Thet Operation', 'kyawthet41014@gmail.com', '09965152520', 'Management', 'excel, powerpoint, leadership, communication', 'active', 'CV Lead Tracker', 'CV: Kyaw Thet - Operation Manager (Retial)MT.docx'),
('Apply Position Warehouse Manager', NULL, '09260504137', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: DAAM_CV Word for WH Manager 29.5.24.docx'),
('Khin Moh Moh Qa', NULL, '09670277727', 'Management', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Khin Moh Moh - QA (MT).docx'),
('Zwe Mg Mg Latt', 'mgmglattzwe@gmail.com', '09770464314', 'Management', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Zwe Mg Mg Latt - Sales Manager (MT).docx'),
('Myo Fleet Supervisor', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Myo - Fleet Supervisor (MT).docx'),
('Phyo Wai Zin Oo', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Phyo Wai Zin Oo - HR Executive (MT).docx'),
('Education Background', 'gomancing2018@gmail.com', '09448053241', 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Go-Man-Cing-Export & Import Document (MT).docx'),
('Htein Lin Kyaw', 'hteinlinkyaw28102000@gmail.com', '09777793419', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Hein Min Htet - Customer Service (MT).docx'),
('Wai Hlyan Hr', NULL, '09771752685', 'HR & Admin', 'git, excel', 'active', 'CV Lead Tracker', 'CV: Wai Hlyan - HR Assistant (MT).docx'),
('Name Aye Aye Myo', NULL, NULL, 'HR & Admin', 'powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Aye Aye Myo - HR Assistant fresher (MT).docx'),
('N Win Thein Hr', NULL, NULL, 'Management', 'aws', 'active', 'CV Lead Tracker', 'CV: San Win Thein - HR Manager (MT).docx'),
('Thank Zin Kyaw Driver', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Thank Zin Kyaw - Driver (MT).docx'),
('Pyae Phyo Thu Hr', 'ppthuogvon@gmail.com', '09984062592', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Pyae Phyo Thu - HR Executive (MT).docx'),
('Ms. Mon Mon Thaw', 'monmonthawdar@gmail.com', '9400432896', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: MonMonThaw-(IT Teacher).docx'),
('Su Myat Khaing', 'suumyatkhaing@gmail.com', NULL, 'Engineering', 'analytical', 'active', 'CV Lead Tracker', 'CV: Su Myat Khaing - Senior IT Officer (MT).docx'),
('Ohnmar Tin Than Hr', 'ohmmar90@gmail.com', NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Ohnmar Tin Than - HR Manager (NPT)MT.docx'),
('Ssm Branch', 'sanmaw20.89@gmail.com', '09765414079', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: SSM - Branch Manager (MT).docx'),
('Ko Mes General', NULL, NULL, 'Management', 'leadership, communication', 'active', 'CV Lead Tracker', 'CV: KO JAMES - General Manager (MT).docx'),
('Twl Qa', NULL, NULL, 'Engineering', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: TWL - QA (MT).docx'),
('Khin Thandar Nyein', 'khinthandarmyint1987@gmail.com', '09776823176', 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Khin Thandar Nyein - Sales Manager (MDY).docx'),
('Khine Zin Cashier', 'khingthazintun43@gmail.com', '09793057724', 'Finance & Accounting', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Khine Zin - Cashier (MT).docx'),
('Thu Thu Hr', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Thu Thu - HR Executive (MT).docx'),
('Khin Hlaing', 'kyawkyawaung525@gmail.com', '09790788827', 'Sales & Marketing', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Khin Hlaing - Sales Manager (MDY)MT.docx'),
('May Pyae Pyae Phyo', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: May Pyae Pyae Phyo-  Sales & Marketing Manager (MT).docx'),
('Personal Profile', NULL, '09980572951', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: CV - HR Executive (MT).docx'),
('Personal Paticular', 'aungthurakhine95@gmail.com', NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Thura Khine - Network Engineer (MT).docx'),
('Ei Thandar Maw Hr', 'eithandarmaw777@gmail.com', '09977033989', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Ei Thandar Maw - HR Executive (MT).docx'),
('W Lal Gay Htoo', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Saw Lal Gay Htoo-RESUME(1).docx'),
('Head Of Les', 'kyawthetthet953@gmail.com', NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Kyaw+Thet - Head of Sales (MT).docx'),
('Nan Yu Hlaing', NULL, '09885006617', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: 1_Nan Yu Hlaing - Sales (Modern T) MT.docx'),
('Thet Wai Aung', 'athetwai762@gmail.com', '09253670034', 'Management', 'leadership', 'active', 'CV Lead Tracker', 'CV: Thet Wai Aung - Senior A (MDY)MT.docx'),
('Khin Nway Nway Hr', 'khinnwaynway281@gamail.com', '09676788593', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Khin Nway Nway - HR Assistant (MT).docx'),
('Khin Nyunt It', 'khinnyunt2195@gmail.com', NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Khin Nyunt - IT.docx'),
('Phyo Pyae Sone', 'puttichaioppiam@gmail.com', '09403707226', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Phyo Pyae Sone - Senior HR Manager (MT).docx'),
('Oo Aung Than Qa', 'aungthanoo32@gmail.com', '09976471239', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Oo Aung Than - QA (MT).docx'),
('Chaw Su Han Machine', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Chaw Su Han - Machine Operator (MT).docx'),
('Hla Myo Nwe', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Hla Myo Nwe - Sales Admin (MT).docx'),
('Win Niang Qc', NULL, '09968719955', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Win Niang - QC (MT).docx'),
('Jhue Qa', NULL, NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Jhue - QA (MT).docx'),
('Aung Thu Production Engineer', 'aungthu.ygn86@gmail.com', '09400547937', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Thu - Production Engineer (MT).docx'),
('Myo Aung Win It', 'myoaungwin.w@gmail.com', '959968423723', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: Myo Aung Win - IT Assistant (MT).docx'),
('Thazinoo Qa Supervisor', 'mzin26918@gmail.com', '09795545114', 'Engineering', 'excel', 'active', 'CV Lead Tracker', 'CV: ThazinOo - QA Supervisor (Beverage).docx'),
('Aung Pyae Sone', NULL, NULL, 'Management', 'leadership', 'active', 'CV Lead Tracker', 'CV: Aung Pyae Sone - Sales & Marketing (MT).docx'),
('Htike Ko Ko Aung', NULL, NULL, 'Sales & Marketing', 'git, excel, project management', 'active', 'CV Lead Tracker', 'CV: Htike Ko Ko Aung - Sales M (TGI)MT.docx'),
('Min Myat Kyaw Mep', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: min myat kyaw - MEP Modeller (MT).docx'),
('Stt Hr', NULL, '09260569229', 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: STT-HR Manager (MT).docx'),
('Curriculum Vitae', NULL, '09750455340', 'Management', 'excel, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Myo Zin Aung - Corporate RM (MT).docx'),
('Applied Position', NULL, '09941006554', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Kyaw Zin Oo 0 HR Execuitve (MT).docx'),
('Aye Aye Win', 'ayeaye.win1284@gmail.com', '09409227711', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Aye Aye Win - Finance Assistant (MT).docx'),
('Ktr Telecom Installation Engineer', NULL, '09889672191', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: KTR - Telecom Installation Engineer (MT).docx'),
('Phone Myat Ko It', 'phonemyatko1@gmail.com', NULL, 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: Phone Myat Ko - IT Administrator (MT).docx'),
('Htet Paing Myo', 'htetpaingmyo99@gmail.com', '09960669124', 'Engineering', 'excel, leadership', 'active', 'CV Lead Tracker', 'CV: Htet Paing Myo - Head of Netwrok Engineer (MT).docx'),
('Thaw Thaw Htun Portfolio', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Thaw Thaw Htun - Portfolio Manager (MT).docx'),
('I Mg Mg Htwe', NULL, '959956659273', 'Management', 'excel, powerpoint, leadership, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Sai Mg Mg Htwe - Sales Manager (MT).docx'),
('No.(100), Wakhema, Ayeyarwady Region', 'maythuthutun212@gmail.com', NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: jj(CV Form) Ma May Thu Thu Tun - Copy.docx'),
('Mya Thida Front Office', 'myathidar262@gmail.com', '09962792174', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Mya Thida - Front office manager (MT).docx'),
('Other Qualifications:', 'winnandar1052000@gmail.com', '09779876636', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: winnandar_Senior Cashier (MT).docx'),
('Hay Man Hnin Hr', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Hay Man Hnin - HR Assistant (MT).docx'),
('May Myat', 'maymyatoo.telenor@gmail.com', '09661832666', 'General/Other', 'excel', 'active', 'CV Lead Tracker', 'CV: May Myat - Executive (pathein).docx'),
('Curriculum Vitae', NULL, NULL, 'Management', 'excel', 'active', 'CV Lead Tracker', 'CV: Nilar Win Shwe - Korean Translator (MT).docx'),
('Nilar Win Application Specialist', 'nilarwin3@gmail.com', '959799652577', 'HR & Admin', 'communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Nilar_Win_- Application Specialist.docx'),
('Zin Thu Win', 'zinthuwin1416@gmail.com', '09940294043', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Zin Thu Win Branch Cashier Pathein CV.docx'),
('Mya Theingi Aung', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Mya Theingi Aung - Senior Sales Admin (MT).docx'),
('Ma Aye Pyae Sone', 'ayejuly928@gmail.com', '09972555966', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Aye Pyae Sone - Customer Service (MT).docx'),
('Pyae Sone Aung It', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Pyae Sone Aung - IT Support (MT).docx'),
('Kyi Lae Lae Win', NULL, '09762775786', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Kyi Lae Lae Win - Sales (MT).docx'),
('Ma Thet Thet Oo', NULL, '09979602171', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: Thet Thet Oo - HR & Admin Manager (MT).docx'),
('Race - Burmese', NULL, '09769180935', 'Customer Service', NULL, 'active', 'CV Lead Tracker', 'CV: Phyo Thu Zar - Non Buying (MT).docx'),
('Win Tun Aung Hr', 'wintunaung1988@gmail.com', '09960510955', 'HR & Admin', 'communication', 'active', 'CV Lead Tracker', 'CV: Win Tun Aung - HR & Admin Manager (MT).docx'),
('Ms. May Phyo Thu', 'maythuit15@gmail.com', '09977172453', 'Engineering', NULL, 'active', 'CV Lead Tracker', 'CV: May Phyo Thu - Odoo Developer (MT).docx'),
('Google Workspace', NULL, NULL, 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: May_Nandar_Kyaw - English Translator (MT).docx'),
('Pyae Sone Aye', 'pyaesoneaye660@gmail.com', '09798000513', 'Sales & Marketing', 'excel', 'active', 'CV Lead Tracker', 'CV: Pyae Sone Aye CV - Sales Admin (MT).docx'),
('Driving License No', 'kyawzinthant24990@gmail.com', '09252280471', 'Sales & Marketing', 'git, leadership', 'active', 'CV Lead Tracker', 'CV: Kyaw Zin Thant - Operation Supervisor (MT).docx'),
('Tun Tun', 'mayyehtut1992@gmial.com', '09256518447', 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Tun Tun - Accountant (MPT) MT.docx'),
('Mr. Ko Ko Lwin', 'alexhonn19@gmail.com', NULL, 'Management', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Ko Ko Lwin - Area Sales Manager (MT).docx'),
('Pyae Phyo Khaing', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Pyae Phyo Khaing - Sales (MT).docx'),
('Htet Lin Paing', 'htetlinpaing@gmail.com', '09790625198', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Htet Lin Paing - B2B, Sales leader(MT).docx'),
('Yan Naung Soe', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Yan Naung Soe - B2B Sales Executive (HTY)MT.docx'),
('Yan Naing Aung', 'yannaingaung6@gmail.com', '09450042549', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Yan Naing Aung - Assistant Finance M (MT).docx'),
('Nay Chey Nu Lwin', NULL, NULL, 'HR & Admin', 'excel, powerpoint, photoshop, leadership', 'active', 'CV Lead Tracker', 'CV: Nay Chey Nu Lwin - Assistant Manager (MT).docx'),
('Chit Su Wai Admin', 'teresawai26@gmail.com', '09254416161', 'HR & Admin', 'leadership, project management', 'active', 'CV Lead Tracker', 'CV: Chit Su Wai - Admin Manager (MT).docx'),
('Personal Resume', 'soehaymarnaing21@gmail.com', '09679251999', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Soe Hay Mar Naing - B2B Sales Manager (MT).docx'),
('Khin Thuzar Lwin', 'mphyusin86@gmail.com', '09756969421', 'Sales & Marketing', 'communication', 'active', 'CV Lead Tracker', 'CV: Khin Thuzar Lwin - Sales Manager (MT).docx'),
('Kyi Pyar Aung', 'kyipyar7383@gmail.com', '0943206529', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Kyi Pyar Aung - Sales Manager (NPT)MT.docx'),
('Khine Admin', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Khine - Admin (MT).docx'),
('Kyaw Htay Admin', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Kyaw Htay - Admin (MT).docx'),
('Win Win Hlaing Admin', NULL, NULL, 'HR & Admin', NULL, 'active', 'CV Lead Tracker', 'CV: Win Win Hlaing - Admin Assistant (MT).docx'),
('Soe Htet Audit', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Soe Htet - Audit Manager (MT).docx'),
('Personal Details', 'naingtunwin949@gmail.com', '09890577279', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Naing Tun Win - Bank Advisor (NPT) MT.docx'),
('Thuta Aung Bank Advisor', 'tuta41298@gmail.com', '09972080490', 'Sales & Marketing', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Thuta Aung - Bank Advisor (MDY).docx'),
('Khin Yamon Lin', 'khinyamonlinn1@gmail.com', '9595019562', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Khin Yamon Lin - Accountant (HTY)MT.docx'),
('Su Myat Sandar', 'sumyat25518@gmail.com', '09786321871', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Sumyatsandar- Account Payable (MT).docx'),
('Htet Htet Kyaw', '11111htethtetkyaw@gmail.com', '09450688520', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Htet Htet Kyaw - Accountant (MT).docx'),
('Ei Nandar Phyo', 'einandarp1994@gmail.com', '09254833395', 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: Ei Nandar Phyo  - Stock Accountant(MT).docx'),
('Personal Information', 'thandar.08.myk@gmail.com', '0943109821', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: SA ( MT).docx'),
('Shine Wana', 'shinewana2991@gmail.com', '09970004482', 'Finance & Accounting', 'excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Shine Wana - SA (MT).docx'),
('Su Thandar Hlaing', NULL, '09250155568', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Su thandar_hlaing - Senior Accountant (MT).docx'),
('Nrc No - 12/tgk(n)174449', 'dreamknight171@gmail.com', '09760990673', 'Finance & Accounting', 'sql', 'active', 'CV Lead Tracker', 'CV: SMH - Senior Accountant (MT).docx'),
('Ngu War Khaing', 'nguewar.009@gmail.com', '09778162050', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Ngu War Khaing - Senior Accountant (MT).docx'),
('Curriculum Vitae', NULL, '09771497574', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Hnin+Sapal+Hlaing - Senior Accountant (MT).docx'),
('Pyone Pyone Sr Oountant', 'thitkhatmaymay@gmail.com', NULL, 'Management', 'communication, analytical', 'active', 'CV Lead Tracker', 'CV: Pyone Pyone - Sr Accoountant (MT).docx'),
('Wai Wai Kyu', 'waiwaikyu35@gmail.com', '09783521787', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Wai Wai Kyu - Senior A (Restaurant)MT.docx'),
('Nan Ohnmar', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Nan Ohnmar - Senior Accountant (Kamaryut)MT.docx'),
('Kyi Kyi Myint', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Kyi Kyi Myint - SA (MT).docx'),
('Myint Bal Lwin', 'myintsaballwin87@gmail.com', '09762022492', 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Myint Sabal Lwin - Senior Accountant (Construction)MT.docx'),
('Thin Su Nandar', NULL, NULL, 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Thin Su Nandar -Senior Accountant (MT).docx'),
('Curriculum Vate', 'thaemonaung4403@gmail.com', '959684483328', 'General/Other', 'excel', 'active', 'CV Lead Tracker', 'CV: Thae - Acc no exp (MT).docx'),
('Thae Unior', 'thaemonaung4403@gmail.com', '959684483328', 'General/Other', 'excel', 'active', 'CV Lead Tracker', 'CV: Thae - unior Acc (No exp) MT.docx'),
('Htet Wai Yan', 'riosrios1290@gmail.com', '09669693855', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Htet Wai Yan - MT.docx'),
('Hla Myo Htet', 'Hlamyohtet133@gmail.com', '09785833474', 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Hla Myo Htet - Junior Accountant (MT).docx'),
('Kyawt Kyawt Myint', 'kyawtkyawtmyint0@gmail.com', '09780927271', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Kyawt Kyawt Myint - Junior A (MT).docx'),
('Htet Wai Yan', 'riosrios1290@gmail.com', '09669693855', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Htet Wai Yan - Junior A (MT).docx'),
('May Pann Ei Phyu', 'maypanneiphyu@gmail.com', '959778778437', 'HR & Admin', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: May Pann Ei phyu - JA (MT).docx'),
('Shin Min Hlaing', 'shinminhlaing2024@gmail.com', '09664922366', 'HR & Admin', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Shin_Min_Hlaing - JA (MT).docx'),
('Yin Nwe Tun J', 'yinnwetun00@gmail.com', '09969957047', 'Finance & Accounting', 'excel, powerpoint', 'active', 'CV Lead Tracker', 'CV: Yin Nwe Tun  - J A(MT).docx'),
('Hsu Myat Yadanar', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Hsu Myat Yadanar - JA (MT).docx'),
('Ei Mon Aung', NULL, '09758872854', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Ei Mon Aung - SA (MT).docx'),
('Hla Myo Htet', 'Hlamyohtet133@gmail.com', '09785833474', 'Finance & Accounting', 'excel, communication', 'active', 'CV Lead Tracker', 'CV: Hla Myo Htet - Junior Accountant (MT).docx'),
('Ei Pwint Phyu', 'eipwintp01@gmail.com', '95975825326', 'Legal', 'excel, powerpoint, communication', 'active', 'CV Lead Tracker', 'CV: Ei Pwint Phyu - JA (MT).docx'),
('Wint Yi Win', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Wint Yi Win- Accountant & Cashier (MT).docx'),
('Shoon Lae Paing S', 'Spaing2000@Gmail.com', '09961944998', 'Customer Service', 'express, excel, communication, problem solving', 'active', 'CV Lead Tracker', 'CV: Shoon Lae Paing_s - Accountant (Pathein)MT.docx'),
('Nway Nway', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Nway Nway Oo( Accountant) - MT.docx'),
('Su Thet', 'oos60587@gmail.com', '09459877665', 'Engineering', 'sql, excel', 'active', 'CV Lead Tracker', 'CV: Su Thet - Accountant (MT).docx'),
('Yee Yee Mon', 'moonbeam.yym@gmail.com', '09965451167', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Yee Yee Mon - Accountant (MT).docx'),
('Aye Zin Mar', 'ayezinmar.ayezinmar@gmail.com', '09756802005', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Aye Zin Mar - Accountant (MT).docx'),
('Pwint Wai Oo', 'nanpwintwaioo646899@gmail.com', '09751092273', 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Pwint Wai Oo - Accountant (MT).docx'),
('Ai Myat Nway', 'aimyatnway931@gmail.com', '09982619947', 'HR & Admin', 'excel', 'active', 'CV Lead Tracker', 'CV: AI MYAT NWAY - Accountant (MT).docx'),
('Su Wai', 'suwaip8y0@gmail.com', '09795870912', 'Finance & Accounting', 'excel', 'active', 'CV Lead Tracker', 'CV: Su Wai - Accountant (MT).docx'),
('Nwe Nwe Aung', 'nwenweaung829@gmail.com', '09440630761', 'Engineering', 'sql, excel', 'active', 'CV Lead Tracker', 'CV: Nwe Nwe Aung - Accountant (MT).docx'),
('Kuy Kyu Aye', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Kuy_Kyu_Aye - Accountant (MT).docx'),
('Yadanar Hlaing', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Yadanar Hlaing - Accountant (MT).docx'),
('Wai Lar Moe', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Wai Lar Moe - Accountant (MT).docx'),
('Thiri Zaw', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: Thiri Zaw - Accountant (Res)MT.docx'),
('Zaw', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: ~$iri Zaw - Accountant (Res)MT.docx'),
('Kyaw Ye Tun', 'kyavvye@gmail.com', NULL, 'General/Other', 'problem solving', 'active', 'CV Lead Tracker', 'CV: Kyaw+Ye+Tun+BD Manager (MT).docx'),
('Khine Htoo Bd', 'khinehtookk@gmail.com', '09261003143', 'Management', 'leadership', 'active', 'CV Lead Tracker', 'CV: Khine Htoo - BD Manager (MT).docx'),
('Soe Ko Ko Corporate', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Soe Ko Ko - Corporate RM (MT).doc'),
('Kyaw Swar Htoon Hse', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Kyaw Swar Htoon - HSE Officer (MT).doc'),
('Zaw Ye Wint Aung', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Zaw Ye Wint Aung  - Senior System Enginer (MT).doc'),
('Aye Theingi Myint Leasing', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Aye Theingi Myint - Leasing Executive (MT).doc'),
('May Thu Hr', NULL, NULL, 'Management', NULL, 'active', 'CV Lead Tracker', 'CV: May Thu - HR Manager (MT).doc'),
('Aung Pyae Phyo Media', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: Aung Pyae Phyo - Media Production (MT).doc'),
('Pyi Htet Paing', NULL, NULL, 'Sales & Marketing', NULL, 'active', 'CV Lead Tracker', 'CV: Pyi Htet Paing - Sales & Marketing (MT).doc'),
('Myo Myo Thwe', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: -Myo Myo Thwe - Junior A (MT).doc'),
('Myo Myo Thwe', NULL, NULL, 'General/Other', NULL, 'active', 'CV Lead Tracker', 'CV: -Myo Myo Thwe - Junior A (MT).doc'),
('Khaing Zar', NULL, NULL, 'Finance & Accounting', NULL, 'active', 'CV Lead Tracker', 'CV: khaing zar - Accountant (MT).doc');